export const ANIME_THEME: any = {
  "intro-print": {
    title: "Battle Cry: Hello Shonen World",
    headerPrefix: "HERO_ACADEMY",
    missionPrefix: "HERO_CALL",
    intro: "# Awakening Your Fighting Spirit: print()\n\nWelcome to the Hero Academy! Whether you're training under All Might, sailing the Grand Line with the Straw Hats, or joining the Demon Slayer Corps, every shonen legend begins with a spirited battle cry.",
    technical: "In Python, the `print()` function displays whatever message or text you place inside its parentheses onto the console screen.",
    example: "print(\"Plus Ultra!\")",
    task: "### YOUR MISSION\n\nUse `print()` to shout out your hero battle cry: `\"Plus Ultra!\"`",
    baseCode: "# TODO: Shout out your hero battle cry\n",
    hints: ["Type print(\"Plus Ultra!\")", "Ensure the text is enclosed in double quotes"],
    solution: "print(\"Plus Ultra!\")",
    solutionRegex: [/print\s*\(\s*['"]Plus Ultra!['"]\s*\)/]
  },
  "naming-conventions": {
    title: "Guild Registry: Lowercase Names",
    headerPrefix: "CORPS_REGISTRY",
    missionPrefix: "HERO_INDEX",
    intro: "# Hero Guild Registry: Lowercase Names\n\nThe Demon Slayer Corps ledger requires strict case-sensitive formatting. All rank and stamina variables must follow snake_case naming conventions and remain lowercase.",
    technical: "Python variables must start with a lowercase letter or underscore, with words joined by underscores `_`.",
    example: "slayer_rank = 1\nprint(slayer_rank)",
    task: "### YOUR MISSION\n\nCreate a lowercase variable named `slayer_rank` and assign its value to `10` (the Mizunoto starter rank). Print it with `print()` to confirm.",
    baseCode: "# TODO: Store slayer_rank variable and print it\n",
    hints: ["Write slayer_rank = 10", "On the next line, write print(slayer_rank)"],
    solution: "slayer_rank = 10\nprint(slayer_rank)",
    solutionRegex: [/slayer_rank\s*=\s*10/, /print\s*\(\s*slayer_rank\s*\)/]
  },
  "intro-comments": {
    title: "Sword Forms: Battle Comments",
    headerPrefix: "BREATHING_SCROLL",
    missionPrefix: "KATA_NOTE",
    intro: "# Secret Katas: Comments\n\nWhen mastering Total Concentration Breathing, master swordsmen write secret notes in the margins of ancient technique scrolls to memorize sword stance transitions.",
    technical: "Lines beginning with `#` are comments. Python ignores them, making them ideal for tactical notes and battle strategy memos.",
    example: "# Water Breathing First Form\nprint(\"Water Surface Slash!\")",
    task: "### YOUR MISSION\n\nWrite a comment `# Water Breathing First Form` and then `print(\"Water Surface Slash!\")`",
    baseCode: "# TODO: Add breathing scroll comment and execute strike\n",
    hints: ["Line 1: # Water Breathing First Form", "Line 2: print(\"Water Surface Slash!\")"],
    solution: "# Water Breathing First Form\nprint(\"Water Surface Slash!\")",
    solutionRegex: [/#.*Water Breathing First Form/, /print\s*\(\s*['"]Water Surface Slash!['"]\s*\)/]
  },
  "comments-inline": {
    title: "Hero Dossier: Inline Comments",
    headerPrefix: "HERO_PROFILE",
    missionPrefix: "QUIRK_TAG",
    intro: "# Quirk Registration: Inline Comments\n\nRecord a hero trainee's power rating alongside their variable assignment without altering system execution.",
    technical: "Inline comments appear directly on the same line after executable code, separated by `#`.",
    example: "hero_stamina = 100 # Maximum spirit energy",
    task: "### YOUR MISSION\n\nInitialize `hero_stamina` to `100`. On the same line, add an inline comment `# Maximum spirit energy`.",
    baseCode: "# TODO: Initialize variable with inline comment\n",
    hints: ["Write hero_stamina = 100 followed by # Maximum spirit energy on the same line."],
    solution: "hero_stamina = 100 # Maximum spirit energy",
    solutionRegex: [/hero_stamina\s*=\s*100/, /#.*Maximum spirit energy/]
  },
  "intro-vars": {
    title: "Hero Vitals: Variables",
    headerPrefix: "SPIRIT_GAUGE",
    missionPrefix: "CHAKRA_ALLOC",
    intro: "# Spirit Energy Storage: Variables\n\n**What is a Variable?** Think of a **variable** as a **scabbard or stamina meter**! You give it a name (like `stamina_points`), store hit points or spirit power inside, and draw from it when unleashing ultimate attacks.",
    technical: "Variables store values that can be referenced and modified throughout your program.",
    example: "stamina_points = 100\nbounty_gold = 5000",
    task: "### YOUR MISSION\n\nCreate `stamina_points` set to `100` and `bounty_gold` set to `5000`.",
    baseCode: "# TODO: Store stamina_points and bounty_gold\n",
    hints: ["stamina_points = 100", "bounty_gold = 5000"],
    solution: "stamina_points = 100\nbounty_gold = 5000",
    solutionRegex: [/stamina_points\s*=\s*100/, /bounty_gold\s*=\s*5000/]
  },
  "vars-reassignment": {
    title: "Power Awakening: Reassignment",
    headerPrefix: "GEAR_FIFTH",
    missionPrefix: "GEAR_BOOST",
    intro: "# Shonen Power Spike: Reassignment\n\nIn the middle of a desperate boss battle against an Upper Moon demon or Yonko pirate, heroes tap into their latent power. Overwrite your `power_level` to ascend to the next gear!",
    technical: "Reassigning a variable updates its stored value, replacing the previous data in memory.",
    example: "power_level = 9000\npower_level = 100000\nprint(power_level)",
    task: "### YOUR MISSION\n\nInitialize `power_level` as `1000`. Then reassign `power_level` to `9001`. Print it.",
    baseCode: "power_level = 1000\n# TODO: Upgrade power_level to 9001 and print\n",
    hints: ["power_level = 9001", "print(power_level)"],
    solution: "power_level = 1000\npower_level = 9001\nprint(power_level)",
    solutionRegex: [/power_level\s*=\s*9001/, /print\s*\(\s*power_level\s*\)/]
  },
  "vars-placeholder": {
    title: "Sword Katas: Variable Interpolation",
    headerPrefix: "SWORD_FORMS",
    missionPrefix: "KATA_SLOT",
    intro: "# Sword Stances: Variable Substitution\n\nDisplay hero techniques by placing your technique name variable into output statements.",
    technical: "Variables can be passed into functions or combined with strings to create dynamic dialogue.",
    example: "kata = \"Hinokami Kagura\"\nprint(kata)",
    task: "### YOUR MISSION\n\nCreate a variable `active_technique` with the value `\"Hinokami Kagura\"` and print it.",
    baseCode: "# TODO: Define active_technique and print\n",
    hints: ["active_technique = \"Hinokami Kagura\"", "print(active_technique)"],
    solution: "active_technique = \"Hinokami Kagura\"\nprint(active_technique)",
    solutionRegex: [/active_technique\s*=\s*['"]Hinokami Kagura['"]/, /print\s*\(\s*active_technique\s*\)/]
  },
  "vars-multi": {
    title: "Straw Hat Trio: Multiple Assignment",
    headerPrefix: "MONSTER_TRIO",
    missionPrefix: "TRIPLE_HERO",
    intro: "# Monster Trio: Multiple Assignment\n\nLuffy, Zoro, and Sanji often deploy simultaneously in battle. Initialize all three heroes on a single line of Python code.",
    technical: "Python supports tuple unpacking for multiple assignment: `a, b, c = 1, 2, 3`.",
    example: "luffy, zoro, sanji = \"Captain\", \"Swordsman\", \"Cook\"\nprint(luffy, zoro, sanji)",
    task: "### YOUR MISSION\n\nAssign `luffy, zoro, sanji` to the strings `\"Captain\"`, `\"Swordsman\"`, `\"Cook\"` on one line and print them.",
    baseCode: "# TODO: Multi-assign hero roles and print\n",
    hints: ["luffy, zoro, sanji = \"Captain\", \"Swordsman\", \"Cook\"", "print(luffy, zoro, sanji)"],
    solution: "luffy, zoro, sanji = \"Captain\", \"Swordsman\", \"Cook\"\nprint(luffy, zoro, sanji)",
    solutionRegex: [/luffy\s*,\s*zoro\s*,\s*sanji\s*=\s*['"]Captain['"]\s*,\s*['"]Swordsman['"]\s*,\s*['"]Cook['"]/, /print\s*\(\s*luffy\s*,\s*zoro\s*,\s*sanji\s*\)/]
  },
  "data-strings": {
    title: "Hero Quirk: Strings",
    headerPrefix: "QUIRK_CARD",
    missionPrefix: "HERO_NAME",
    intro: "# Hero Quirk Registration: Strings\n\nEvery student entering U.A. High School registers their Hero Name and Quirk as text strings inside quotation marks.",
    technical: "Strings represent sequences of characters and can be enclosed in single or double quotes.",
    example: "hero_name = \"Deku\"\nquirk_name = \"One For All\"",
    task: "### YOUR MISSION\n\nCreate variable `hero_name` set to `\"Deku\"` and variable `quirk_name` set to `\"One For All\"`. Print both.",
    baseCode: "# TODO: Declare hero strings and print\n",
    hints: ["hero_name = \"Deku\"", "quirk_name = \"One For All\"", "print(hero_name, quirk_name)"],
    solution: "hero_name = \"Deku\"\nquirk_name = \"One For All\"\nprint(hero_name, quirk_name)",
    solutionRegex: [/hero_name\s*=\s*['"]Deku['"]/, /quirk_name\s*=\s*['"]One For All['"]/]
  },
  "data-booleans": {
    title: "Battle Ready: Booleans",
    headerPrefix: "ARENA_SENSOR",
    missionPrefix: "COMBAT_READY",
    intro: "# Combat Readiness: Booleans\n\nIs your Nichirin blade unsheathed? Has the hero license exam begun? Booleans represent binary truth states: `True` or `False`.",
    technical: "Python booleans are capitalized `True` and `False`.",
    example: "blade_drawn = True\nis_exhausted = False",
    task: "### YOUR MISSION\n\nSet `blade_drawn` to `True` and `is_exhausted` to `False`. Print both.",
    baseCode: "# TODO: Assign boolean battle flags\n",
    hints: ["blade_drawn = True", "is_exhausted = False", "print(blade_drawn, is_exhausted)"],
    solution: "blade_drawn = True\nis_exhausted = False\nprint(blade_drawn, is_exhausted)",
    solutionRegex: [/blade_drawn\s*=\s*True/, /is_exhausted\s*=\s*False/]
  },
  "intro-math": {
    title: "Bounty Calculation: Basic Math",
    headerPrefix: "MARINE_BOUNTY",
    missionPrefix: "BERRIES_TALLY",
    intro: "# Grand Line Bounties: Basic Math\n\nAfter toppling a warlord, the World Government tallies the new bounty posters! Calculate total reward berries using Python arithmetic.",
    technical: "Python uses `+`, `-`, `*`, and `/` for standard math operations.",
    example: "base_bounty = 300000000\ncrew_bonus = 50000000\ntotal = base_bounty + crew_bonus\nprint(total)",
    task: "### YOUR MISSION\n\nCalculate `total_bounty` as `300000000 + 50000000` and print the result.",
    baseCode: "# TODO: Calculate total bounty and print\n",
    hints: ["total_bounty = 300000000 + 50000000", "print(total_bounty)"],
    solution: "total_bounty = 300000000 + 50000000\nprint(total_bounty)",
    solutionRegex: [/total_bounty\s*=\s*300000000\s*\+\s*50000000/, /print\s*\(\s*total_bounty\s*\)/]
  },
  "math-complex": {
    title: "Stamina Formula: Compound Math",
    headerPrefix: "TRAINING_CAMP",
    missionPrefix: "STAMINA_RECOVERY",
    intro: "# Hashira Training: Compound Arithmetic\n\nCalculate Tanjiro's recovery rate after performing waterfall cutting training with multiple multipliers and offsets.",
    technical: "Compound expressions follow standard operator precedence: parentheses first, then multiplication/division, then addition/subtraction.",
    example: "energy = (100 - 20) * 1.5\nprint(energy)",
    task: "### YOUR MISSION\n\nCalculate `final_stamina` using formula: `(base_stamina - fatigue) * multiplier`. Base stamina is `120`, fatigue is `20`, and multiplier is `1.5`. Print `final_stamina`.",
    baseCode: "base_stamina = 120\nfatigue = 20\nmultiplier = 1.5\n# TODO: Calculate final_stamina and print\n",
    hints: ["final_stamina = (base_stamina - fatigue) * multiplier", "print(final_stamina)"],
    solution: "base_stamina = 120\nfatigue = 20\nmultiplier = 1.5\nfinal_stamina = (base_stamina - fatigue) * multiplier\nprint(final_stamina)",
    solutionRegex: [/final_stamina\s*=\s*\(\s*base_stamina\s*-\s*fatigue\s*\)\s*\*\s*multiplier/, /print\s*\(\s*final_stamina\s*\)/]
  },
  "intro-lists": {
    title: "Pirate Crew: Lists",
    headerPrefix: "STRAW_HAT_CREW",
    missionPrefix: "ROSTER_INIT",
    intro: "# Pirate Crew Roster: Lists\n\nEvery pirate captain sails with a trusty crew! Keep your shipmates organized inside a Python list.",
    technical: "Lists are ordered, mutable sequences defined inside square brackets `[...]`.",
    example: "crew = [\"Luffy\", \"Zoro\", \"Nami\"]\nprint(crew)",
    task: "### YOUR MISSION\n\nInitialize a list named `pirate_crew` with `\"Luffy\"`, `\"Zoro\"`, and `\"Nami\"`. Print `pirate_crew`.",
    baseCode: "# TODO: Initialize pirate_crew list and print\n",
    hints: ["pirate_crew = [\"Luffy\", \"Zoro\", \"Nami\"]", "print(pirate_crew)"],
    solution: "pirate_crew = [\"Luffy\", \"Zoro\", \"Nami\"]\nprint(pirate_crew)",
    solutionRegex: [/pirate_crew\s*=\s*\[\s*['"]Luffy['"]\s*,\s*['"]Zoro['"]\s*,\s*['"]Nami['"]\s*\]/, /print\s*\(\s*pirate_crew\s*\)/]
  },
  "list-indexing": {
    title: "Breathing Forms: List Indexing",
    headerPrefix: "WATER_BREATHING",
    missionPrefix: "KATA_SELECT",
    intro: "# Sword Technique Catalog: List Indexing\n\nWater Breathing has multiple numbered forms! Remember: Python lists use zero-based indexing (`0` is the first form, `2` is the third form).",
    technical: "Index `0` accesses the initial item; index `2` retrieves the 3rd item.",
    example: "first_form = water_forms[0]\nthird_form = water_forms[2]",
    task: "### YOUR MISSION\n\n1. Retrieve index `0` from `water_forms` into `first_form`.\n2. Retrieve index `2` from `water_forms` into `third_form`.\n3. Print both variables.",
    baseCode: "water_forms = [\"Surface Slash\", \"Water Wheel\", \"Flowing Dance\"]\n# TODO: Extract indices 0 and 2 and print\n",
    hints: ["first_form = water_forms[0]", "third_form = water_forms[2]", "print(first_form)", "print(third_form)"],
    solution: "water_forms = [\"Surface Slash\", \"Water Wheel\", \"Flowing Dance\"]\nfirst_form = water_forms[0]\nthird_form = water_forms[2]\nprint(first_form)\nprint(third_form)",
    solutionRegex: [/first_form\s*=\s*water_forms\s*\[\s*0\s*\]/, /third_form\s*=\s*water_forms\s*\[\s*2\s*\]/]
  },
  "list-append": {
    title: "Recruiting Nakama: .append()",
    headerPrefix: "CREW_RECRUITMENT",
    missionPrefix: "NAKAMA_JOIN",
    intro: "# Welcoming New Nakama: .append()\n\nAfter liberating an island from an evil warlord, a skilled doctor wants to join your voyage! Use `.append()` to add them to your crew.",
    technical: "The `.append()` method mutates lists in-place by adding a new item to the very end.",
    example: "crew.append(\"Chopper\")\nprint(crew)",
    task: "### YOUR MISSION\n\n1. Append `\"Chopper\"` to `pirate_crew`.\n2. Print the updated `pirate_crew` list.",
    baseCode: "pirate_crew = [\"Luffy\", \"Zoro\", \"Nami\"]\n# TODO: Append Chopper and print\n",
    hints: ["pirate_crew.append(\"Chopper\")", "print(pirate_crew)"],
    solution: "pirate_crew = [\"Luffy\", \"Zoro\", \"Nami\"]\npirate_crew.append(\"Chopper\")\nprint(pirate_crew)",
    solutionRegex: [/pirate_crew\.\s*append\s*\(\s*['"]Chopper['"]\s*\)/, /print\s*\(\s*pirate_crew\s*\)/]
  },
  "list-pop": {
    title: "Temporary Detachment: .pop()",
    headerPrefix: "SQUAD_TRANSFER",
    missionPrefix: "DISPATCH_HERO",
    intro: "# Deploying Hero Reinforcements: .pop()\n\nAn emergency distress beacon flares up across the city! Detach the last registered hero from your patrol roster and dispatch them to the scene.",
    technical: "Calling `.pop()` removes and returns the last element of a list.",
    example: "dispatched = hero_squad.pop()\nprint(dispatched)",
    task: "### YOUR MISSION\n\n1. Pop the last hero from `hero_squad` into a variable named `dispatched_hero`.\n2. Print `dispatched_hero`.",
    baseCode: "hero_squad = [\"Deku\", \"Bakugo\", \"Todoroki\"]\n# TODO: Pop the last hero and print\n",
    hints: ["dispatched_hero = hero_squad.pop()", "print(dispatched_hero)"],
    solution: "hero_squad = [\"Deku\", \"Bakugo\", \"Todoroki\"]\ndispatched_hero = hero_squad.pop()\nprint(dispatched_hero)",
    solutionRegex: [/dispatched_hero\s*=\s*hero_squad\.\s*pop\s*\(\s*\)/, /print\s*\(\s*dispatched_hero\s*\)/]
  },
  "intro-tuples": {
    title: "Bounty Coordinates: Tuples",
    headerPrefix: "LAUGH_TALE_PONEGLYPH",
    missionPrefix: "ETERNAL_LOG",
    intro: "# Road Poneglyph Coordinates: Tuples\n\nThe coordinates leading to Laugh Tale are carved into indestructible ancient stone blocks! Because they can never be altered or corrupted, store them inside an immutable tuple.",
    technical: "Tuples use parentheses `()` and cannot be mutated or changed once defined.",
    example: "laugh_tale_coords = (\"Grand Line\", 420)\nprint(laugh_tale_coords)",
    task: "### YOUR MISSION\n\n1. Initialize a tuple named `laugh_tale_coords` containing `\"Grand Line\"` and the number `420`.\n2. Print `laugh_tale_coords`.",
    baseCode: "# TODO: Declare coordinate tuple and print\n",
    hints: ["laugh_tale_coords = (\"Grand Line\", 420)", "print(laugh_tale_coords)"],
    solution: "laugh_tale_coords = (\"Grand Line\", 420)\nprint(laugh_tale_coords)",
    solutionRegex: [/laugh_tale_coords\s*=\s*\(\s*['"]Grand Line['"]\s*,\s*420\s*\)/, /print\s*\(\s*laugh_tale_coords\s*\)/]
  },
  "intro-tuples-immutability": {
    title: "Guild Gear vs Ancient Katana: Immutability",
    headerPrefix: "INVENTORY_COMPARE",
    missionPrefix: "MUTABLE_VS_IMMUTABLE",
    intro: "# Gear Inventory vs Sacred Sword: Immutability\n\nA demon slayer can restock consumable medicine pills at any village, but their forged Nichirin sword alloy numbers are permanent!",
    technical: "Lists are mutable and can be modified in place (`item[0] = new_val`), while tuples are read-only and immutable.",
    example: "bag = [\"Medicine\"]\nbag[0] = \"Healing Ointment\"\nsword_stats = (100, 95)",
    task: "### YOUR MISSION\n\n1. Create a list `consumables` with `[\"Medicine\"]`.\n2. Create a tuple `sword_stats` with numbers `(100, 95)`.\n3. Change `consumables[0]` to `\"Healing Ointment\"`.\n4. Print `consumables` and `sword_stats`.",
    baseCode: "# TODO: Demonstrate list mutability and tuple immutability\n",
    hints: ["consumables = [\"Medicine\"]", "sword_stats = (100, 95)", "consumables[0] = \"Healing Ointment\"", "print(consumables)", "print(sword_stats)"],
    solution: "consumables = [\"Medicine\"]\nsword_stats = (100, 95)\nconsumables[0] = \"Healing Ointment\"\nprint(consumables)\nprint(sword_stats)",
    solutionRegex: [/consumables\s*\[\s*0\s*\]\s*=\s*['"]Healing Ointment['"]/, /sword_stats\s*=\s*\(\s*100\s*,\s*95\s*\)/]
  },
  "list-slicing": {
    title: "Vanguard Strike: List Slicing",
    headerPrefix: "RAID_PARTY",
    missionPrefix: "VANGUARD_DEPLOY",
    intro: "# Onigashima Infiltration: List Slicing\n\nDuring a massive raid on a demon fortress, select the frontline vanguard squad (indices 1 through 4 exclusive) from the grand hero alliance roster.",
    technical: "Slice syntax `list[start:end]` extracts elements from index `start` up to but not including index `end`.",
    example: "vanguard = raid_members[1:4]\nprint(vanguard)",
    task: "### YOUR MISSION\n\n1. Slice indices `1:4` from `raid_members`.\n2. Store into `vanguard_squad`.\n3. Print `vanguard_squad`.",
    baseCode: "raid_members = [\"Luffy\", \"Zoro\", \"Law\", \"Kid\", \"Killer\", \"Yamato\"]\n# TODO: Slice indices 1:4 and print\n",
    hints: ["vanguard_squad = raid_members[1:4]", "print(vanguard_squad)"],
    solution: "raid_members = [\"Luffy\", \"Zoro\", \"Law\", \"Kid\", \"Killer\", \"Yamato\"]\nvanguard_squad = raid_members[1:4]\nprint(vanguard_squad)",
    solutionRegex: [/vanguard_squad\s*=\s*raid_members\s*\[\s*1\s*:\s*4\s*\]/, /print\s*\(\s*vanguard_squad\s*\)/]
  },
  "list-filtering": {
    title: "Bounty Filter: List Comprehensions",
    headerPrefix: "BOUNTY_POSTERS",
    missionPrefix: "HIGH_BOUNTY_SCAN",
    intro: "# High Bounty Scan: List Comprehensions\n\nFilter all super-rookie pirate bounties greater than 100 million berries to identify dangerous threats entering the New World!",
    technical: "List comprehensions construct filtered lists succinctly: `[item for item in list if condition]`.",
    example: "super_rookies = [b for b in bounties if b > 100]\nprint(super_rookies)",
    task: "### YOUR MISSION\n\n1. Use a list comprehension to filter all bounty values **greater than 100** from `bounty_millions`.\n2. Store in `super_rookies`.\n3. Print `super_rookies`.",
    baseCode: "bounty_millions = [30, 120, 50, 320, 80, 200]\n# TODO: Filter bounties > 100\n",
    hints: ["super_rookies = [b for b in bounty_millions if b > 100]", "print(super_rookies)"],
    solution: "bounty_millions = [30, 120, 50, 320, 80, 200]\nsuper_rookies = [b for b in bounty_millions if b > 100]\nprint(super_rookies)",
    solutionRegex: [/super_rookies\s*=\s*\[\s*b\s+for\s+b\s+in\s+bounty_millions\s+if\s+b\s*>\s*100\s*\]/, /print\s*\(\s*super_rookies\s*\)/]
  },
  "list-comprehension-range": {
    title: "Kata Drills: Range Comprehension",
    headerPrefix: "SWORD_DOJO",
    missionPrefix: "EVEN_FORM_DRILL",
    intro: "# Dojo Training: Range Comprehension\n\nUrokodaki orders Tanjiro to practice all even-numbered sword form repetitions from 2 to 10.",
    technical: "Combine `range()` and list comprehensions to generate structured numeric sequences.",
    example: "kata_reps = [x for x in range(2, 11) if x % 2 == 0]\nprint(kata_reps)",
    task: "### YOUR MISSION\n\nGenerate all even numbers between 2 and 10 (inclusive) using a list comprehension into `kata_drills` and print.",
    baseCode: "# TODO: Generate even kata drill counts\n",
    hints: ["kata_drills = [x for x in range(2, 11) if x % 2 == 0]", "print(kata_drills)"],
    solution: "kata_drills = [x for x in range(2, 11) if x % 2 == 0]\nprint(kata_drills)",
    solutionRegex: [/kata_drills\s*=\s*\[\s*x\s+for\s+x\s+in\s+range\s*\(\s*2\s*,\s*11\s*\)\s+if\s+x\s*%\s*2\s*==\s*0\s*\]/, /print\s*\(\s*kata_drills\s*\)/]
  },
  "intro-input": {
    title: "Calling Techniques: input()",
    headerPrefix: "SPECIAL_MOVE_INPUT",
    missionPrefix: "SHOUT_TECHNIQUE",
    intro: "# Announcing Your Ultimate Move: input()\n\nIn true shonen fashion, shouting your technique name gives it maximum impact! Prompt the trainee to speak their finishing blow into the console.",
    technical: "The `input()` function pauses program execution and captures user text from the keyboard as a string.",
    example: "technique = input(\"Name your ultimate move: \")\nprint(technique)",
    task: "### YOUR MISSION\n\nPrompt with `\"Name your move: \"` using `input()`, store in `move_name`, and `print(move_name)`.",
    baseCode: "# TODO: Prompt move name and print\n",
    hints: ["move_name = input(\"Name your move: \")", "print(move_name)"],
    solution: "move_name = input(\"Name your move: \")\nprint(move_name)",
    solutionRegex: [/move_name\s*=\s*input\s*\(\s*['"]Name your move:\s*['"]\s*\)/, /print\s*\(\s*move_name\s*\)/]
  },
  "print-formatting": {
    title: "Hero Dossier: Print Formatting",
    headerPrefix: "UA_STUDENT_CARD",
    missionPrefix: "HERO_CARD_FORMAT",
    intro: "# Hero License Card: Print Formatting\n\nFormat hero licenses with custom separators and clean layout tags using `sep` and `end` arguments.",
    technical: "The `print()` function accepts `sep` to define separators between multiple items and `end` to define closing characters.",
    example: "print(\"Deku\", \"Class 1-A\", \"Rank 1\", sep=\" | \")",
    task: "### YOUR MISSION\n\nPrint `\"Deku\"`, `\"Class 1-A\"`, and `\"Rank 1\"` separated by `\" | \"` using `sep=\" | \"`.",
    baseCode: "# TODO: Format print with custom separator\n",
    hints: ["print(\"Deku\", \"Class 1-A\", \"Rank 1\", sep=\" | \")"],
    solution: "print(\"Deku\", \"Class 1-A\", \"Rank 1\", sep=\" | \")",
    solutionRegex: [/print\s*\(\s*['"]Deku['"]\s*,\s*['"]Class 1-A['"]\s*,\s*['"]Rank 1['"]\s*,\s*sep\s*=\s*['"]\s*\|\s*['"]\s*\)/]
  },
  "input-fstrings-fun": {
    title: "Finishing Move: f-Strings",
    headerPrefix: "FINISHER_CALL",
    missionPrefix: "FSTRING_STRIKE",
    intro: "# Dynamic Battle Shouts: f-Strings\n\nInject your character's name, quirk, and percentage power directly into epic dialogue using formatted f-strings!",
    technical: "Prefix string literals with `f\"...\"` and embed variables or expressions directly inside curly braces `{var}`.",
    example: "hero = \"All Might\"\npower = 100\nprint(f\"{hero} unleashes Detroit Smash at {power}%!\")",
    task: "### YOUR MISSION\n\nGiven `hero = \"All Might\"` and `power = 100`, print `f\"{hero} unleashes Detroit Smash at {power}%!\"`.",
    baseCode: "hero = \"All Might\"\npower = 100\n# TODO: Print dynamic battle shout using f-string\n",
    hints: ["print(f\"{hero} unleashes Detroit Smash at {power}%!\")"],
    solution: "hero = \"All Might\"\npower = 100\nprint(f\"{hero} unleashes Detroit Smash at {power}%!\")",
    solutionRegex: [/print\s*\(\s*f['"].*\{hero\}.*Detroit Smash.*\{power\}%.*['"]\s*\)/]
  },
  "control-indentation": {
    title: "Sword Stance: Code Indentation",
    headerPrefix: "DOJO_DISCIPLINE",
    missionPrefix: "STANCE_INDENT",
    intro: "# Blade Precision: Code Indentation\n\nIn swordcraft and Python alike, form and structure are everything. Python uses 4-space indentation to determine which commands belong inside a block.",
    technical: "Code lines indented under a colon `:` belong to that statement's execution block.",
    example: "if True:\n    print(\"Blade drawn\")",
    task: "### YOUR MISSION\n\nFix the indentation so that `print(\"Blade drawn\")` is indented by 4 spaces under `if True:`.",
    baseCode: "if True:\nprint(\"Blade drawn\")\n",
    hints: ["Add 4 spaces before print(\"Blade drawn\")"],
    solution: "if True:\n    print(\"Blade drawn\")",
    solutionRegex: [/if\s+True\s*:\s*\n\s{4}print\s*\(\s*['"]Blade drawn['"]\s*\)/]
  },
  "control-if": {
    title: "Boss Encounter: Simple If",
    headerPrefix: "DEMON_DETECTOR",
    missionPrefix: "UPPER_MOON_FLAG",
    intro: "# Upper Moon Encounter: Simple If\n\nTanjiro's sharp sense of smell detects a demon scent nearby! If the scent flag is active, draw your sword immediately.",
    technical: "The `if` condition evaluates a boolean expression and executes its indented block only if True.",
    example: "if demon_spotted:\n    print(\"DRAW NICHIRIN BLADE\")",
    task: "### YOUR MISSION\n\nIf `demon_spotted` is `True`, print `\"DRAW NICHIRIN BLADE\"`.",
    baseCode: "demon_spotted = True\n# TODO: Check demon_spotted condition\n",
    hints: ["if demon_spotted:\n    print(\"DRAW NICHIRIN BLADE\")"],
    solution: "demon_spotted = True\nif demon_spotted:\n    print(\"DRAW NICHIRIN BLADE\")",
    solutionRegex: [/if\s+demon_spotted\s*:/, /print\s*\(\s*['"]DRAW NICHIRIN BLADE['"]\s*\)/]
  },
  "control-else": {
    title: "Stamina Gate: If/Else",
    headerPrefix: "STAMINA_METER",
    missionPrefix: "STAMINA_BRANCH",
    intro: "# Stamina Check: If/Else\n\nBefore executing the Eleventh Form of Water Breathing, verify whether Giyu has sufficient stamina remaining.",
    technical: "The `else` branch executes when the preceding `if` condition evaluates to False.",
    example: "if stamina >= 50:\n    print(\"UNLEASH FORM\")\nelse:\n    print(\"RECOVER SPIRIT\")",
    task: "### YOUR MISSION\n\n1. If `stamina >= 50`, print **`\"UNLEASH FORM\"`**.\n2. Else, print **`\"RECOVER SPIRIT\"`**.",
    baseCode: "stamina = 75\n# TODO: Branch on stamina condition\n",
    hints: ["if stamina >= 50:\n    print(\"UNLEASH FORM\")\nelse:\n    print(\"RECOVER SPIRIT\")"],
    solution: "stamina = 75\nif stamina >= 50:\n    print(\"UNLEASH FORM\")\nelse:\n    print(\"RECOVER SPIRIT\")",
    solutionRegex: [/if\s+stamina\s*>=\s*50\s*:/, /else\s*:/, /print\s*\(\s*['"]UNLEASH FORM['"]\s*\)/, /print\s*\(\s*['"]RECOVER SPIRIT['"]\s*\)/]
  },
  "control-elif": {
    title: "Corps Ranks: Elif Promotion",
    headerPrefix: "HASHIRA_EVAL",
    missionPrefix: "RANK_PROMOTION",
    intro: "# Slayer Corps Promotion: Elif Branching\n\nClassify a demon slayer trainee based on their confirmed demon eliminations: Hashira (50+ kills), Kanoe (10+ kills), or Mizunoto starter.",
    technical: "Use `elif` to check multiple sequential conditions without nesting multiple if-statements.",
    example: "if demons_slain >= 50:\n    print(\"HASHIRA RANK\")\nelif demons_slain >= 10:\n    print(\"KANOE RANK\")\nelse:\n    print(\"MIZUNOTO RANK\")",
    task: "### YOUR MISSION\n\n1. If `demons_slain >= 50`, print **`\"HASHIRA RANK\"`**.\n2. Elif `demons_slain >= 10`, print **`\"KANOE RANK\"`**.\n3. Else, print **`\"MIZUNOTO RANK\"`**.",
    baseCode: "demons_slain = 25\n# TODO: Evaluate rank using if / elif / else\n",
    hints: ["if demons_slain >= 50:", "elif demons_slain >= 10:", "else:"],
    solution: "demons_slain = 25\nif demons_slain >= 50:\n    print(\"HASHIRA RANK\")\nelif demons_slain >= 10:\n    print(\"KANOE RANK\")\nelse:\n    print(\"MIZUNOTO RANK\")",
    solutionRegex: [/if\s+demons_slain\s*>=\s*50\s*:/, /elif\s+demons_slain\s*>=\s*10\s*:/, /else\s*:/, /print\s*\(\s*['"]HASHIRA RANK['"]\s*\)/, /print\s*\(\s*['"]KANOE RANK['"]\s*\)/]
  },
  "control-meme-gen": {
    title: "Nakama Rescue: Branching",
    headerPrefix: "RESCUE_CHOICE",
    missionPrefix: "COMBAT_DECISION",
    intro: "# Enies Lobby Declaration: Branching Action\n\nWhen Spandam demands surrender, Luffy orders Sogeking to shoot down the World Government flag!",
    technical: "Evaluate boolean conditions to steer dialogue and action branching.",
    example: "if will_to_fight:\n    print(\"I WANT TO LIVE!\")\nelse:\n    print(\"Retreat\")",
    task: "### YOUR MISSION\n\nIf `will_to_fight`, print **`\"I WANT TO LIVE!\"`**; else print **`\"Retreat\"`**.",
    baseCode: "will_to_fight = True\n# TODO: If will_to_fight print shout\n",
    hints: ["if will_to_fight:\n    print(\"I WANT TO LIVE!\")\nelse:\n    print(\"Retreat\")"],
    solution: "will_to_fight = True\nif will_to_fight:\n    print(\"I WANT TO LIVE!\")\nelse:\n    print(\"Retreat\")",
    solutionRegex: [/if\s+will_to_fight\s*:/, /print\s*\(\s*['"]I WANT TO LIVE!['"]\s*\)/]
  },
  "control-nickname-gen": {
    title: "Hero License: Hero Title",
    headerPrefix: "PRO_HERO_BOARD",
    missionPrefix: "LICENSE_APPROVAL",
    intro: "# Hero License Approval: Dynamic Titles\n\nAssign a hero status title depending on whether the trainee passed the Provisional Hero License Exam.",
    technical: "Conditionally assign strings to variables before displaying them.",
    example: "if score >= 80:\n    status = \"Licensed Hero\"\nelse:\n    status = \"Trainee\"\nprint(status)",
    task: "### YOUR MISSION\n\nIf `exam_score >= 80`, set `status = \"Licensed Hero\"`; else set `status = \"Trainee\"`. Print `status`.",
    baseCode: "exam_score = 92\n# TODO: Assign status and print\n",
    hints: ["if exam_score >= 80:\n    status = \"Licensed Hero\"\nelse:\n    status = \"Trainee\"\nprint(status)"],
    solution: "exam_score = 92\nif exam_score >= 80:\n    status = \"Licensed Hero\"\nelse:\n    status = \"Trainee\"\nprint(status)",
    solutionRegex: [/if\s+exam_score\s*>=\s*80/, /status\s*=\s*['"]Licensed Hero['"]/, /print\s*\(\s*status\s*\)/]
  },
  "control-adventure": {
    title: "Grand Line Voyage: Nested Logic",
    headerPrefix: "LOG_POSE_ROUTE",
    missionPrefix: "SEA_DECISION",
    intro: "# Navigating the Calm Belt: Nested Logic\n\nNami reads the Log Pose! If the compass needle points forward and weather is calm, sail full speed toward Alabasta.",
    technical: "Nesting conditionals allows checking secondary prerequisites only after an initial condition passes.",
    example: "if weather == \"Clear\":\n    if wind_speed > 10:\n        print(\"SAIL TO ALABASTA\")",
    task: "### YOUR MISSION\n\nIf `weather == \"Clear\"`:\n    if `wind_speed > 10`:\n        print **`\"SAIL TO ALABASTA\"`**.",
    baseCode: "weather = \"Clear\"\nwind_speed = 15\n# TODO: Build nested conditionals\n",
    hints: ["if weather == \"Clear\":\n    if wind_speed > 10:\n        print(\"SAIL TO ALABASTA\")"],
    solution: "weather = \"Clear\"\nwind_speed = 15\nif weather == \"Clear\":\n    if wind_speed > 10:\n        print(\"SAIL TO ALABASTA\")",
    solutionRegex: [/if\s+weather\s*==\s*['"]Clear['"]\s*:\s*\n\s+if\s+wind_speed\s*>\s*10\s*:/, /print\s*\(\s*['"]SAIL TO ALABASTA['"]\s*\)/]
  },
  "control-loops": {
    title: "Sword Swings: For Loops",
    headerPrefix: "DOJO_PRACTICE",
    missionPrefix: "SWORD_DRILLS",
    intro: "# Ten Thousand Swings: For Loops\n\nUrokodaki commands 5 consecutive sword swing practice repetitions. Iterate cleanly through a `for` loop.",
    technical: "`for` loops iterate over sequences generated by `range()` or collections.",
    example: "for i in range(5):\n    print(\"Swing!\")",
    task: "### YOUR MISSION\n\nUse a `for` loop to print `\"Swing!\"` exactly `5` times using `range(5)`.",
    baseCode: "# TODO: Repeat sword swing 5 times\n",
    hints: ["for i in range(5):\n    print(\"Swing!\")"],
    solution: "for i in range(5):\n    print(\"Swing!\")",
    solutionRegex: [/for\s+\w+\s+in\s+range\s*\(\s*5\s*\)\s*:/, /print\s*\(\s*['"]Swing!['"]\s*\)/]
  },
  "loop-data-scan": {
    title: "Crew Bounties: List Iteration",
    headerPrefix: "MARINE_SCAN",
    missionPrefix: "POSTER_INSPECT",
    intro: "# Inspecting Wanted Posters: List Iteration\n\nInspect each pirate crew member in sequence and display their name.",
    technical: "Looping over a list binds each element in turn to the loop variable.",
    example: "for pirate in crew:\n    print(pirate)",
    task: "### YOUR MISSION\n\nLoop through `straw_hats` with a `for` loop and `print` each pirate name.",
    baseCode: "straw_hats = [\"Luffy\", \"Zoro\", \"Nami\", \"Usopp\", \"Sanji\"]\n# TODO: Loop through straw_hats and print\n",
    hints: ["for member in straw_hats:\n    print(member)"],
    solution: "straw_hats = [\"Luffy\", \"Zoro\", \"Nami\", \"Usopp\", \"Sanji\"]\nfor member in straw_hats:\n    print(member)",
    solutionRegex: [/for\s+\w+\s+in\s+straw_hats\s*:/, /print\s*\(\s*\w+\s*\)/]
  },
  "control-while": {
    title: "Boss Encounter: While Loop",
    headerPrefix: "MUZAN_BATTLE",
    missionPrefix: "BOSS_HP_DEPLETE",
    intro: "# Boss Battle: While Loop\n\nKeep attacking the demon boss until their health points drop to zero or below!",
    technical: "A `while` loop continues executing as long as its test condition remains True.",
    example: "while boss_hp > 0:\n    boss_hp -= 20\n    print(\"Strike!\")",
    task: "### YOUR MISSION\n\nWhile `boss_hp > 0`, subtract `20` from `boss_hp` and `print(\"Strike!\")`.",
    baseCode: "boss_hp = 60\n# TODO: While loop striking until boss_hp is 0\n",
    hints: ["while boss_hp > 0:\n    boss_hp -= 20\n    print(\"Strike!\")"],
    solution: "boss_hp = 60\nwhile boss_hp > 0:\n    boss_hp -= 20\n    print(\"Strike!\")",
    solutionRegex: [/while\s+boss_hp\s*>\s*0\s*:/, /boss_hp\s*-=\s*20/, /print\s*\(\s*['"]Strike!['"]\s*\)/]
  },
  "functions-intro": {
    title: "Sword Kata Definition: def",
    headerPrefix: "KATA_CODEX",
    missionPrefix: "DEF_TECHNIQUE",
    intro: "# Defining Special Moves: Functions\n\nPackage your ultimate fighting technique into a reusable Python function using the `def` keyword!",
    technical: "Functions allow bundling reusable logic blocks callable by name.",
    example: "def unleash_smash():\n    print(\"Detroit Smash!\")\n\nunleash_smash()",
    task: "### YOUR MISSION\n\n1. Define a function `unleash_smash()` that prints `\"Detroit Smash!\"`.\n2. Call `unleash_smash()`.",
    baseCode: "# TODO: Define unleash_smash and call it\n",
    hints: ["def unleash_smash():\n    print(\"Detroit Smash!\")\nunleash_smash()"],
    solution: "def unleash_smash():\n    print(\"Detroit Smash!\")\n\nunleash_smash()",
    solutionRegex: [/def\s+unleash_smash\s*\(\s*\)\s*:/, /print\s*\(\s*['"]Detroit Smash!['"]\s*\)/, /unleash_smash\s*\(\s*\)/]
  },
  "functions-multi-params": {
    title: "Tag Team Combo: Parameters",
    headerPrefix: "COMBO_STRIKE",
    missionPrefix: "DUAL_HERO",
    intro: "# Dual Hero Attack: Parameters\n\nCombine two heroes and their respective quirks into a devastating combo finisher!",
    technical: "Functions accept multiple input parameters separated by commas.",
    example: "def hero_combo(hero1, hero2):\n    print(f\"{hero1} and {hero2} attack!\")",
    task: "### YOUR MISSION\n\nDefine `hero_combo(hero1, hero2)` that prints `f\"{hero1} and {hero2} attack!\"`. Call it with `\"Luffy\"` and `\"Zoro\"`.",
    baseCode: "# TODO: Define hero_combo and call with Luffy and Zoro\n",
    hints: ["def hero_combo(hero1, hero2):\n    print(f\"{hero1} and {hero2} attack!\")\nhero_combo(\"Luffy\", \"Zoro\")"],
    solution: "def hero_combo(hero1, hero2):\n    print(f\"{hero1} and {hero2} attack!\")\n\nhero_combo(\"Luffy\", \"Zoro\")",
    solutionRegex: [/def\s+hero_combo\s*\(\s*hero1\s*,\s*hero2\s*\)\s*:/, /hero_combo\s*\(\s*['"]Luffy['"]\s*,\s*['"]Zoro['"]\s*\)/]
  },
  "functions-return": {
    title: "Power Scaling: return",
    headerPrefix: "POWER_CALCULATOR",
    missionPrefix: "RETURN_STRENGTH",
    intro: "# Power Level Calculation: return\n\nInstead of merely printing a value, compute and return a hero's scaled power rating back to the caller.",
    technical: "The `return` statement hands back a computed value from a function call.",
    example: "def scale_power(base, multiplier):\n    return base * multiplier",
    task: "### YOUR MISSION\n\n1. Define `calc_power(base, mult)` that returns `base * mult`.\n2. Call `calc_power(100, 5)` and print the returned value.",
    baseCode: "# TODO: Define calc_power and print result\n",
    hints: ["def calc_power(base, mult):\n    return base * mult\nprint(calc_power(100, 5))"],
    solution: "def calc_power(base, mult):\n    return base * mult\n\nprint(calc_power(100, 5))",
    solutionRegex: [/def\s+calc_power\s*\(\s*base\s*,\s*mult\s*\)\s*:/, /return\s+base\s*\*\s*mult/, /print\s*\(\s*calc_power\s*\(\s*100\s*,\s*5\s*\)\s*\)/]
  },
  "oop-intro": {
    title: "Hero Class Blueprint: Classes",
    headerPrefix: "HERO_BLUEPRINT",
    missionPrefix: "CLASS_DEF",
    intro: "# The Hero Blueprint: Classes\n\nEvery hero in the world shares common attributes (name, quirk, stamina). Package these traits into an object-oriented **Class**.",
    technical: "Classes provide reusable blueprints for creating custom objects in Python.",
    task: "### YOUR MISSION\n\nDefine an empty class named `Hero`. Use `pass` inside its block.",
    baseCode: "# TODO: Define Hero class\n",
    hints: ["class Hero:\n    pass"],
    solution: "class Hero:\n    pass",
    solutionRegex: [/class\s+Hero\s*:/, /pass/]
  },
  "oop-init": {
    title: "Hero Induction: __init__",
    headerPrefix: "UA_ENROLLMENT",
    missionPrefix: "INIT_HERO",
    intro: "# Hero Induction: Constructor\n\nWhen a new student enrolls in U.A. High, record their hero name with the `__init__` constructor method.",
    technical: "`__init__` is Python's constructor, initializing object instances upon creation.",
    task: "### YOUR MISSION\n\nInside `Hero`, define `__init__(self, name)` and assign `self.name = name`.",
    baseCode: "class Hero:\n    # TODO: Add __init__ constructor\n",
    hints: ["def __init__(self, name):\n    self.name = name"],
    solution: "class Hero:\n    def __init__(self, name):\n        self.name = name",
    solutionRegex: [/def\s+__init__\s*\(\s*self\s*,\s*name\s*\)\s*:/, /self\.name\s*=\s*name/]
  },
  "oop-methods": {
    title: "Hero Moves: Class Methods",
    headerPrefix: "QUIRK_ACTION",
    missionPrefix: "METHOD_EXEC",
    intro: "# Unleashing Capabilities: Methods\n\nA hero must be able to perform actions! Functions defined inside a class are called **Methods**.",
    task: "### YOUR MISSION\n\nAdd a method `unleash_quirk(self)` to `Hero` that prints `\"Quirk activated!\"`.",
    baseCode: "class Hero:\n    def __init__(self, name):\n        self.name = name\n    # TODO: Define unleash_quirk method\n",
    hints: ["def unleash_quirk(self):\n    print(\"Quirk activated!\")"],
    solution: "class Hero:\n    def __init__(self, name):\n        self.name = name\n    def unleash_quirk(self):\n        print(\"Quirk activated!\")",
    solutionRegex: [/def\s+unleash_quirk\s*\(\s*self\s*\)\s*:/, /print\s*\(\s*['"]Quirk activated!['"]\s*\)/]
  },
  "oop-state": {
    title: "Stamina Tracker: Object State",
    headerPrefix: "STAMINA_STATE",
    missionPrefix: "FATIGUE_TRACK",
    intro: "# Battle Fatigue: Object State\n\nEach hero instance independently tracks their current stamina meter as battle progresses.",
    task: "### YOUR MISSION\n\n1. In `Hero.__init__`, set `self.stamina = 100`.\n2. Add method `exhaust(self)` that sets `self.stamina = 0`.",
    baseCode: "class Hero:\n    def __init__(self, name):\n        self.name = name\n        # TODO: Add stamina = 100\n    # TODO: Add exhaust method\n",
    hints: ["self.stamina = 100", "def exhaust(self):\n    self.stamina = 0"],
    solution: "class Hero:\n    def __init__(self, name):\n        self.name = name\n        self.stamina = 100\n    def exhaust(self):\n        self.stamina = 0",
    solutionRegex: [/self\.stamina\s*=\s*100/, /def\s+exhaust\s*\(\s*self\s*\)\s*:/, /self\.stamina\s*=\s*0/]
  },
  "oop-interaction": {
    title: "Dueling Rivals: Object Interaction",
    headerPrefix: "SPARRING_MATCH",
    missionPrefix: "RIVAL_DUEL",
    intro: "# Arena Sparring: Object Interaction\n\nHeroes sharpen their skills by dueling their rivals! Methods can accept other object instances as arguments.",
    task: "### YOUR MISSION\n\nAdd method `spar(self, other)` to `Hero` that prints `f\"{self.name} spars with {other.name}!\"`.",
    baseCode: "class Hero:\n    def __init__(self, name):\n        self.name = name\n    # TODO: Add spar method\n",
    hints: ["def spar(self, other):\n    print(f\"{self.name} spars with {other.name}!\")"],
    solution: "class Hero:\n    def __init__(self, name):\n        self.name = name\n    def spar(self, other):\n        print(f\"{self.name} spars with {other.name}!\")",
    solutionRegex: [/def\s+spar\s*\(\s*self\s*,\s*other\s*\)\s*:/, /f['"].*\{self\.name\}.*spars with.*\{other\.name\}!['"]/]
  },
  "oop-inheritance": {
    title: "Pro Hero: Class Inheritance",
    headerPrefix: "PRO_RANK",
    missionPrefix: "SUBCLASS_PRO",
    intro: "# Pro Hero Graduation: Inheritance\n\nA `ProHero` inherits all base `Hero` traits while gaining access to emergency agency commands.",
    task: "### YOUR MISSION\n\nCreate a subclass `ProHero(Hero)` with method `deploy_agency(self)` that prints `\"Agency deployed!\"`.",
    baseCode: "class Hero:\n    def __init__(self, name):\n        self.name = name\n# TODO: Define ProHero inheriting from Hero\n",
    hints: ["class ProHero(Hero):\n    def deploy_agency(self):\n        print(\"Agency deployed!\")"],
    solution: "class Hero:\n    def __init__(self, name):\n        self.name = name\n\nclass ProHero(Hero):\n    def deploy_agency(self):\n        print(\"Agency deployed!\")",
    solutionRegex: [/class\s+ProHero\s*\(\s*Hero\s*\)\s*:/, /def\s+deploy_agency\s*\(\s*self\s*\)\s*:/, /print\s*\(\s*['"]Agency deployed!['"]\s*\)/]
  },
  "oop-str": {
    title: "Hero Billboard: __str__",
    headerPrefix: "BILLBOARD_CHART",
    missionPrefix: "STR_FORMAT",
    intro: "# Billboard Readout: __str__\n\nCustomize how a `Hero` prints in rankings by defining the `__str__` dunder method.",
    task: "### YOUR MISSION\n\nIn `Hero`, implement `__str__(self)` returning `f\"Hero: {self.name}\"`.",
    baseCode: "class Hero:\n    def __init__(self, name):\n        self.name = name\n    # TODO: Add __str__ method\n",
    hints: ["def __str__(self):\n    return f\"Hero: {self.name}\""],
    solution: "class Hero:\n    def __init__(self, name):\n        self.name = name\n    def __str__(self):\n        return f\"Hero: {self.name}\"",
    solutionRegex: [/def\s+__str__\s*\(\s*self\s*\)\s*:/, /return\s+f['"]Hero:\s*\{self\.name\}['"]/]
  },
  "oop-class-vars": {
    title: "League Creed: Class Variables",
    headerPrefix: "HERO_CREED",
    missionPrefix: "SHARED_MOTTO",
    intro: "# Shared Creed: Class Variables\n\nEvery hero has a unique identity, but all heroes uphold the shared guild motto.",
    task: "### YOUR MISSION\n\n1. Define class variable `guild = \"Heroes Guild\"` inside `Hero`.\n2. Print `Hero.guild`.",
    baseCode: "class Hero:\n    # TODO: Add class variable guild = \"Heroes Guild\"\n    pass\n# TODO: Print Hero.guild\n",
    hints: ["guild = \"Heroes Guild\"", "print(Hero.guild)"],
    solution: "class Hero:\n    guild = \"Heroes Guild\"\n\nprint(Hero.guild)",
    solutionRegex: [/guild\s*=\s*['"]Heroes Guild['"]/, /print\s*\(\s*Hero\.guild\s*\)/]
  }
};
