export const MARIO_THEME: any = {
  "intro-print": {
    title: "World 1-1: Hello Mario",
    headerPrefix: "WORLD_1_1",
    missionPrefix: "MARIO_BOOT",
    intro: "# Awakening in Mushroom Kingdom: print()\n\nWelcome to the Mushroom Kingdom! Bowser has locked away the castle stars. Jump out of the green pipe and announce your heroic arrival with Mario's signature shout.",
    technical: "In Python, the `print()` function displays whatever text or numbers you place inside its parentheses on the screen.",
    example: "print(\"It's-a me, Mario!\")",
    task: "### YOUR MISSION\n\nUse `print()` to display: `\"It's-a me, Mario!\"`",
    baseCode: "# TODO: Call out Mario's catchphrase\n",
    hints: ["Type print(\"It's-a me, Mario!\")","Make sure the text is inside double quotes"],
    solution: "print(\"It's-a me, Mario!\")",
    solutionRegex: [/print\s*\(\s*['"]It's-a me, Mario!['"]\s*\)/]
  },
  "naming-conventions": {
    title: "Coin Tally: Lowercase Names",
    headerPrefix: "MUSHROOM_BANK",
    missionPrefix: "COIN_INDEX",
    intro: "# Coin Counters: Lowercase Names\n\nToad's Mushroom Bank strictly requires lowercase variable names. When tracking collected gold coins, use lowercase letters and underscores.",
    technical: "Python variables must start with a lowercase letter or underscore, with words separated by underscores `_`.",
    example: "coin_count = 100\nprint(coin_count)",
    task: "### YOUR MISSION\n\nCreate a lowercase variable named `coin_count` and assign its value to `100` (enough for a 1-Up extra life!). Print it with `print()` to confirm. Everything must be lowercase!",
    baseCode: "# TODO: Store coin_count variable and print it\n",
    hints: ["Write coin_count = 100","On the next line, write print(coin_count)"],
    solution: "coin_count = 100\nprint(coin_count)",
    solutionRegex: [/coin_count\s*=\s*100/, /print\s*\(\s*coin_count\s*\)/]
  },
  "intro-comments": {
    title: "Castle Scouting: Comments",
    headerPrefix: "PIPE_TUNNEL",
    missionPrefix: "SCOUT_NOTE",
    intro: "# Underground Pipes: Comments\n\nWhen exploring mysterious subterranean warp pipes, Mario leaves scouting notes on brick walls to mark secret coin rooms.",
    technical: "Lines starting with `#` are comments. Python ignores them, making them perfect for developer and gameplay notes.",
    example: "# Stomp the Goomba\nprint(\"Jumping into pipe...\")",
    task: "### YOUR MISSION\n\nWrite a comment `# Stomp the Goomba` and then `print(\"Jumping into pipe...\")`",
    baseCode: "# TODO: Add scouting comment and jump into pipe\n",
    hints: ["Line 1: # Stomp the Goomba","Line 2: print(\"Jumping into pipe...\")"],
    solution: "# Stomp the Goomba\nprint(\"Jumping into pipe...\")",
    solutionRegex: [/#.*Stomp the Goomba/, /print\s*\(\s*['"]Jumping into pipe\.\.\.['"]\s*\)/]
  },
  "comments-inline": {
    title: "1-Up Counter: Inline Comments",
    headerPrefix: "LIFE_DISPLAY",
    missionPrefix: "LIFE_NOTE",
    intro: "# Extra Lives: Inline Comments\n\nDocument Mario's spare lives right beside your variable initialization without cluttering the screen.",
    technical: "Inline comments appear on the same line after executable code, separated by `#`.",
    example: "mario_lives = 3 # Extra life counter",
    task: "### YOUR MISSION\n\nInitialise `mario_lives` to `3`. On the same line, add an inline comment `# Extra life counter`.",
    baseCode: "# TODO: Initialize variable with inline comment\n",
    hints: ["Write mario_lives = 3 followed by # Extra life counter on the same line."],
    solution: "mario_lives = 3 # Extra life counter",
    solutionRegex: [/mario_lives\s*=\s*3/, /#.*Extra life counter/]
  },
  "intro-vars": {
    title: "Power-up Satchel: Variables",
    headerPrefix: "ITEM_BOX",
    missionPrefix: "POWER_SLOT",
    intro: "# Power-Up Satchel: Variables\n\n**What is a Variable?** Think of a **variable** as a **floating yellow ? Block**! You give the block a label (like `super_stars`), store power-ups inside, and hit it whenever Mario needs an invincible boost.",
    technical: "Variables store values that can be referenced and manipulated throughout a program.",
    example: "super_stars = 5\nfire_flowers = 10",
    task: "### YOUR MISSION\n\nCreate `super_stars` set to `5` and `fire_flowers` set to `10`.",
    baseCode: "# TODO: Record super stars and fire flowers\n",
    hints: ["super_stars = 5","fire_flowers = 10"],
    solution: "super_stars = 5\nfire_flowers = 10",
    solutionRegex: [/super_stars\s*=\s*5/, /fire_flowers\s*=\s*10/]
  },
  "vars-reassignment": {
    title: "Super Mushroom: Reassignment",
    headerPrefix: "GROWTH_SCALE",
    missionPrefix: "POWER_UPGRADE",
    intro: "# Mushroom Growth: Reassignment\n\nMario just grabbed a Super Mushroom! Update your `mario_scale` variable from `1.0` (Small Mario) to `2.0` (Super Mario) to grow double-sized.",
    technical: "When you assign a new value to an existing variable name, Python throws away the old value and replaces it with the new one. This is called **reassignment**.",
    example: "mario_scale = 1.0\nmario_scale = 2.0\nprint(mario_scale)",
    task: "### YOUR MISSION\n\nInitialise `mario_scale` as `1.0`. Then update `mario_scale` to `2.0`. Print it.",
    baseCode: "mario_scale = 1.0\n# TODO: Upgrade to 2.0 and print\n",
    hints: ["Assign mario_scale = 2.0 on the next line.","Print it with print(mario_scale)."],
    solution: "mario_scale = 1.0\nmario_scale = 2.0\nprint(mario_scale)",
    solutionRegex: [/mario_scale\s*=\s*1\.0/, /mario_scale\s*=\s*2\.0/, /print\s*\(\s*mario_scale\s*\)/]
  },
  "vars-placeholder": {
    title: "Castle Rescue: Empty Placeholders",
    headerPrefix: "CASTLE_RESCUE",
    missionPrefix: "RESCUE_RECEIVE",
    intro: "# Princess Chamber: Empty Placeholders\n\nBefore opening Bowser's dungeon keep, prepare an empty string buffer to hold the rescued character's name.",
    technical: "For strings, an \"empty\" value is represented by two quotes with nothing inside, such as `\"\"` or `''`.\n\n### Overwriting with Input:\nBy first initializing `mario_data = \"\"` as a placeholder, we allocate space in memory. Then, running `mario_data = input(\"...\")` overwrites that placeholder with whatever you enter, updating the empty string dynamically!",
    example: "mario_data = \"\"\nmario_data = input(\"Enter rescued character: \")\nprint(\"Mushroom Kingdom cheers: \" + mario_data)",
    task: "### YOUR MISSION\n\n1. Initialize `mario_data` as an empty string `\"\"` or `''`.\n2. Use `input(\"Enter rescued character: \")` to populate it.\n3. Print `\"Mushroom Kingdom cheers: \" + mario_data`.",
    baseCode: "# TODO: Prepare buffer and log rescued character\n",
    hints: ["Use mario_data = \"\" to prepare the buffer.","Use mario_data = input(\"Enter rescued character: \") to capture the character.","Print \"Mushroom Kingdom cheers: \" concatenated with mario_data."],
    solution: "mario_data = \"\"\nmario_data = input(\"Enter rescued character: \")\nprint(\"Mushroom Kingdom cheers: \" + mario_data)",
    solutionRegex: [/mario_data\s*=\s*['"]['"]/, /input/, /print/]
  },
  "vars-multi": {
    title: "Bonus Room: Multiple Assignment",
    headerPrefix: "BONUS_ROOM",
    missionPrefix: "MULTI_BONUS",
    intro: "# Hidden Coin Room: Multiple Assignment\n\nMario found a hidden cloud room loaded with coins and 1-Up mushrooms! Unpack both prize quantities on a single line.",
    technical: "Multiple assignment pairs comma-separated names with comma-separated values: `a, b = 1, 2`.",
    example: "gold_coins, green_mushrooms = 100, 3",
    task: "### YOUR MISSION\n\nAssign `gold_coins` set to `100` and `green_mushrooms` set to `3` in one line.",
    baseCode: "# TODO: Assign gold_coins and green_mushrooms in one line\n",
    hints: ["gold_coins, green_mushrooms = 100, 3"],
    solution: "gold_coins, green_mushrooms = 100, 3",
    solutionRegex: [/gold_coins\s*,\s*green_mushrooms\s*=\s*100\s*,\s*3/]
  },
  "data-strings": {
    title: "Active Power-up: Strings",
    headerPrefix: "POWER_GAUGE",
    missionPrefix: "ITEM_NAME",
    intro: "# Mushroom Kingdom Item: Strings\n\nStore the name of Mario's active power-up item in a string variable.",
    technical: "Strings represent text enclosed in single or double quotes.",
    example: "powerup = \"Super Mushroom\"\nprint(powerup)",
    task: "### YOUR MISSION\n\nCreate a variable `powerup` set to `\"Super Mushroom\"`. Print it.",
    baseCode: "# TODO: Set powerup and print\n",
    hints: ["powerup = \"Super Mushroom\"","print(powerup)"],
    solution: "powerup = \"Super Mushroom\"\nprint(powerup)",
    solutionRegex: [/powerup\s*=\s*['"]Super Mushroom['"]/, /print\s*\(\s*powerup\s*\)/]
  },
  "data-booleans": {
    title: "Game Flags: Booleans",
    headerPrefix: "STAGE_FLAGS",
    missionPrefix: "POWER_FLAGS",
    intro: "# Stage Condition: Booleans\n\nIn Super Mario, boolean flags check whether Mario has picked up a Fire Flower or whether his extra lives have hit Game Over.",
    technical: "Booleans can only be `True` or `False`. Always capitalize the first letter.",
    example: "has_fire_flower = True\nis_game_over = False",
    task: "### YOUR MISSION\n\nSet `has_fire_flower` to `True` and `is_game_over` to `False`.",
    baseCode: "# TODO: Set fire flower and game over flags\n",
    hints: ["has_fire_flower = True","is_game_over = False"],
    solution: "has_fire_flower = True\nis_game_over = False",
    solutionRegex: [/has_fire_flower\s*=\s*True/, /is_game_over\s*=\s*False/]
  },
  "intro-math": {
    title: "Coin Tally: Addition",
    headerPrefix: "COIN_VAULT",
    missionPrefix: "SUM_COINS",
    intro: "# Mushroom Kingdom Treasury: Addition\n\nTally coins collected from both World 1 and World 2 using Python addition.",
    technical: "The `+` operator adds numerical values together.",
    example: "total_coins = world_1_coins + world_2_coins\nprint(total_coins)",
    task: "### YOUR MISSION\n\nCreate `world_1_coins` as `50` and `world_2_coins` as `50`. Store the sum in `total_coins` and print it.",
    baseCode: "# TODO: Calculate total coins\n",
    hints: ["world_1_coins = 50","world_2_coins = 50","total_coins = world_1_coins + world_2_coins","print(total_coins)"],
    solution: "world_1_coins = 50\nworld_2_coins = 50\ntotal_coins = world_1_coins + world_2_coins\nprint(total_coins)",
    solutionRegex: [/total_coins\s*=\s*world_1_coins\s*\+\s*world_2_coins/, /print\s*\(\s*total_coins\s*\)/]
  },
  "math-complex": {
    title: "High Score: Complex Math",
    headerPrefix: "SCORE_CALCULATOR",
    missionPrefix: "FINAL_SCORE",
    intro: "# Flagpole Finish: Complex Math\n\nCalculate your final stage score factoring in base points, remaining timer deductions, and difficulty multiplier.",
    technical: "Operations inside parentheses `()` evaluate first before multiplication `*`.",
    example: "final_score = (base_score + time_penalty) * 0.8\nprint(final_score)",
    task: "### YOUR MISSION\n\n1. Set `base_score` as `80`.\n2. Set `time_penalty` as `-10`.\n3. Calculate `(base_score + time_penalty) * 0.8` and store in `final_score`.\n4. Print `final_score`.",
    baseCode: "# TODO: Compute final_score\n",
    hints: ["base_score = 80","time_penalty = -10","final_score = (base_score + time_penalty) * 0.8","print(final_score)"],
    solution: "base_score = 80\ntime_penalty = -10\nfinal_score = (base_score + time_penalty) * 0.8\nprint(final_score)",
    solutionRegex: [/final_score\s*=\s*\(\s*base_score\s*\+\s*time_penalty\s*\)\s*\*\s*0\.8/, /print\s*\(\s*final_score\s*\)/]
  },
  "intro-lists": {
    title: "Item Slots: Lists",
    headerPrefix: "RESERVE_BOX",
    missionPrefix: "POWER_ROSTER",
    intro: "# Reserve Item Box: Lists\n\nStore Mario's collected power-up reserves in a Python list.",
    technical: "Lists are ordered, mutable sequences surrounded by brackets `[...]`.",
    example: "powerups = [\"Super Mushroom\", \"Fire Flower\", \"Super Star\"]\nprint(powerups)",
    task: "### YOUR MISSION\n\nInitialise your `powerups` list with \"Super Mushroom\", \"Fire Flower\", and \"Super Star\". Print the powerups list.",
    baseCode: "# TODO: Initialize powerups list and print\n",
    hints: ["powerups = [\"Super Mushroom\", \"Fire Flower\", \"Super Star\"]","print(powerups)"],
    solution: "powerups = [\"Super Mushroom\", \"Fire Flower\", \"Super Star\"]\nprint(powerups)",
    solutionRegex: [/powerups\s*=\s*\[/, /print\s*\(\s*powerups\s*\)/]
  },
  "list-indexing": {
    title: "Powerup Selection: List Indexing",
    headerPrefix: "POWER_SLOTS",
    missionPrefix: "SLOT_CHOOSE",
    intro: "# Item Box Selector: List Indexing\n\nIn your reserve item box, slot 1 is accessed with index `0`, while slot 3 is at index `2`.",
    technical: "Index `0` accesses the first item; index `2` accesses the third item.",
    example: "slot_first = powerups[0]\nslot_third = powerups[2]",
    task: "### YOUR MISSION\n\n1. Retrieve the first item (index 0) in the `powerups` list and store in `slot_first`.\n2. Retrieve the third item (index 2) in the `powerups` list and store in `slot_third`.\n3. Print `slot_first` and `slot_third`.",
    baseCode: "powerups = [\"Super Mushroom\", \"Fire Flower\", \"Super Star\"]\n# TODO: Extract indices 0 and 2 and print\n",
    hints: ["slot_first = powerups[0]","slot_third = powerups[2]","print(slot_first)","print(slot_third)"],
    solution: "slot_first = powerups[0]\nslot_third = powerups[2]\nprint(slot_first)\nprint(slot_third)",
    solutionRegex: [/slot_first\s*=\s*powerups\s*\[\s*0\s*\]/, /slot_third\s*=\s*powerups\s*\[\s*2\s*\]/]
  },
  "list-append": {
    title: "Cape Feather: .append()",
    headerPrefix: "POWERUP_STASH",
    missionPrefix: "YOUR TASK",
    intro: "# Super Mario World: .append()\n\nMario found a flying Cape Feather! Use `.append()` to add it directly to your powerups list.",
    technical: "The `.append()` method mutates lists in-place, adding an element to the end.",
    example: "powerups.append(\"Cape Feather\")\nprint(powerups)",
    task: "### YOUR MISSION\n\n1. Append \"Cape Feather\" to the `powerups` list.\n2. Print the final `powerups` list to confirm.",
    baseCode: "powerups = [\"Super Mushroom\", \"Fire Flower\", \"Super Star\"]\n# TODO: Append value and print\n",
    hints: ["powerups.append(\"Cape Feather\")","print(powerups)"],
    solution: "powerups.append(\"Cape Feather\")\nprint(powerups)",
    solutionRegex: [/powerups\.\s*append\s*\(\s*['"]Cape Feather['"]\s*\)/, /print\s*\(\s*powerups\s*\)/]
  },
  "list-pop": {
    title: "Koopa Shell: .pop()",
    headerPrefix: "ENEMY_STOMP",
    missionPrefix: "YOUR TASK",
    intro: "# Stomping Castle Minions: .pop()\n\nMario jumps on the last enemy guarding the bridge! Use `.pop()` to remove and record the defeated enemy.",
    technical: "Calling `.pop()` removes and returns the last element from a list.",
    example: "stomped_foe = castle_enemies.pop()\nprint(stomped_foe)",
    task: "### YOUR MISSION\n\n1. Pop the last item from the `castle_enemies` list and store it inside a variable named `stomped_foe`.\n2. Print `stomped_foe` to output the defeated foe.",
    baseCode: "castle_enemies = [\"Goomba\", \"Koopa Troopa\", \"Bowser Jr.\"]\n# TODO: Pop last element and print\n",
    hints: ["stomped_foe = castle_enemies.pop()","print(stomped_foe)"],
    solution: "stomped_foe = castle_enemies.pop()\nprint(stomped_foe)",
    solutionRegex: [/stomped_foe\s*=\s*castle_enemies\.\s*pop\s*\(\s*\)/, /print\s*\(\s*stomped_foe\s*\)/]
  },
  "intro-tuples": {
    title: "Secret Warp Zone: Tuples",
    headerPrefix: "WARP_ZONE",
    missionPrefix: "YOUR TASK",
    intro: "# Warp Zone Destination: Tuples\n\nWarp pipe destinations are permanently embedded into the stage architecture. Tuples provide immutable collections.",
    technical: "Tuples use parentheses `()` and cannot be modified once created.",
    example: "warp_pipe = (\"World 1-1\", 1985)\nprint(warp_pipe)",
    task: "### YOUR MISSION\n\n1. Initialize a tuple named `warp_pipe` containing \"World 1-1\" and the number `1985`.\n2. Print the `warp_pipe` tuple.",
    baseCode: "# TODO: Initialize the coordinate tuple and print\n",
    hints: ["warp_pipe = (\"World 1-1\", 1985)","print(warp_pipe)"],
    solution: "warp_pipe = (\"World 1-1\", 1985)\nprint(warp_pipe)",
    solutionRegex: [/warp_pipe\s*=\s*\(\s*['"]World 1-1['"]\s*,\s*1985\s*\)/, /print\s*\(\s*warp_pipe\s*\)/]
  },
  "intro-tuples-immutability": {
    title: "Item Bag vs Flagpole: Immutability",
    headerPrefix: "FLAGPOLE_RECORDS",
    missionPrefix: "YOUR TASK",
    intro: "# Reserve Items vs Flagpole Heights: Immutability\n\nActive inventory items are mutable and change dynamically, but the flagpole height coordinates are unalterable!",
    technical: "Lists can be updated in-place (`list[0] = new_val`), while tuples are read-only and immutable.",
    example: "active_items = [\"Mushroom\"]\nactive_items[0] = \"Starman\"",
    task: "### YOUR MISSION\n\n1. Create a list named `active_items` containing the single string \"Mushroom\"\n2. Create a tuple named `flagpole_coords` containing the numbers `8` and `4`.\n3. Rewrite `active_items[0]` to be \"Starman\"\n4. Print both `active_items` and `flagpole_coords`.",
    baseCode: "# TODO: Demonstrate mutable list and immutable tuple\n",
    hints: ["active_items = [\"Mushroom\"]","flagpole_coords = (8, 4)","active_items[0] = \"Starman\"","print(active_items)","print(flagpole_coords)"],
    solution: "active_items = [\"Mushroom\"]\nflagpole_coords = (8, 4)\nactive_items[0] = \"Starman\"\nprint(active_items)\nprint(flagpole_coords)",
    solutionRegex: [/active_items\s*\[\s*0\s*\]\s*=\s*['"]Starman['"]/, /flagpole_coords\s*=\s*\(\s*8\s*,\s*4\s*\)/]
  },
  "list-slicing": {
    title: "World Map: List Slicing",
    headerPrefix: "WORLD_MAP_SLICE",
    missionPrefix: "YOUR TASK",
    intro: "# World Map Routes: List Slicing\n\nSlice through middle world sections on Mario's map to plot the fastest course through Bowser's keeps.",
    technical: "Slice syntax `list[start:end]` extracts elements from `start` up to but not including `end`.",
    example: "castle_sectors = world_map[1:4]\nprint(castle_sectors)",
    task: "### YOUR MISSION\n\n1. Slice index `1` to index `4` (exclusive) from the `world_map` list.\n2. Store this result in a new variable named `castle_sectors`.\n3. Print the resulting slice `castle_sectors`.",
    baseCode: "world_map = [\"Plains\", \"Underground\", \"Underwater\", \"Castle\", \"Sky\", \"Lava\"]\n# TODO: Slice indices 1:4 and print\n",
    hints: ["castle_sectors = world_map[1:4]","print(castle_sectors)"],
    solution: "castle_sectors = world_map[1:4]\nprint(castle_sectors)",
    solutionRegex: [/castle_sectors\s*=\s*world_map\s*\[\s*1\s*:\s*4\s*\]/, /print\s*\(\s*castle_sectors\s*\)/]
  },
  "list-filtering": {
    title: "Coin Stages: List Comprehensions",
    headerPrefix: "COIN_FILTER",
    missionPrefix: "YOUR TASK",
    intro: "# High-Reward Stages: List Comprehensions\n\nFilter all stages that contain more than 50 coins to speedrun maximum 1-Up extra lives!",
    technical: "List comprehensions construct filtered lists cleanly: `[x for x in list if condition]`.",
    example: "high_coin_stages = [c for c in stage_coins if c > 50]\nprint(high_coin_stages)",
    task: "### YOUR MISSION\n\n1. Use a list comprehension to filter all values **greater than 50** from `stage_coins`.\n2. Store the result in a variable named `high_coin_stages`.\n3. Print `high_coin_stages`.",
    baseCode: "stage_coins = [15, 65, 30, 92, 45, 88]\n# TODO: Comprehend and filter values > 50\n",
    hints: ["high_coin_stages = [c for c in stage_coins if c > 50]","print(high_coin_stages)"],
    solution: "high_coin_stages = [c for c in stage_coins if c > 50]\nprint(high_coin_stages)",
    solutionRegex: [/high_coin_stages\s*=\s*\[\s*c\s+for\s+c\s+in\s+stage_coins\s+if\s+c\s*>\s*50\s*\]/, /print\s*\(\s*high_coin_stages\s*\)/]
  },
  "list-comprehension-range": {
    title: "Warp Pipe Network: Even Comprehension",
    headerPrefix: "PIPE_NETWORK",
    missionPrefix: "YOUR TASK",
    intro: "# Warp Network: Even Pipe Filtering\n\nIsolate even-numbered warp pipes in the sewer network using modulo `% 2 == 0`.",
    technical: "Use modulo `x % 2 == 0` inside a list comprehension to filter even integers.",
    example: "even_numbered_pipes = [p for p in pipe_numbers if p % 2 == 0]\nprint(even_numbered_pipes)",
    task: "### YOUR MISSION\n\n1. Filter only the **even** numbers from the `pipe_numbers` list using a list comprehension.\n2. Store this filtered list in a new variable named `even_numbered_pipes`.\n3. Print `even_numbered_pipes`.",
    baseCode: "pipe_numbers = [101, 102, 103, 104, 105, 106, 107, 108]\n# TODO: Comprehend and filter even indices\n",
    hints: ["even_numbered_pipes = [p for p in pipe_numbers if p % 2 == 0]","print(even_numbered_pipes)"],
    solution: "even_numbered_pipes = [p for p in pipe_numbers if p % 2 == 0]\nprint(even_numbered_pipes)",
    solutionRegex: [/even_numbered_pipes\s*=\s*\[\s*p\s+for\s+p\s+in\s+pipe_numbers\s+if\s+p\s*%\s*2\s*==\s*0\s*\]/, /print\s*\(\s*even_numbered_pipes\s*\)/]
  },
  "intro-input": {
    title: "Warp Zone Gate: User Input",
    headerPrefix: "WARP_TERMINAL",
    missionPrefix: "YOUR TASK",
    intro: "# Secret Warp Pipe: User Input\n\nPrompt the player for the warp zone destination Mario should jump into!",
    technical: "`input()` captures keyboard input as text. Concatenate strings with `+`.",
    example: "kingdom_zone = input(\"Enter warp zone: \")\nprint(\"Warping to: \" + kingdom_zone)",
    task: "### YOUR MISSION\n\n1. Ask the player for the warp zone with the prompt: **\"Enter warp zone: \"** and store in `kingdom_zone`.\n2. Print **\"Warping to: \"** concatenated with `kingdom_zone`.",
    baseCode: "# TODO: Capture warp zone and print\n",
    hints: ["kingdom_zone = input(\"Enter warp zone: \")","print(\"Warping to: \" + kingdom_zone)"],
    solution: "kingdom_zone = input(\"Enter warp zone: \")\nprint(\"Warping to: \" + kingdom_zone)",
    solutionRegex: [/kingdom_zone\s*=\s*input\s*\(\s*['"]Enter warp zone:\s*['"]\s*\)/, /print\s*\(\s*['"]Warping to:\s*['"]\s*\+\s*kingdom_zone\s*\)/]
  },
  "input-mad-libs": {
    title: "Mushroom Kingdom Epic: Mad Libs Story",
    headerPrefix: "MARIO_STORY",
    missionPrefix: "HERO_TALE",
    intro: "# Bowser Castle Climax: Mad Libs Story\n\nAssemble an epic Mushroom Kingdom victory legend!",
    technical: "Collect user inputs and concatenate into a cohesive narrative.",
    example: "mario_story = hero + \" defeated \" + villain + \" using a \" + power + \"!\"\nprint(mario_story)",
    task: "### YOUR MISSION\n\n1. Ask for hero name with prompt: **\"Hero name: \"** and store in `hero`.\n2. Ask for villain with prompt: **\"Villain: \"** and store in `villain`.\n3. Ask for power-up with prompt: **\"Power-up: \"** and store in `power`.\n4. Combine into `mario_story` and print: `hero + \" defeated \" + villain + \" using a \" + power + \"!\"`.",
    baseCode: "# TODO: Compose Mario adventure story\n",
    hints: ["hero = input(\"Hero name: \")","villain = input(\"Villain: \")","power = input(\"Power-up: \")","mario_story = hero + \" defeated \" + villain + \" using a \" + power + \"!\"","print(mario_story)"],
    solution: "hero = input(\"Hero name: \")\nvillain = input(\"Villain: \")\npower = input(\"Power-up: \")\nmario_story = hero + \" defeated \" + villain + \" using a \" + power + \"!\"\nprint(mario_story)",
    solutionRegex: [/hero\s*=\s*input\s*\(\s*['"]Hero name:\s*['"]\s*\)/, /villain\s*=\s*input\s*\(\s*['"]Villain:\s*['"]\s*\)/, /power\s*=\s*input\s*\(\s*['"]Power-up:\s*['"]\s*\)/, /print\s*\(\s*mario_story\s*\)/]
  },
  "input-mad-libs-pro": {
    title: "Peach Rescue: Multi-Variable Logging",
    headerPrefix: "RESCUE_ARCHIVE",
    missionPrefix: "ROYAL_RECORD",
    intro: "# Royal Dispatch: Multi-Variable Logging\n\nRecord the official royal decree declaring Princess Peach safe in the Mushroom Kingdom archive!",
    technical: "Combine 5 separate prompt inputs into a structured royal dispatch message.",
    example: "quest_log = plumber + \" rushed \" + item + \" into \" + castle + \" at \" + world + \". Princess is \" + state + \"!\"\nprint(quest_log)",
    task: "### YOUR MISSION\n\n1. Ask for plumber with **\"Plumber: \"** in `plumber`.\n2. Ask for item with **\"Item: \"** in `item`.\n3. Ask for castle with **\"Castle: \"** in `castle`.\n4. Ask for world with **\"World: \"** in `world`.\n5. Ask for state with **\"State: \"** in `state`.\n6. Combine into `quest_log` and print: `plumber + \" rushed \" + item + \" into \" + castle + \" at \" + world + \". Princess is \" + state + \"!\"`.",
    baseCode: "# TODO: Log royal decree\n",
    hints: ["Ask all 5 inputs using input()","Combine them with + concatenation and print quest_log"],
    solution: "plumber = input(\"Plumber: \")\nitem = input(\"Item: \")\ncastle = input(\"Castle: \")\nworld = input(\"World: \")\nstate = input(\"State: \")\nquest_log = plumber + \" rushed \" + item + \" into \" + castle + \" at \" + world + \". Princess is \" + state + \"!\"\nprint(quest_log)",
    solutionRegex: [/plumber\s*=\s*input\s*\(\s*['"]Plumber:\s*['"]\s*\)/, /item\s*=\s*input\s*\(\s*['"]Item:\s*['"]\s*\)/, /castle\s*=\s*input\s*\(\s*['"]Castle:\s*['"]\s*\)/, /world\s*=\s*input\s*\(\s*['"]World:\s*['"]\s*\)/, /state\s*=\s*input\s*\(\s*['"]State:\s*['"]\s*\)/, /print\s*\(\s*quest_log\s*\)/]
  },
  "print-formatting": {
    title: "Hero Passport: F-Strings",
    headerPrefix: "HERO_PROFILE",
    missionPrefix: "F_STRING_TAG",
    intro: "# Mushroom Kingdom Passport: Clean F-Strings\n\nUse an f-string to display your hero alias and hero rank cleanly on your Mushroom Kingdom passport.",
    technical: "F-strings allow embedding variables inside string literals using `{variable}` syntax.",
    example: "print(f'Plumber: {alias} | Hero Rank: {level}')",
    task: "### YOUR MISSION\n\nYou have `alias = 'Mario'` and `level = 99`. Use an **f-string** to print: `Plumber: Mario | Hero Rank: 99`.",
    baseCode: "alias = 'Mario'\nlevel = 99\n# TODO: Print using f-string\n",
    hints: ["print(f'Plumber: {alias} | Hero Rank: {level}')"],
    solution: "alias = 'Mario'\nlevel = 99\nprint(f'Plumber: {alias} | Hero Rank: {level}')",
    solutionRegex: [/print\s*\(\s*f['"]Plumber:\s*\{alias\}\s*\|\s*Hero\s*Rank:\s*\{level\}['"]\s*\)/]
  },
  "input-fstrings-fun": {
    title: "Toad Mobilization: Dynamic Deployment",
    headerPrefix: "TOAD_TOWN",
    missionPrefix: "F_STRING_INPUT",
    intro: "# Toad Town Brigade: F-String Input\n\nPrompt the player for Toad reinforcements heading to distant castle worlds, formatting the world in uppercase.",
    technical: "Combine integer inputs with string formatting methods like `.upper()` in f-strings.",
    example: "print(f\"Deploying {toads} toads to {castle.upper()}...\")",
    task: "### YOUR MISSION\n\n1. Prompt for Toad count with: **\"Enter Toad count: \"** and store as int in `toads`.\n2. Prompt for castle world with: **\"Enter castle world: \"** and store in `castle`.\n3. Use an **f-string** to print: `Deploying {toads} toads to {castle.upper()}...`.",
    baseCode: "# TODO: Gather toad count and castle world\n",
    hints: ["toads = int(input(\"Enter Toad count: \"))","castle = input(\"Enter castle world: \")","print(f\"Deploying {toads} toads to {castle.upper()}...\")"],
    solution: "toads = int(input(\"Enter Toad count: \"))\ncastle = input(\"Enter castle world: \")\nprint(f\"Deploying {toads} toads to {castle.upper()}...\")",
    solutionRegex: [/print\s*\(\s*f['"]Deploying\s*\{toads\}\s*toads\s*to\s*\{castle\.upper\(\)\}\.\.\.['"]\s*\)/]
  },
  "input-cast-int": {
    title: "Coin Block: Integer Casting",
    headerPrefix: "SPECIAL_COINS",
    missionPrefix: "INT_CONVERSION",
    intro: "# Red & Blue Coins: Integer Casting\n\nTally red and blue coins by converting user inputs to integers before calculating the total coin bonus.",
    technical: "Wrap `input()` inside `int()` to convert text strings to numbers.",
    example: "red_coins = int(input(\"Enter red coins: \"))\nblue_coins = int(input(\"Enter blue coins: \"))\nprint(red_coins + blue_coins)",
    task: "### YOUR MISSION\n\nTally special coins:\n1. Prompt for red coins with **\"Enter red coins: \"** and store as an integer in `red_coins`.\n2. Prompt for blue coins with **\"Enter blue coins: \"** and store as an integer in `blue_coins`.\n3. Print the sum of these coins.",
    baseCode: "# TODO: Cast inputs to int and calculate sum\n",
    hints: ["red_coins = int(input(\"Enter red coins: \"))","blue_coins = int(input(\"Enter blue coins: \"))","print(red_coins + blue_coins)"],
    solution: "red_coins = int(input(\"Enter red coins: \"))\nblue_coins = int(input(\"Enter blue coins: \"))\nprint(red_coins + blue_coins)",
    solutionRegex: [/red_coins\s*=\s*int\s*\(\s*input/, /blue_coins\s*=\s*int\s*\(\s*input/, /print\s*\(\s*red_coins\s*\+\s*blue_coins\s*\)/]
  },
  "input-cast-float": {
    title: "Jump Physics: Float Casting",
    headerPrefix: "SUPER_JUMP",
    missionPrefix: "FLOAT_CALIBRATION",
    intro: "# Platformer Physics: Float Conversion\n\nCalculate Mario's vertical jump apex by multiplying takeoff velocity by the gravity pull coefficient.",
    technical: "Wrap `input()` in `float()` to parse decimals.",
    example: "jump_vel = float(input(\"Enter jump speed: \"))\ngravity = float(input(\"Gravity factor: \"))\nprint(jump_vel * gravity)",
    task: "### YOUR MISSION\n\nCalibrate jumping physics:\n1. Prompt for jump speed with **\"Enter jump speed: \"** and store as float in `jump_vel`.\n2. Prompt for gravity factor with **\"Gravity factor: \"** and store as float in `gravity`.\n3. Print the result of multiplying `jump_vel` by `gravity`.",
    baseCode: "# TODO: Cast inputs to float and multiply\n",
    hints: ["jump_vel = float(input(\"Enter jump speed: \"))","gravity = float(input(\"Gravity factor: \"))","print(jump_vel * gravity)"],
    solution: "jump_vel = float(input(\"Enter jump speed: \"))\ngravity = float(input(\"Gravity factor: \"))\nprint(jump_vel * gravity)",
    solutionRegex: [/jump_vel\s*=\s*float\s*\(\s*input/, /gravity\s*=\s*float\s*\(\s*input/, /print\s*\(\s*jump_vel\s*\*\s*gravity\s*\)/]
  },
  "control-indentation": {
    title: "Castle Drawbridge: Indentation",
    headerPrefix: "CASTLE_GATE",
    missionPrefix: "INDENT_BLOCK",
    intro: "# Castle Drawbridge: Indentation Rules\n\nLower the drawbridge over Bowser's lava moat by structuring a clean 4-space indented `if True:` block.",
    technical: "In Python, code blocks under an `if` statement must be indented by exactly 4 spaces.",
    example: "if True:\n    print(\"Accessing...\")",
    task: "### YOUR MISSION\n\n1. Set up an `if True:` condition block.\n2. On the next line, indented with 4 spaces, print **\"Accessing...\"** to lower the bridge.",
    baseCode: "# TODO: Indented if block\n",
    hints: ["if True:","    print(\"Accessing...\")"],
    solution: "if True:\n    print(\"Accessing...\")",
    solutionRegex: [/if\s+True\s*:/, /print\s*\(\s*['"]Accessing\.\.\.['"]\s*\)/]
  },
  "control-nested-indent": {
    title: "Bowser Throne: Double Indentation",
    headerPrefix: "THRONE_ROOM",
    missionPrefix: "NESTED_INDENT",
    intro: "# Bowser Throne Room: Double Indentation\n\nUnlock Bowser's inner sanctum doors using double-indented nested `if True:` blocks.",
    technical: "Nested if blocks require double indentation (8 spaces) on their interior executable statements.",
    example: "if True:\n    if True:\n        print(\"CORE ACCESS GRANTED\")",
    task: "### YOUR MISSION\n\n1. Write the outer gate with **`if True:`**.\n2. Nest the inner gate underneath with an inner **`if True:`** (indented by 4 spaces).\n3. On the innermost level (indented with 8 spaces), print **`\"CORE ACCESS GRANTED\"`**.",
    baseCode: "# TODO: Nested if blocks\n",
    hints: ["if True:","    if True:","        print(\"CORE ACCESS GRANTED\")"],
    solution: "if True:\n    if True:\n        print(\"CORE ACCESS GRANTED\")",
    solutionRegex: [/if\s+True\s*:/, /if\s+True\s*:/, /print\s*\(\s*['"]CORE\s+ACCESS\s+GRANTED['"]\s*\)/]
  },
  "control-if": {
    title: "Super Star: Simple If",
    headerPrefix: "STAR_POWER",
    missionPrefix: "STAR_FLAG",
    intro: "# Starman Invincibility: Simple If\n\nWhen Mario grabs a Super Star, check if super status is active to trigger invincible rainbow speed!",
    technical: "The `if` statement executes its code block if its boolean condition is True.",
    example: "if is_super:\n    print(\"SUPER MARIO ACTIVE\")",
    task: "### YOUR MISSION\n\nIf `is_super` is `True`, print `\"SUPER MARIO ACTIVE\"`.",
    baseCode: "is_super = True\n# TODO: Check super state\n",
    hints: ["if is_super:","    print(\"SUPER MARIO ACTIVE\")"],
    solution: "is_super = True\nif is_super:\n    print(\"SUPER MARIO ACTIVE\")",
    solutionRegex: [/if\s+is_super/, /print\s*\(\s*['"]SUPER MARIO ACTIVE['"]\s*\)/]
  },
  "control-else": {
    title: "Boss Door: If/Else",
    headerPrefix: "KEY_DOOR",
    missionPrefix: "ELSE_LOGIC",
    intro: "# Castle Keyhole: If/Else\n\nTest the castle skeleton key using an `if/else` block.",
    technical: "The `else` block runs when the preceding `if` condition evaluates to False.",
    example: "if key_valid:\n    print(\"ACCESS GRANTED\")\nelse:\n    print(\"ALARM TRIGGERED\")",
    task: "### YOUR MISSION\n\n1. Construct an `if/else` block evaluating `key_valid`.\n2. If `key_valid` is `True`, print **`\"ACCESS GRANTED\"`**.\n3. Else, print **`\"ALARM TRIGGERED\"`**.",
    baseCode: "key_valid = True\n# TODO: if/else branch\n",
    hints: ["if key_valid:","    print(\"ACCESS GRANTED\")","else:","    print(\"ALARM TRIGGERED\")"],
    solution: "if key_valid:\n    print(\"ACCESS GRANTED\")\nelse:\n    print(\"ALARM TRIGGERED\")",
    solutionRegex: [/if\s+key_valid/, /else\s*:/, /print\s*\(\s*['"]ACCESS GRANTED['"]\s*\)/, /print\s*\(\s*['"]ALARM TRIGGERED['"]\s*\)/]
  },
  "control-elif": {
    title: "Kingdom Clearance: Elif Levels",
    headerPrefix: "CASTLE_CLEARANCE",
    missionPrefix: "TIER_ELIF",
    intro: "# Royal Castle Pass: Elif Branching\n\nSort visitor privileges based on castle badge clearance levels.",
    technical: "Chaining `elif` conditions allows multiple separate outcomes to be evaluated in order.",
    example: "if clearance == 1:\n    print(\"ROOT ACCESS\")\nelif clearance <= 5:\n    print(\"LEVEL 5 ACCESS\")\nelse:\n    print(\"PERMISSION DENIED\")",
    task: "### YOUR MISSION\n\n1. Build an `if/elif/else` script around `clearance`.\n2. If `clearance` is exactly `1`, print **`\"ROOT ACCESS\"`**.\n3. Elif `clearance` is less than or equal to `5`, print **`\"LEVEL 5 ACCESS\"`**.\n4. Else, print **`\"PERMISSION DENIED\"`**.",
    baseCode: "clearance = 5\n# TODO: Route clearance\n",
    hints: ["if clearance == 1:","elif clearance <= 5:","else:"],
    solution: "if clearance == 1:\n    print(\"ROOT ACCESS\")\nelif clearance <= 5:\n    print(\"LEVEL 5 ACCESS\")\nelse:\n    print(\"PERMISSION DENIED\")",
    solutionRegex: [/if\s+clearance\s*==\s*1/, /elif\s+clearance\s*<=\s*5/, /else\s*:/, /print\s*\(\s*['"]ROOT ACCESS['"]\s*\)/, /print\s*\(\s*['"]LEVEL 5 ACCESS['"]\s*\)/, /print\s*\(\s*['"]PERMISSION DENIED['"]\s*\)/]
  },
  "control-meme-gen": {
    title: "Bowser's Flame: Pipe Retreat",
    headerPrefix: "LAVA_MOAT",
    missionPrefix: "FIRE_EVADE",
    intro: "# Castle Hazard: Pipe Retreat\n\nIf Bowser unleashes a giant fireball, duck into a green warp pipe immediately; otherwise, jump past the axe and touch the flagpole!",
    technical: "Use boolean conditions directly inside `if` statements.",
    example: "if is_detected:\n    print(\"WARP_PIPE_RETREAT\")\nelse:\n    print(\"Flagpole cleared with fireworks!\")",
    task: "### YOUR MISSION\n\nCompose an `if/else` guard:\n1. If `is_detected`, print **`\"WARP_PIPE_RETREAT\"`** to duck into safety.\n2. Else, print **`\"Flagpole cleared with fireworks!\"`**.",
    baseCode: "is_detected = True\n# TODO: Process retreat\n",
    hints: ["if is_detected:","    print(\"WARP_PIPE_RETREAT\")","else:","    print(\"Flagpole cleared with fireworks!\")"],
    solution: "if is_detected:\n    print(\"WARP_PIPE_RETREAT\")\nelse:\n    print(\"Flagpole cleared with fireworks!\")",
    solutionRegex: [/if\s+is_detected/, /else\s*:/, /print\s*\(\s*['"]WARP_PIPE_RETREAT['"]\s*\)/, /print\s*\(\s*['"]Flagpole\s+cleared\s+with\s+fireworks!['"]\s*\)/]
  },
  "control-nickname-gen": {
    title: "Plumber Rank: Super Star Title",
    headerPrefix: "HERO_LEVELLER",
    missionPrefix: "MARIO_TITLE",
    intro: "# High Score Hall: Player Rank Assignment\n\nAward Mario a prestigious title based on his total stage high score.",
    technical: "Assign a variable inside conditional branches and display it afterwards.",
    example: "if mario_score > 9000:\n    player_status = \"Super Star\"\nelse:\n    player_status = \"Novice\"\nprint(player_status)",
    task: "### YOUR MISSION\n\nVerify player tier:\n1. If `mario_score > 9000`, set `player_status` to **`\"Super Star\"`**.\n2. Else, set `player_status` to **`\"Novice\"`**.\n3. Finally, print `print(player_status)`.",
    baseCode: "mario_score = 9001\nplayer_status = \"\"\n# TODO: Evaluate hero rank and print\n",
    hints: ["if mario_score > 9000:","    player_status = \"Super Star\"","else:","    player_status = \"Novice\"","print(player_status)"],
    solution: "mario_score = 9001\nif mario_score > 9000:\n    player_status = \"Super Star\"\nelse:\n    player_status = \"Novice\"\nprint(player_status)",
    solutionRegex: [/if\s+mario_score\s*>\s*9000\s*:/, /player_status\s*=\s*['"]Super Star['"]/, /player_status\s*=\s*['"]Novice['"]/, /print\s*\(\s*player_status\s*\)/]
  },
  "control-adventure": {
    title: "Castle Door: Choice Routing",
    headerPrefix: "CASTLE_CHAMBER",
    missionPrefix: "CHAMBER_ROUTE",
    intro: "# Bowser Castle: Chamber Choice\n\nYou arrive at the twin gates of Bowser's keep: take bridge 1 (\"1\") or warp tunnel 2 (\"2\").",
    technical: "Compare `choice` using `==` against string values `'1'` and `'2'`.",
    example: "if choice == \"1\":\n    print(\"Rescued Princess Peach!\")\nelif choice == \"2\":\n    print(\"Found Secret Warp Zone!\")\nelse:\n    print(\"Thank you Mario! But our princess is in another castle.\")",
    task: "### YOUR MISSION\n\nCompose a castle chamber router:\n1. If `choice` is **\"1\"**, print **\"Rescued Princess Peach!\"**.\n2. Elif `choice` is **\"2\"**, print **\"Found Secret Warp Zone!\"**.\n3. Else, print **\"Thank you Mario! But our princess is in another castle.\"**.",
    baseCode: "choice = \"1\"\n# TODO: Route chamber choice\n",
    hints: ["if choice == \"1\":","elif choice == \"2\":","else:"],
    solution: "if choice == \"1\":\n    print(\"Rescued Princess Peach!\")\nelif choice == \"2\":\n    print(\"Found Secret Warp Zone!\")\nelse:\n    print(\"Thank you Mario! But our princess is in another castle.\")",
    solutionRegex: [/if\s+choice\s*==\s*['"]1['"]\s*:/, /elif\s+choice\s*==\s*['"]2['"]\s*:/, /else\s*:/, /print\s*\(\s*['"]Rescued Princess Peach!['"]\s*\)/, /print\s*\(\s*['"]Found Secret Warp Zone!['"]\s*\)/, /print\s*\(\s*['"]Thank you Mario! But our princess is in another castle\.['"]\s*\)/]
  },
  "control-multi-elif": {
    title: "Kingdom Zones: Multi Elif",
    headerPrefix: "ZONE_WARP",
    missionPrefix: "ZONE_SELECT",
    intro: "# Mushroom Kingdom Zones: Multi-Branch Routing\n\nRoute Mario to specific kingdom sectors based on the entered zone name.",
    technical: "Cascading `if/elif/elif/else` blocks inspect multiple alternatives sequentially.",
    example: "if kingdom_zone == \"mushroom\":\n    print(\"Toad Town peaceful.\")\nelif kingdom_zone == \"bowser\":\n    print(\"Lava moat boiling.\")",
    task: "### YOUR MISSION\n\nAssign zone status based on variable `kingdom_zone`:\n1. If `kingdom_zone` is **`\"mushroom\"`**, print **`\"Toad Town peaceful.\"`**\n2. Elif `kingdom_zone` is **`\"bowser\"`**, print **`\"Lava moat boiling.\"`**\n3. Elif `kingdom_zone` is **`\"underground\"`**, print **`\"Buzzy beetle cave.\"`**\n4. Else, print **`\"Unknown pipe route.\"`**",
    baseCode: "kingdom_zone = \"mushroom\"\n# TODO: Route kingdom zone\n",
    hints: ["if kingdom_zone == \"mushroom\":","elif kingdom_zone == \"bowser\":","elif kingdom_zone == \"underground\":","else:"],
    solution: "kingdom_zone = \"mushroom\"\nif kingdom_zone == \"mushroom\":\n    print(\"Toad Town peaceful.\")\nelif kingdom_zone == \"bowser\":\n    print(\"Lava moat boiling.\")\nelif kingdom_zone == \"underground\":\n    print(\"Buzzy beetle cave.\")\nelse:\n    print(\"Unknown pipe route.\")",
    solutionRegex: [/if\s+kingdom_zone\s*==\s*['"]mushroom['"]\s*:/, /elif\s+kingdom_zone\s*==\s*['"]bowser['"]\s*:/, /elif\s+kingdom_zone\s*==\s*['"]underground['"]\s*:/, /else\s*:/, /print\s*\(\s*['"]Toad\s+Town\s+peaceful\.['"]\s*\)/, /print\s*\(\s*['"]Lava\s+moat\s+boiling\.['"]\s*\)/, /print\s*\(\s*['"]Buzzy\s+beetle\s+cave\.['"]\s*\)/, /print\s*\(\s*['"]Unknown\s+pipe\s+route\.['"]\s*\)/]
  },
  "control-loops": {
    title: "Coin Trail: Range Loop",
    headerPrefix: "COIN_LOOP",
    missionPrefix: "COIN_COLLECT",
    intro: "# Coin Block Run: For Loops\n\nAutomate gathering a trail of 5 consecutive coins with a `for` loop.",
    technical: "The `range(5)` function loops 5 times, passing indices 0 through 4 to variable `i`.",
    example: "for i in range(5):\n    print(f\"Coin {i+1} collected\")",
    task: "### YOUR MISSION\n\nUse a `for` loop with `range(5)` to `print` the status message `f\"Coin {i+1} collected\"` for each of the 5 coins.",
    baseCode: "# TODO: Loop 5 times\n",
    hints: ["for i in range(5):","    print(f\"Coin {i+1} collected\")"],
    solution: "for i in range(5):\n    print(f\"Coin {i+1} collected\")",
    solutionRegex: [/for\s+i\s+in\s+range\s*\(\s*5\s*\)/, /print/]
  },
  "loop-data-scan": {
    title: "Pipe Sequence: Character Iteration",
    headerPrefix: "PIPE_CODE",
    missionPrefix: "CODE_SCAN",
    intro: "# Warp Pipe Dial: Character Parsing\n\nRead every letter of the secret warp route code `\"JUMP\"`.",
    technical: "Iterating through strings processes characters sequentially one by one.",
    example: "for letter in warp_code:\n    print(letter)",
    task: "### YOUR MISSION\n\nYou've uncovered a pipe code `warp_code`: `\"JUMP\"`. Use a `for` loop to iterate through every character `letter` in `warp_code` and `print` it.",
    baseCode: "warp_code = \"JUMP\"\n# TODO: Iterate through letters\n",
    hints: ["for letter in warp_code:","    print(letter)"],
    solution: "warp_code = \"JUMP\"\nfor letter in warp_code:\n    print(letter)",
    solutionRegex: [/for\s+letter\s+in\s+warp_code/, /print\s*\(\s*letter\s*\)/]
  },
  "loop-list-audit": {
    title: "NES Cartridge: File Audit",
    headerPrefix: "CARTRIDGE_LOADER",
    missionPrefix: "SPRITE_FILTER",
    intro: "# Stage Loader: Filter Sprite Files\n\nScan through incoming cartridge assets and load only valid retro sprite packages ending in `.nes`.",
    technical: "The `.endswith()` method returns True if a string ends with the specified file extension.",
    example: "for asset in level_assets:\n    if asset.endswith(\".nes\"):\n        print(f\"Loading sprite: {asset}\")",
    task: "### YOUR MISSION\n\nScan through `level_assets`. If a file ends with `\".nes\"`, `print` the output line: `f\"Loading sprite: {asset}\"`.",
    baseCode: "level_assets = [\"mush.nes\", \"audio.wav\", \"pipe.nes\", \"save.dat\"]\n# TODO: Audit sprite files\n",
    hints: ["for asset in level_assets:","    if asset.endswith(\".nes\"):","        print(f\"Loading sprite: {asset}\")"],
    solution: "level_assets = [\"mush.nes\", \"audio.wav\", \"pipe.nes\", \"save.dat\"]\nfor asset in level_assets:\n    if asset.endswith(\".nes\"):\n        print(f\"Loading sprite: {asset}\")",
    solutionRegex: [/for\s+asset\s+in\s+level_assets/, /asset\.endswith\s*\(\s*['"]\.nes['"]\s*\)/, /print/]
  },
  "loop-nested": {
    title: "Mushroom Grid: 3x3 Grid Scan",
    headerPrefix: "KINGDOM_MAP",
    missionPrefix: "GRID_SCAN",
    intro: "# Mushroom Kingdom Grid: Nested Loops\n\nScan a 3x3 tile grid in the Mushroom Kingdom using nested loops.",
    technical: "Nested loops execute the inner loop completely for each step of the outer loop.",
    example: "for x in range(3):\n    for y in range(3):\n        print(f\"Mushroom Grid - Row: {x}, Col: {y}\")",
    task: "### YOUR MISSION\n\nScan a **3x3 tile grid**. Code nested loops with `range(3)` for `x` and `y`.\n\nInside the inner loop, `print` each coordinate in this exact format: `f\"Mushroom Grid - Row: {x}, Col: {y}\"`.\n\nMake sure your `print` is indented with 8 spaces!",
    baseCode: "# TODO: Nested grid loop\n",
    hints: ["for x in range(3):","    for y in range(3):","        print(f\"Mushroom Grid - Row: {x}, Col: {y}\")"],
    solution: "for x in range(3):\n    for y in range(3):\n        print(f\"Mushroom Grid - Row: {x}, Col: {y}\")",
    solutionRegex: [/for\s+x/, /for\s+y/, /print/]
  },
  "loop-break-continue": {
    title: "Flagpole Slide: Loop Break",
    headerPrefix: "FLAGPOLE_SLIDE",
    missionPrefix: "FLAG_STOP",
    intro: "# Flagpole Finish: Loop Break\n\nSlide down the 10-tier flagpole. When Mario reaches tier index `7`, break immediately to stick the landing and launch fireworks!",
    technical: "The `break` statement halts loop execution immediately.",
    example: "for i in range(10):\n    if i == 7:\n        break\n    print(i)",
    task: "### YOUR MISSION\n\nLoop through `range(10)`. If flagpole slide index `i` reaches `7`, call `break`. Otherwise, `print` current index `i` using `print(i)`.",
    baseCode: "# TODO: Loop with break condition\n",
    hints: ["for i in range(10):","    if i == 7:","        break","    print(i)"],
    solution: "for i in range(10):\n    if i == 7:\n        break\n    print(i)",
    solutionRegex: [/for\s+i\s+in\s+range/, /if\s+i\s*==\s*7/, /break/, /print/]
  },
  "control-while": {
    title: "Starman Timer: While Loop",
    headerPrefix: "STARMAN_TIMER",
    missionPrefix: "STAR_DRAIN",
    intro: "# Invincible Starman: While Loops\n\nWhile loops run as long as power remains active. Track Starman battery power as it drains down to zero.",
    task: "### YOUR MISSION\n\n1. `battery` starts at `100`.\n2. While `battery > 0`, subtract `20` from `battery` to power the star.\n3. `print` the current `battery` level inside the loop.",
  },
  "functions-intro": {
    headerPrefix: "WARP_PIPE_ROUTINE",
    missionPrefix: "PIPE_JUMP",
    intro: "# Warp Routing: Functions\n\nDefine a reusable warp routine instead of re-coding pipe entry animations for every level!",
    task: "Write a function `jump_pipe(pipe_code)` that prints `f'Warping through pipe {pipe_code}...'`. Call it with `'World-4'`.",
    baseCode: "# TODO: Define jump_pipe function\n",
    solution: "def jump_pipe(pipe_code):\n    print(f'Warping through pipe {pipe_code}...')\n\njump_pipe('World-4')",
    solutionRegex: [/def\s+jump_pipe/, /jump_pipe\s*\(/]
  },
  "functions-recursion": {
    headerPrefix: "COIN_COUNTDOWN",
    missionPrefix: "RECURSIVE_COIN",
    intro: "# Coin Block Cascade: Recursion\n\nCollect a multi-coin block cascade using a recursive function that pops coins until count reaches 0!",
    task: "Write a recursive function `coin_countdown(coins)` that prints the coins and calls itself with `coins-1` until it reaches `0`. Call it with `5`.",
    baseCode: "# TODO: Define recursive function\n",
    solution: "def coin_countdown(coins):\n    print(coins)\n    if coins > 0:\n        coin_countdown(coins - 1)\n\ncoin_countdown(5)",
    solutionRegex: [/def\s+coin_countdown/, /coin_countdown\s*\(\s*coins\s*-\s*1\s*\)/]
  },
  "oop-intro": {
    headerPrefix: "HERO_REGISTRY",
    missionPrefix: "HERO_TEMPLATE",
    intro: "# Mushroom Kingdom Heroes: Classes\n\nEvery character in the Mushroom Kingdom (Mario, Luigi, Toad) shares fundamental player attributes. Define a reusable blueprint called a **Class**.",
    task: "### YOUR MISSION\n\nDefine a base class named `Character`. Use `pass` inside its block under proper indentation.",
    baseCode: "# TODO: Establish base class Character\n",
    hints: ["Use 'class Character:' followed by an indented 'pass'."],
    solution: "class Character:\n    pass",
    solutionRegex: [/class\s+Character/, /pass/]
  },
  "oop-init": {
    headerPrefix: "PLAYER_SELECT",
    missionPrefix: "HERO_CONSTRUCTOR",
    intro: "# Player Select Screen: Constructors\n\nWhen a player selects their hero at the title screen, initialize their hero name with the `__init__` constructor.",
    task: "### YOUR MISSION\n\nInside `Character`, define the constructor method `__init__` which accepts `self` and a parameter `name`. Assign the `name` value to `self.name`.",
    baseCode: "class Character:\n    # TODO: Add __init__ constructor\n",
    hints: ["def __init__(self, name):","    self.name = name"],
    solution: "class Character:\n    def __init__(self, name):\n        self.name = name",
    solutionRegex: [/def\s+__init__\s*\(\s*self\s*,\s*name\s*\)\s*:/, /self\.name\s*=\s*name/]
  },
  "oop-methods": {
    headerPrefix: "JUMP_PHYSICS",
    missionPrefix: "JUMP_ACTION",
    intro: "# Super Jump: Methods\n\nA Mushroom Kingdom hero needs active abilities like jumping! Functions defined inside a class are called **Methods**.",
    task: "### YOUR MISSION\n\nAdd a `jump` method to `Character` that `print`s \"Super jump activated\".",
    baseCode: "class Character:\n    def __init__(self, name):\n        self.name = name\n    # TODO: Define jump method\n",
    hints: ["def jump(self):","    print(\"Super jump activated\")"],
    solution: "class Character:\n    def __init__(self, name):\n        self.name = name\n    def jump(self):\n        print(\"Super jump activated\")",
    solutionRegex: [/def\s+jump\s*\(\s*self\s*\)\s*:/, /print\s*\(\s*['"]Super jump activated['"]\s*\)/]
  },
  "oop-state": {
    headerPrefix: "GROWTH_STATE",
    missionPrefix: "FORM_CHECK",
    intro: "# Power-Up Transformation: Object State\n\nCharacters track their transformation form (Small vs Super) as they grab power-up mushrooms.",
    task: "### YOUR MISSION\n\n1. In `__init__`, add a `form` instance variable defaulted to the string \"Small\".\n2. Create a method `grow` that updates `self.form` to the string \"Super\".",
    baseCode: "class Character:\n    def __init__(self, name):\n        self.name = name\n        # TODO: Add form default\n    # TODO: Add grow method\n",
    hints: ["self.form = \"Small\"","def grow(self):","    self.form = \"Super\""],
    solution: "class Character:\n    def __init__(self, name):\n        self.name = name\n        self.form = \"Small\"\n    def grow(self):\n        self.form = \"Super\"",
    solutionRegex: [/self\.form\s*=\s*['"]Small['"]/, /def\s+grow/, /self\.form\s*=\s*['"]Super['"]/]
  },
  "oop-interaction": {
    headerPrefix: "CO_OP_HIGHFIVE",
    missionPrefix: "TEAM_PLAY",
    intro: "# Co-Op Adventures: Object Interaction\n\nIn multiplayer Mario games, heroes interact directly by passing power-ups and giving high fives! Methods can accept other instances as arguments.",
    task: "### YOUR MISSION\n\nAdd a `high_five` method to `Character` that accepts `other` as its parameter. It should `print` the formatted message: `f\"High five with: {other.name}\"`.",
    baseCode: "class Character:\n    def __init__(self, name):\n        self.name = name\n    # TODO: Add high_five method\n",
    hints: ["def high_five(self, other):","    print(f\"High five with: {other.name}\")"],
    solution: "class Character:\n    def __init__(self, name):\n        self.name = name\n    def high_five(self, other):\n        print(f\"High five with: {other.name}\")",
    solutionRegex: [/def\s+high_five\s*\(\s*self\s*,\s*other\s*\)\s*:/, /other\.name/]
  },
  "oop-inheritance": {
    headerPrefix: "FIRE_MARIO",
    missionPrefix: "FIRE_SUBCLASS",
    intro: "# Fire Power: Inheritance\n\nFire Mario inherits all standard abilities from Character, but gains the fiery ability to throw bouncing fireballs!",
    task: "### YOUR MISSION\n\nCreate a class `SuperPlayer` that inherits from `Character`. Give it a `throw_fireball` method that `print`s \"Fireball launched\".",
    baseCode: "class Character:\n    def __init__(self, name):\n        self.name = name\n# TODO: Create SuperPlayer subclass inheriting from Character\n",
    hints: ["class SuperPlayer(Character):","    def throw_fireball(self):","        print(\"Fireball launched\")"],
    solution: "class Character:\n    def __init__(self, name):\n        self.name = name\n\nclass SuperPlayer(Character):\n    def throw_fireball(self):\n        print(\"Fireball launched\")",
    solutionRegex: [/class\s+SuperPlayer\s*\(\s*Character\s*\)\s*:/, /def\s+throw_fireball/, /print\s*\(\s*['"]Fireball launched['"]\s*\)/]
  },
  "oop-str": {
    headerPrefix: "NAME_BADGE",
    missionPrefix: "HERO_TAG",
    intro: "# Scoreboard Readout: Special Str Method\n\nOverride `__str__` so the scoreboard prints a clean, charming hero tag instead of an obscure memory address.",
    task: "### YOUR MISSION\n\nIn `Character`, add the custom method `__str__` that returns: `f\"Super Mario Character {self.name}\"`.",
    baseCode: "class Character:\n    def __init__(self, name):\n        self.name = name\n    # TODO: Add __str__ method\n",
    hints: ["def __str__(self):","    return f\"Super Mario Character {self.name}\""],
    solution: "class Character:\n    def __init__(self, name):\n        self.name = name\n    def __str__(self):\n        return f\"Super Mario Character {self.name}\"",
    solutionRegex: [/def\s+__str__/, /return\s+f['"].*Super Mario Character.*self\.name.*['"]/]
  },
  "oop-class-vars": {
    headerPrefix: "FRANCHISE_FLAG",
    missionPrefix: "GLOBAL_FRANCHISE",
    intro: "# Nintendo Legacy: Shared Class Variables\n\nEvery character across every world belongs to the Super Mario franchise. Store this universal constant in a class variable.",
    task: "### YOUR MISSION\n\n1. Define a class variable `franchise` set to \"Super Mario\" inside `Character` before other initialisers.\n2. `print` the class variable using `Character.franchise`.",
    baseCode: "class Character:\n    # TODO: Define class variable 'franchise'\n    pass\n# TODO: Print Character.franchise\n",
    hints: ["franchise = \"Super Mario\"","print(Character.franchise)"],
    solution: "class Character:\n    franchise = \"Super Mario\"\n\nprint(Character.franchise)",
    solutionRegex: [/franchise\s*=\s*['"]Super Mario['"]/, /print\s*\(\s*Character\.franchise\s*\)/]
  }
};
