export const MECHA_THEME: any = {
  "intro-print": {
    title: "Cockpit Boot: Hello Mecha",
    headerPrefix: "MECHA_HUD",
    missionPrefix: "PILOT_INIT",
    intro: "# Neural Cockpit Handshake: print()\n\nWelcome to Tokyo-3 Defense Command! The seismic sirens are blaring across the bay—a Category 4 Kaiju has breached the defensive perimeter! Power on your mobile suit's central processing unit and announce your readiness to Central Command.",
    technical: "In Python, the `print()` function sends system messages or variables to the telemetry terminal display.",
    example: "print(\"All systems nominal. Gundam launching!\")",
    task: "### YOUR MISSION\n\nUse `print()` to send the launch message: `\"All systems nominal. Gundam launching!\"`",
    baseCode: "# TODO: Transmit launch readiness to command\n",
    hints: ["Type print(\"All systems nominal. Gundam launching!\")", "Ensure the text is enclosed in double quotes"],
    solution: "print(\"All systems nominal. Gundam launching!\")",
    solutionRegex: [/print\s*\(\s*['"]All systems nominal\.\s*Gundam launching!['"]\s*\)/]
  },
  "naming-conventions": {
    title: "Telemetry Index: Lowercase Names",
    headerPrefix: "TELEMETRY_LOG",
    missionPrefix: "SENSOR_TAG",
    intro: "# Sensor Calibration: Lowercase Names\n\nThe defense mainframe requires strict snake_case naming conventions for all telemetry variables to prevent compiler faults in heat-sensitive flight subroutines.",
    technical: "Python variables must begin with a lowercase letter or underscore, and compound words should be joined by underscores `_`.",
    example: "missile_payload = 24\nprint(missile_payload)",
    task: "### YOUR MISSION\n\nCreate a lowercase variable named `missile_payload` set to `24`. Print it with `print()` to verify your bay telemetry.",
    baseCode: "# TODO: Initialize missile_payload and print\n",
    hints: ["Write missile_payload = 24", "On the next line, write print(missile_payload)"],
    solution: "missile_payload = 24\nprint(missile_payload)",
    solutionRegex: [/missile_payload\s*=\s*24/, /print\s*\(\s*missile_payload\s*\)/]
  },
  "intro-comments": {
    title: "Battle Protocol: Comments",
    headerPrefix: "MAINTENANCE_LOG",
    missionPrefix: "CREW_NOTE",
    intro: "# Flight Engineer Protocol: Comments\n\nBefore engaging an atomic Kaiju, the hangar pit crew leaves calibration notes in the system flight logs without interfering with autopilot systems.",
    technical: "Lines beginning with `#` are comments. Python bypasses them during execution, making them perfect for tactical maintenance notes.",
    example: "# Calibrate plasma cannons\nprint(\"Target locked!\")",
    task: "### YOUR MISSION\n\nWrite a comment `# Calibrate plasma cannons` and then `print(\"Target locked!\")`",
    baseCode: "# TODO: Add maintenance comment and lock target\n",
    hints: ["Line 1: # Calibrate plasma cannons", "Line 2: print(\"Target locked!\")"],
    solution: "# Calibrate plasma cannons\nprint(\"Target locked!\")",
    solutionRegex: [/#.*Calibrate plasma cannons/, /print\s*\(\s*['"]Target locked!['"]\s*\)/]
  },
  "comments-inline": {
    title: "Core Status: Inline Comments",
    headerPrefix: "REACTOR_BAY",
    missionPrefix: "CORE_COMMENT",
    intro: "# Reactor Output Tagging: Inline Comments\n\nRecord the Jaeger reactor synchronization percentage on the same line as your core initialization code.",
    technical: "Inline comments follow executable code on the same line, prefixed by a `#`.",
    example: "reactor_core = 95.5 # Core output safe",
    task: "### YOUR MISSION\n\nInitialize `reactor_core` to `95.5`. On the same line, add an inline comment `# Core output safe`.",
    baseCode: "# TODO: Initialize variable with inline comment\n",
    hints: ["Write reactor_core = 95.5 followed by # Core output safe on the same line."],
    solution: "reactor_core = 95.5 # Core output safe",
    solutionRegex: [/reactor_core\s*=\s*95\.5/, /#.*Core output safe/]
  },
  "intro-vars": {
    title: "System Telemetry: Variables",
    headerPrefix: "DIAGNOSTICS_BUS",
    missionPrefix: "TELEMETRY_ALLOC",
    intro: "# Defense Grid Telemetry: Variables\n\n**What is a Variable?** Think of a **variable** as a **telemetry monitor in your robot's cockpit**! You label each gauge (like `shield_level` or `missile_payload`), store live sensor data inside, and query it during intense Kaiju battles.",
    technical: "Variables store data values in system memory so you can monitor, calculate, and modify them as combat evolves.",
    example: "shield_level = 100\nmissile_payload = 36",
    task: "### YOUR MISSION\n\nCreate variable `shield_level` set to `100` and `missile_payload` set to `36`.",
    baseCode: "# TODO: Store shield_level and missile_payload\n",
    hints: ["shield_level = 100", "missile_payload = 36"],
    solution: "shield_level = 100\nmissile_payload = 36",
    solutionRegex: [/shield_level\s*=\s*100/, /missile_payload\s*=\s*36/]
  },
  "vars-reassignment": {
    title: "Shield Overcharge: Reassignment",
    headerPrefix: "SHIELD_AMPLIFIER",
    missionPrefix: "ENERGY_REALLOC",
    intro: "# Emergency Shield Overcharge: Reassignment\n\nGodzilla is powering up his atomic breath! Divert auxiliary reactor power to overcharge your energy shielding from 50% to 150%.",
    technical: "Reassigning a variable updates its value in place, discarding whatever data was previously stored.",
    example: "shield_level = 50\nshield_level = 150\nprint(shield_level)",
    task: "### YOUR MISSION\n\nInitialize `shield_level` as `50`. Then reassign `shield_level` to `150`. Print it.",
    baseCode: "shield_level = 50\n# TODO: Overcharge shield_level to 150 and print\n",
    hints: ["shield_level = 150", "print(shield_level)"],
    solution: "shield_level = 50\nshield_level = 150\nprint(shield_level)",
    solutionRegex: [/shield_level\s*=\s*150/, /print\s*\(\s*shield_level\s*\)/]
  },
  "vars-placeholder": {
    title: "Radar Target: Variable Interpolation",
    headerPrefix: "SECTOR_SCANNER",
    missionPrefix: "TARGET_TAG",
    intro: "# Radar Tracking: Target Identification\n\nDisplay the approaching beast's codename by storing it in a telemetry variable and outputting it to the bridge screen.",
    technical: "Variables allow dynamic content insertion into program output streams.",
    example: "kaiju_target = \"Category 4 - Titan\"\nprint(kaiju_target)",
    task: "### YOUR MISSION\n\nCreate variable `kaiju_target` with value `\"Category 4 - Titan\"` and print it.",
    baseCode: "# TODO: Declare kaiju_target and print\n",
    hints: ["kaiju_target = \"Category 4 - Titan\"", "print(kaiju_target)"],
    solution: "kaiju_target = \"Category 4 - Titan\"\nprint(kaiju_target)",
    solutionRegex: [/kaiju_target\s*=\s*['"]Category 4 - Titan['"]/, /print\s*\(\s*kaiju_target\s*\)/]
  },
  "vars-multi": {
    title: "Cockpit Telemetry: Multiple Assignment",
    headerPrefix: "AVIONICS_SUITE",
    missionPrefix: "TRIPLE_SENSOR",
    intro: "# Flight Suite Diagnostics: Multiple Assignment\n\nIn high-speed dogfights against airborne monstrosities, sync core reactor output, shield strength, and armor integrity simultaneously on one line.",
    technical: "Multiple variable assignments can be chained on one line using commas: `a, b, c = 1, 2, 3`.",
    example: "reactor, shield, armor = 100, 80, 95\nprint(reactor, shield, armor)",
    task: "### YOUR MISSION\n\nAssign `reactor, shield, armor = 100, 80, 95` on a single line and print them.",
    baseCode: "# TODO: Multi-assign reactor, shield, and armor then print\n",
    hints: ["reactor, shield, armor = 100, 80, 95", "print(reactor, shield, armor)"],
    solution: "reactor, shield, armor = 100, 80, 95\nprint(reactor, shield, armor)",
    solutionRegex: [/reactor\s*,\s*shield\s*,\s*armor\s*=\s*100\s*,\s*80\s*,\s*95/, /print\s*\(\s*reactor\s*,\s*shield\s*,\s*armor\s*\)/]
  },
  "data-strings": {
    title: "Mecha Designation: Strings",
    headerPrefix: "HANGAR_REGISTRY",
    missionPrefix: "UNIT_CALLSIGN",
    intro: "# Unit Callsign Registration: Strings\n\nEvery mechanized defender deployed to Tokyo Bay has a formal serial number and combat callsign recorded as text strings.",
    technical: "Text data is represented by strings wrapped in quotation marks.",
    example: "unit_callsign = \"Gundam RX-78-2\"\npilot_name = \"Amuro Ray\"",
    task: "### YOUR MISSION\n\nCreate variable `unit_callsign` set to `\"Gundam RX-78-2\"` and `pilot_name` set to `\"Amuro Ray\"`. Print both.",
    baseCode: "# TODO: Create unit_callsign and pilot_name, then print\n",
    hints: ["unit_callsign = \"Gundam RX-78-2\"", "pilot_name = \"Amuro Ray\"", "print(unit_callsign, pilot_name)"],
    solution: "unit_callsign = \"Gundam RX-78-2\"\npilot_name = \"Amuro Ray\"\nprint(unit_callsign, pilot_name)",
    solutionRegex: [/unit_callsign\s*=\s*['"]Gundam RX-78-2['"]/, /pilot_name\s*=\s*['"]Amuro Ray['"]/]
  },
  "data-booleans": {
    title: "Radar Threat Alert: Booleans",
    headerPrefix: "EARLY_WARNING",
    missionPrefix: "KAIJU_RADAR",
    intro: "# Seismic Perimeter: Booleans\n\nSonar sensors along the oceanic trench ping constantly. If anomalous wave patterns appear, flip the emergency alarm flag to `True`.",
    technical: "Booleans evaluate to `True` or `False` without quotation marks.",
    example: "kaiju_detected = True\ncity_evacuated = False",
    task: "### YOUR MISSION\n\nSet `kaiju_detected` to `True` and `city_evacuated` to `False`. Print both.",
    baseCode: "# TODO: Define boolean radar telemetry\n",
    hints: ["kaiju_detected = True", "city_evacuated = False", "print(kaiju_detected, city_evacuated)"],
    solution: "kaiju_detected = True\ncity_evacuated = False\nprint(kaiju_detected, city_evacuated)",
    solutionRegex: [/kaiju_detected\s*=\s*True/, /city_evacuated\s*=\s*False/]
  },
  "intro-math": {
    title: "Missile Volley: Basic Math",
    headerPrefix: "ORDNANCE_BAY",
    missionPrefix: "MISSILE_COUNT",
    intro: "# Ammunition Depletion: Basic Math\n\nYour mecha unit started with 48 micro-missiles in Bay A and 32 in Bay B. Calculate the combined payload reserve.",
    technical: "Standard math operators `+`, `-`, `*`, `/` perform numerical calculations in Python.",
    example: "bay_a = 48\nbay_b = 32\ntotal_missiles = bay_a + bay_b\nprint(total_missiles)",
    task: "### YOUR MISSION\n\nCalculate `total_missiles = 48 + 32` and print `total_missiles`.",
    baseCode: "# TODO: Calculate total_missiles and print\n",
    hints: ["total_missiles = 48 + 32", "print(total_missiles)"],
    solution: "total_missiles = 48 + 32\nprint(total_missiles)",
    solutionRegex: [/total_missiles\s*=\s*48\s*\+\s*32/, /print\s*\(\s*total_missiles\s*\)/]
  },
  "math-complex": {
    title: "Beam Cannon Discharge: Compound Math",
    headerPrefix: "ENERGY_CAPACITOR",
    missionPrefix: "MEGA_BEAM_BURST",
    intro: "# Particle Accelerator Output: Compound Math\n\nCalculate the total megawatt output of the Hyper Mega Particle Cannon: `(base_flux + booster_flux) * efficiency`.",
    technical: "Use parentheses to enforce calculation order before applying multipliers.",
    example: "flux = (500 + 250) * 0.8\nprint(flux)",
    task: "### YOUR MISSION\n\nGiven `base_flux = 500`, `booster_flux = 250`, and `efficiency = 0.8`, compute `beam_output = (base_flux + booster_flux) * efficiency` and print it.",
    baseCode: "base_flux = 500\nbooster_flux = 250\nefficiency = 0.8\n# TODO: Calculate beam_output and print\n",
    hints: ["beam_output = (base_flux + booster_flux) * efficiency", "print(beam_output)"],
    solution: "base_flux = 500\nbooster_flux = 250\nefficiency = 0.8\nbeam_output = (base_flux + booster_flux) * efficiency\nprint(beam_output)",
    solutionRegex: [/beam_output\s*=\s*\(\s*base_flux\s*\+\s*booster_flux\s*\)\s*\*\s*efficiency/, /print\s*\(\s*beam_output\s*\)/]
  },
  "intro-lists": {
    title: "City Defense Sectors: Lists",
    headerPrefix: "TOKYO_DEFENSE",
    missionPrefix: "SECTOR_ROSTER",
    intro: "# Urban Defense Grid: Lists\n\nThe Defense Force organizes Tokyo into fortified urban sectors. Store the active defense zones in an ordered Python list.",
    technical: "Lists are mutable, ordered collections declared with brackets `[...]`.",
    example: "defense_sectors = [\"Shinjuku\", \"Odaiba\", \"Ginza\"]\nprint(defense_sectors)",
    task: "### YOUR MISSION\n\nInitialize `defense_sectors` with `\"Shinjuku\"`, `\"Odaiba\"`, and `\"Ginza\"`. Print `defense_sectors`.",
    baseCode: "# TODO: Initialize defense_sectors list and print\n",
    hints: ["defense_sectors = [\"Shinjuku\", \"Odaiba\", \"Ginza\"]", "print(defense_sectors)"],
    solution: "defense_sectors = [\"Shinjuku\", \"Odaiba\", \"Ginza\"]\nprint(defense_sectors)",
    solutionRegex: [/defense_sectors\s*=\s*\[\s*['"]Shinjuku['"]\s*,\s*['"]Odaiba['"]\s*,\s*['"]Ginza['"]\s*\]/, /print\s*\(\s*defense_sectors\s*\)/]
  },
  "list-indexing": {
    title: "Sensor Priorities: List Indexing",
    headerPrefix: "RADAR_PRIORITY",
    missionPrefix: "SECTOR_SELECT",
    intro: "# Radar Coordinates: List Indexing\n\nTargeting computers select sectors by index number! Index `0` represents the immediate ground zero zone, while index `2` is the secondary fallback line.",
    technical: "List indices start at `0`. Index `2` accesses the 3rd element.",
    example: "ground_zero = defense_sectors[0]\nfallback = defense_sectors[2]",
    task: "### YOUR MISSION\n\n1. Store index `0` of `defense_sectors` in `ground_zero`.\n2. Store index `2` of `defense_sectors` in `fallback_zone`.\n3. Print both variables.",
    baseCode: "defense_sectors = [\"Shinjuku\", \"Odaiba\", \"Ginza\"]\n# TODO: Extract indices 0 and 2 and print\n",
    hints: ["ground_zero = defense_sectors[0]", "fallback_zone = defense_sectors[2]", "print(ground_zero)", "print(fallback_zone)"],
    solution: "defense_sectors = [\"Shinjuku\", \"Odaiba\", \"Ginza\"]\nground_zero = defense_sectors[0]\nfallback_zone = defense_sectors[2]\nprint(ground_zero)\nprint(fallback_zone)",
    solutionRegex: [/ground_zero\s*=\s*defense_sectors\s*\[\s*0\s*\]/, /fallback_zone\s*=\s*defense_sectors\s*\[\s*2\s*\]/]
  },
  "list-append": {
    title: "Deploying Fortifications: .append()",
    headerPrefix: "SECTOR_EXPANSION",
    missionPrefix: "ADD_SECTOR",
    intro: "# Expanding Defense Perimeter: .append()\n\nEngineers have erected emergency anti-Kaiju blast walls around Roppongi! Add this new zone to your active defense sectors list.",
    technical: "Calling `.append()` attaches a new element directly to the end of a list.",
    example: "defense_sectors.append(\"Roppongi\")\nprint(defense_sectors)",
    task: "### YOUR MISSION\n\n1. Append `\"Roppongi\"` to `defense_sectors`.\n2. Print `defense_sectors`.",
    baseCode: "defense_sectors = [\"Shinjuku\", \"Odaiba\", \"Ginza\"]\n# TODO: Append Roppongi and print\n",
    hints: ["defense_sectors.append(\"Roppongi\")", "print(defense_sectors)"],
    solution: "defense_sectors = [\"Shinjuku\", \"Odaiba\", \"Ginza\"]\ndefense_sectors.append(\"Roppongi\")\nprint(defense_sectors)",
    solutionRegex: [/defense_sectors\.\s*append\s*\(\s*['"]Roppongi['"]\s*\)/, /print\s*\(\s*defense_sectors\s*\)/]
  },
  "list-pop": {
    title: "Evacuation Protocol: .pop()",
    headerPrefix: "BREACH_EVAC",
    missionPrefix: "POP_SECTOR",
    intro: "# Sector Breach: .pop()\n\nThe giant monster has overrun the rearmost defense barricade! Remove the compromised sector using `.pop()` and store it in an evacuation alert variable.",
    technical: "`.pop()` removes and returns the final item from a list.",
    example: "fallen_zone = defense_sectors.pop()\nprint(fallen_zone)",
    task: "### YOUR MISSION\n\n1. Pop the last item from `defense_sectors` into `compromised_zone`.\n2. Print `compromised_zone`.",
    baseCode: "defense_sectors = [\"Shinjuku\", \"Odaiba\", \"Ginza\"]\n# TODO: Pop the last sector and print\n",
    hints: ["compromised_zone = defense_sectors.pop()", "print(compromised_zone)"],
    solution: "defense_sectors = [\"Shinjuku\", \"Odaiba\", \"Ginza\"]\ncompromised_zone = defense_sectors.pop()\nprint(compromised_zone)",
    solutionRegex: [/compromised_zone\s*=\s*defense_sectors\.\s*pop\s*\(\s*\)/, /print\s*\(\s*compromised_zone\s*\)/]
  },
  "intro-tuples": {
    title: "Launch Coordinates: Tuples",
    headerPrefix: "SILO_COORDINATES",
    missionPrefix: "IMMUTABLE_SILO",
    intro: "# Fixed Silo Coordinates: Tuples\n\nUnderground Jaeger launch silo coordinates must never shift or be rewritten during seismic tremors. Store them inside an immutable tuple.",
    technical: "Tuples use parentheses `()` and represent fixed, immutable coordinate data.",
    example: "silo_coords = (35.6895, 139.6917)\nprint(silo_coords)",
    task: "### YOUR MISSION\n\n1. Create a tuple named `silo_coords` with values `(35.6895, 139.6917)`.\n2. Print `silo_coords`.",
    baseCode: "# TODO: Initialize coordinate tuple and print\n",
    hints: ["silo_coords = (35.6895, 139.6917)", "print(silo_coords)"],
    solution: "silo_coords = (35.6895, 139.6917)\nprint(silo_coords)",
    solutionRegex: [/silo_coords\s*=\s*\(\s*35\.6895\s*,\s*139\.6917\s*\)/, /print\s*\(\s*silo_coords\s*\)/]
  },
  "intro-tuples-immutability": {
    title: "Payload vs Bay Coordinates: Immutability",
    headerPrefix: "TELEMETRY_LOCK",
    missionPrefix: "COMPARE_COLLECTIONS",
    intro: "# Missile Bay vs Fixed Hardpoint: Immutability\n\nMissile loadouts change throughout battle, but the physical chassis hardpoint dimensions are permanently locked in steel.",
    technical: "Lists are mutable and can be reassigned in place; tuples are strictly read-only.",
    example: "ammo = [\"Missile\"]\nammo[0] = \"Plasma Torpedo\"\nhardpoint = (1, 4)",
    task: "### YOUR MISSION\n\n1. Create list `ammo_bay = [\"Missile\"]`.\n2. Create tuple `hardpoint = (1, 4)`.\n3. Modify `ammo_bay[0] = \"Plasma Torpedo\"`.\n4. Print `ammo_bay` and `hardpoint`.",
    baseCode: "# TODO: Demonstrate list mutability and tuple immutability\n",
    hints: ["ammo_bay = [\"Missile\"]", "hardpoint = (1, 4)", "ammo_bay[0] = \"Plasma Torpedo\"", "print(ammo_bay)", "print(hardpoint)"],
    solution: "ammo_bay = [\"Missile\"]\nhardpoint = (1, 4)\nammo_bay[0] = \"Plasma Torpedo\"\nprint(ammo_bay)\nprint(hardpoint)",
    solutionRegex: [/ammo_bay\s*\[\s*0\s*\]\s*=\s*['"]Plasma Torpedo['"]/, /hardpoint\s*=\s*\(\s*1\s*,\s*4\s*\)/]
  },
  "list-slicing": {
    title: "Radar Grid Scan: List Slicing",
    headerPrefix: "RADAR_SWEEP",
    missionPrefix: "SLICE_SECTORS",
    intro: "# Focused Sector Scan: List Slicing\n\nSweep the immediate danger perimeter (indices 1 through 4 exclusive) across the Tokyo Bay radar sweep.",
    technical: "Slice notation `list[start:end]` slices elements up to but excluding `end`.",
    example: "danger_zone = radar_readings[1:4]\nprint(danger_zone)",
    task: "### YOUR MISSION\n\n1. Slice indices `1:4` from `radar_readings`.\n2. Store into `danger_zone`.\n3. Print `danger_zone`.",
    baseCode: "radar_readings = [\"Bay\", \"Harbor\", \"Bridge\", \"Airport\", \"Suburbs\", \"Mountains\"]\n# TODO: Slice indices 1:4 and print\n",
    hints: ["danger_zone = radar_readings[1:4]", "print(danger_zone)"],
    solution: "radar_readings = [\"Bay\", \"Harbor\", \"Bridge\", \"Airport\", \"Suburbs\", \"Mountains\"]\ndanger_zone = radar_readings[1:4]\nprint(danger_zone)",
    solutionRegex: [/danger_zone\s*=\s*radar_readings\s*\[\s*1\s*:\s*4\s*\]/, /print\s*\(\s*danger_zone\s*\)/]
  },
  "list-filtering": {
    title: "Seismic Filtering: List Comprehensions",
    headerPrefix: "SEISMIC_TELEMETRY",
    missionPrefix: "HIGH_MAGNITUDE",
    intro: "# High Richter Threat Detection: List Comprehensions\n\nFilter seismic sensor spikes greater than magnitude 5.0 to identify active Kaiju subterranean tunneling movements.",
    technical: "List comprehensions filter sequences cleanly: `[x for x in list if condition]`.",
    example: "severe_shocks = [s for s in seismic_shocks if s > 5.0]\nprint(severe_shocks)",
    task: "### YOUR MISSION\n\n1. Filter all values **greater than 5.0** from `seismic_shocks` using a list comprehension.\n2. Store in `severe_shocks`.\n3. Print `severe_shocks`.",
    baseCode: "seismic_shocks = [2.1, 6.4, 3.2, 7.8, 4.5, 8.2]\n# TODO: Filter shocks > 5.0\n",
    hints: ["severe_shocks = [s for s in seismic_shocks if s > 5.0]", "print(severe_shocks)"],
    solution: "seismic_shocks = [2.1, 6.4, 3.2, 7.8, 4.5, 8.2]\nsevere_shocks = [s for s in seismic_shocks if s > 5.0]\nprint(severe_shocks)",
    solutionRegex: [/severe_shocks\s*=\s*\[\s*s\s+for\s+s\s+in\s+seismic_shocks\s+if\s+s\s*>\s*5\.0\s*\]/, /print\s*\(\s*severe_shocks\s*\)/]
  },
  "list-comprehension-range": {
    title: "Thruster Calibration: Range Comprehension",
    headerPrefix: "PROPULSION_SYS",
    missionPrefix: "EVEN_THRUSTERS",
    intro: "# Thruster Array Test: Range Comprehension\n\nIgnite the even-numbered thruster nozzles from 2 to 10 to balance the flight stabilizers.",
    technical: "Combine `range()` and modulo conditions inside a list comprehension.",
    example: "active_nozzles = [n for n in range(2, 11) if n % 2 == 0]\nprint(active_nozzles)",
    task: "### YOUR MISSION\n\nGenerate all even numbers from 2 to 10 (inclusive) using a list comprehension into `active_nozzles` and print.",
    baseCode: "# TODO: Generate active_nozzles comprehension and print\n",
    hints: ["active_nozzles = [n for n in range(2, 11) if n % 2 == 0]", "print(active_nozzles)"],
    solution: "active_nozzles = [n for n in range(2, 11) if n % 2 == 0]\nprint(active_nozzles)",
    solutionRegex: [/active_nozzles\s*=\s*\[\s*n\s+for\s+n\s+in\s+range\s*\(\s*2\s*,\s*11\s*\)\s+if\s+n\s*%\s*2\s*==\s*0\s*\]/, /print\s*\(\s*active_nozzles\s*\)/]
  },
  "intro-input": {
    title: "Pilot Authorization: input()",
    headerPrefix: "COCKPIT_LOGIN",
    missionPrefix: "KEY_INPUT",
    intro: "# Biometric Pilot Check: input()\n\nBefore disengaging the hangar clamps, prompt the pilot to enter their access authorization key.",
    technical: "`input()` prompts the terminal user for text data and returns it as a string.",
    example: "pilot_key = input(\"Enter Pilot Key: \")\nprint(pilot_key)",
    task: "### YOUR MISSION\n\nPrompt with `\"Enter Pilot Key: \"` using `input()`, store in `pilot_key`, and `print(pilot_key)`.",
    baseCode: "# TODO: Prompt for pilot_key and print\n",
    hints: ["pilot_key = input(\"Enter Pilot Key: \")", "print(pilot_key)"],
    solution: "pilot_key = input(\"Enter Pilot Key: \")\nprint(pilot_key)",
    solutionRegex: [/pilot_key\s*=\s*input\s*\(\s*['"]Enter Pilot Key:\s*['"]\s*\)/, /print\s*\(\s*pilot_key\s*\)/]
  },
  "print-formatting": {
    title: "Telemetry Display: Print Formatting",
    headerPrefix: "HUD_TELEMETRY",
    missionPrefix: "BAR_FORMAT",
    intro: "# Cockpit HUD Display: Print Formatting\n\nDisplay telemetry parameters with clean separation bars using the `sep` argument inside `print()`.",
    technical: "`print()` allows custom separators through `sep=\"...\"`.",
    example: "print(\"REACTOR: 100%\", \"SHIELDS: 85%\", \"MISSILES: 24\", sep=\" | \")",
    task: "### YOUR MISSION\n\nPrint `\"REACTOR: 100%\"`, `\"SHIELDS: 85%\"`, and `\"MISSILES: 24\"` separated by `\" | \"`.",
    baseCode: "# TODO: Format HUD telemetry readout\n",
    hints: ["print(\"REACTOR: 100%\", \"SHIELDS: 85%\", \"MISSILES: 24\", sep=\" | \")"],
    solution: "print(\"REACTOR: 100%\", \"SHIELDS: 85%\", \"MISSILES: 24\", sep=\" | \")",
    solutionRegex: [/print\s*\(\s*['"]REACTOR: 100%['"]\s*,\s*['"]SHIELDS: 85%['"]\s*,\s*['"]MISSILES: 24['"]\s*,\s*sep\s*=\s*['"]\s*\|\s*['"]\s*\)/]
  },
  "input-fstrings-fun": {
    title: "Tactical Warning: f-Strings",
    headerPrefix: "THREAT_BROADCAST",
    missionPrefix: "BROADCAST_WARN",
    intro: "# Siren Broadcast: f-Strings\n\nConstruct emergency citywide alert broadcasts embedding live Kaiju category and sector telemetry using f-strings!",
    technical: "f-Strings (`f\"...\"`) embed live variables directly into formatted strings.",
    example: "category = 4\nsector = \"Tokyo Bay\"\nprint(f\"WARNING: Category {category} Kaiju breaching {sector}!\")",
    task: "### YOUR MISSION\n\nGiven `category = 4` and `sector = \"Tokyo Bay\"`, print `f\"WARNING: Category {category} Kaiju breaching {sector}!\"`.",
    baseCode: "category = 4\nsector = \"Tokyo Bay\"\n# TODO: Broadcast threat alert with f-string\n",
    hints: ["print(f\"WARNING: Category {category} Kaiju breaching {sector}!\")"],
    solution: "category = 4\nsector = \"Tokyo Bay\"\nprint(f\"WARNING: Category {category} Kaiju breaching {sector}!\")",
    solutionRegex: [/print\s*\(\s*f['"]WARNING:\s*Category\s*\{category\}\s*Kaiju\s*breaching\s*\{sector\}!['"]\s*\)/]
  },
  "control-indentation": {
    title: "Safety Interlock: Code Indentation",
    headerPrefix: "INTERLOCK_CIRCUIT",
    missionPrefix: "INDENT_ALIGN",
    intro: "# Blast Shield Interlock: Indentation\n\nMisaligned code blocks in the defense mainframe can short-circuit the pneumatic blast doors. Ensure blocks are properly indented by 4 spaces.",
    technical: "Indentation marks the scope of statements following a colon `:`.",
    example: "if True:\n    print(\"Blast doors sealed\")",
    task: "### YOUR MISSION\n\nIndent `print(\"Blast doors sealed\")` under `if True:` with 4 spaces.",
    baseCode: "if True:\nprint(\"Blast doors sealed\")\n",
    hints: ["Add 4 spaces before print(\"Blast doors sealed\")"],
    solution: "if True:\n    print(\"Blast doors sealed\")",
    solutionRegex: [/if\s+True\s*:\s*\n\s{4}print\s*\(\s*['"]Blast doors sealed['"]\s*\)/]
  },
  "control-if": {
    title: "Target Lock: Simple If",
    headerPrefix: "RADAR_LOCK_SYS",
    missionPrefix: "FIRE_PERMIT",
    intro: "# Cannon Interlock: Simple If\n\nWhen the targeting computer locks onto the Kaiju's thermal signature, activate the fire authorization flag.",
    technical: "The `if` condition executes its body only if the condition evaluates to True.",
    example: "if target_locked:\n    print(\"FIRE MAIN CANNON\")",
    task: "### YOUR MISSION\n\nIf `target_locked` is `True`, print `\"FIRE MAIN CANNON\"`.",
    baseCode: "target_locked = True\n# TODO: Check target_locked and print\n",
    hints: ["if target_locked:\n    print(\"FIRE MAIN CANNON\")"],
    solution: "target_locked = True\nif target_locked:\n    print(\"FIRE MAIN CANNON\")",
    solutionRegex: [/if\s+target_locked\s*:/, /print\s*\(\s*['"]FIRE MAIN CANNON['"]\s*\)/]
  },
  "control-else": {
    title: "Shield Critical: If/Else",
    headerPrefix: "ENERGY_BARRIER",
    missionPrefix: "SHIELD_ALERT",
    intro: "# Energy Barrier Status: If/Else\n\nCheck whether your mecha's forcefield can absorb another direct atomic blast or if the unit must fall back.",
    technical: "`else` provides a guaranteed fallback execution path when an `if` condition is False.",
    example: "if shield_level >= 50:\n    print(\"SHIELD ABSORB\")\nelse:\n    print(\"DEPLOY SMOKE RETREAT\")",
    task: "### YOUR MISSION\n\n1. If `shield_level >= 50`, print **`\"SHIELD ABSORB\"`**.\n2. Else, print **`\"DEPLOY SMOKE RETREAT\"`**.",
    baseCode: "shield_level = 25\n# TODO: Check shield status\n",
    hints: ["if shield_level >= 50:\n    print(\"SHIELD ABSORB\")\nelse:\n    print(\"DEPLOY SMOKE RETREAT\")"],
    solution: "shield_level = 25\nif shield_level >= 50:\n    print(\"SHIELD ABSORB\")\nelse:\n    print(\"DEPLOY SMOKE RETREAT\")",
    solutionRegex: [/if\s+shield_level\s*>=\s*50\s*:/, /else\s*:/, /print\s*\(\s*['"]SHIELD ABSORB['"]\s*\)/, /print\s*\(\s*['"]DEPLOY SMOKE RETREAT['"]\s*\)/]
  },
  "control-elif": {
    title: "Kaiju Classification: Elif Tiers",
    headerPrefix: "THREAT_INDEX",
    missionPrefix: "KAIJU_TIER",
    intro: "# Threat Severity Assessment: Elif Branching\n\nClassify incoming monsters by danger rating: Category 5 (Omega Event), Category 4 (Heavy Jaeger Deployment), or Category 1 (Minor Alert).",
    technical: "`elif` allows multi-way branching for sequential evaluation.",
    example: "if category >= 5:\n    print(\"OMEGA EVENT\")\nelif category >= 4:\n    print(\"HEAVY DEPLOYMENT\")\nelse:\n    print(\"MINOR ALERT\")",
    task: "### YOUR MISSION\n\n1. If `category >= 5`, print **`\"OMEGA EVENT\"`**.\n2. Elif `category >= 4`, print **`\"HEAVY DEPLOYMENT\"`**.\n3. Else, print **`\"MINOR ALERT\"`**.",
    baseCode: "category = 4\n# TODO: Evaluate threat level using if/elif/else\n",
    hints: ["if category >= 5:", "elif category >= 4:", "else:"],
    solution: "category = 4\nif category >= 5:\n    print(\"OMEGA EVENT\")\nelif category >= 4:\n    print(\"HEAVY DEPLOYMENT\")\nelse:\n    print(\"MINOR ALERT\")",
    solutionRegex: [/if\s+category\s*>=\s*5\s*:/, /elif\s+category\s*>=\s*4\s*:/, /else\s*:/, /print\s*\(\s*['"]OMEGA EVENT['"]\s*\)/, /print\s*\(\s*['"]HEAVY DEPLOYMENT['"]\s*\)/]
  },
  "control-meme-gen": {
    title: "Atomic Breath Warning: Decision Branch",
    headerPrefix: "ATOMIC_CHARGE",
    missionPrefix: "DEFLECT_CHOICE",
    intro: "# Dorsal Fin Blue Glow: Defensive Branching\n\nThe titan's dorsal plates are glowing electric neon blue! If beam charge is detected, raise the anti-radiation mirror.",
    technical: "Boolean branch logic evaluates threat indicators.",
    example: "if is_charging:\n    print(\"RAISE REFLECTOR SHIELD\")\nelse:\n    print(\"Continue bombardment\")",
    task: "### YOUR MISSION\n\nIf `is_charging`, print **`\"RAISE REFLECTOR SHIELD\"`**; else print **`\"Continue bombardment\"`**.",
    baseCode: "is_charging = True\n# TODO: Check is_charging\n",
    hints: ["if is_charging:\n    print(\"RAISE REFLECTOR SHIELD\")\nelse:\n    print(\"Continue bombardment\")"],
    solution: "is_charging = True\nif is_charging:\n    print(\"RAISE REFLECTOR SHIELD\")\nelse:\n    print(\"Continue bombardment\")",
    solutionRegex: [/if\s+is_charging\s*:/, /print\s*\(\s*['"]RAISE REFLECTOR SHIELD['"]\s*\)/]
  },
  "control-nickname-gen": {
    title: "Mecha Readiness: Status String",
    headerPrefix: "SYSTEM_DIAG",
    missionPrefix: "COMBAT_RATING",
    intro: "# Operational Readiness: Dynamic Status\n\nDesignate a mobile suit unit status string according to its current reactor stability percentage.",
    technical: "Conditionally define variables inside if-blocks before output.",
    example: "if reactor >= 90:\n    status = \"Combat Ready\"\nelse:\n    status = \"Hangar Maintenance\"\nprint(status)",
    task: "### YOUR MISSION\n\nIf `reactor >= 90`, set `status = \"Combat Ready\"`; else set `status = \"Hangar Maintenance\"`. Print `status`.",
    baseCode: "reactor = 95\n# TODO: Assign status and print\n",
    hints: ["if reactor >= 90:\n    status = \"Combat Ready\"\nelse:\n    status = \"Hangar Maintenance\"\nprint(status)"],
    solution: "reactor = 95\nif reactor >= 90:\n    status = \"Combat Ready\"\nelse:\n    status = \"Hangar Maintenance\"\nprint(status)",
    solutionRegex: [/if\s+reactor\s*>=\s*90/, /status\s*=\s*['"]Combat Ready['"]/, /print\s*\(\s*status\s*\)/]
  },
  "control-adventure": {
    title: "Evacuation Intercept: Nested Logic",
    headerPrefix: "DEFENSE_INTERCEPT",
    missionPrefix: "CIVILIAN_SAFETY",
    intro: "# Coastal Intercept: Nested Logic\n\nIf the Kaiju approaches within 5 kilometers of the shoreline AND shelters are not yet sealed, fire flare barrages to divert its path.",
    technical: "Nest `if` conditions to verify secondary prerequisites.",
    example: "if distance_km < 5:\n    if not shelters_sealed:\n        print(\"DIVERT KAIJU\")",
    task: "### YOUR MISSION\n\nIf `distance_km < 5`:\n    if `shelters_open`:\n        print **`\"DIVERT KAIJU\"`**.",
    baseCode: "distance_km = 3\nshelters_open = True\n# TODO: Nested conditional checks\n",
    hints: ["if distance_km < 5:\n    if shelters_open:\n        print(\"DIVERT KAIJU\")"],
    solution: "distance_km = 3\nshelters_open = True\nif distance_km < 5:\n    if shelters_open:\n        print(\"DIVERT KAIJU\")",
    solutionRegex: [/if\s+distance_km\s*<\s*5\s*:\s*\n\s+if\s+shelters_open\s*:/, /print\s*\(\s*['"]DIVERT KAIJU['"]\s*\)/]
  },
  "control-loops": {
    title: "Sonar Pings: For Loops",
    headerPrefix: "SONAR_BUOY",
    missionPrefix: "RADAR_SWEEP_LOOP",
    intro: "# Trench Sonar Sweep: For Loops\n\nTransmit 5 consecutive sonar pings across the Mariana Trench to locate the subterranean portal rift.",
    technical: "`for` loops iterate a specified number of times using `range(n)`.",
    example: "for i in range(5):\n    print(\"Sonar ping dispatched\")",
    task: "### YOUR MISSION\n\nUse a `for` loop to print `\"Sonar ping dispatched\"` exactly `5` times using `range(5)`.",
    baseCode: "# TODO: Repeat sonar ping 5 times\n",
    hints: ["for i in range(5):\n    print(\"Sonar ping dispatched\")"],
    solution: "for i in range(5):\n    print(\"Sonar ping dispatched\")",
    solutionRegex: [/for\s+\w+\s+in\s+range\s*\(\s*5\s*\)\s*:/, /print\s*\(\s*['"]Sonar ping dispatched['"]\s*\)/]
  },
  "loop-data-scan": {
    title: "Threat Scan: List Iteration",
    headerPrefix: "RADAR_MANIFEST",
    missionPrefix: "SCAN_CONTACTS",
    intro: "# Radar Contact Manifest: List Iteration\n\nInspect every active seismic contact detected along the Pacific Rim defense line and output their codenames.",
    technical: "Looping directly through a list assigns each element to the loop variable in turn.",
    example: "for monster in kaiju_list:\n    print(monster)",
    task: "### YOUR MISSION\n\nIterate over `kaiju_list` with a `for` loop and print each monster.",
    baseCode: "kaiju_list = [\"Leatherback\", \"Otachi\", \"Knifehead\", \"Raiju\"]\n# TODO: Loop through kaiju_list and print\n",
    hints: ["for monster in kaiju_list:\n    print(monster)"],
    solution: "kaiju_list = [\"Leatherback\", \"Otachi\", \"Knifehead\", \"Raiju\"]\nfor monster in kaiju_list:\n    print(monster)",
    solutionRegex: [/for\s+\w+\s+in\s+kaiju_list\s*:/, /print\s*\(\s*\w+\s*\)/]
  },
  "control-while": {
    title: "Kaiju Engagement: While Loop",
    headerPrefix: "TITAN_COMBAT",
    missionPrefix: "TITAN_HP_DRAIN",
    intro: "# Pacific Rim Showdown: While Loop\n\nFire rocket punches continuously until the Kaiju's vitality rating reaches 0!",
    technical: "`while` loops repeat until their test condition is met.",
    example: "while kaiju_hp > 0:\n    kaiju_hp -= 25\n    print(\"Rocket punch hit!\")",
    task: "### YOUR MISSION\n\nWhile `kaiju_hp > 0`, decrease `kaiju_hp` by `25` and print `\"Rocket punch hit!\"`.",
    baseCode: "kaiju_hp = 75\n# TODO: Loop until kaiju_hp is 0\n",
    hints: ["while kaiju_hp > 0:\n    kaiju_hp -= 25\n    print(\"Rocket punch hit!\")"],
    solution: "kaiju_hp = 75\nwhile kaiju_hp > 0:\n    kaiju_hp -= 25\n    print(\"Rocket punch hit!\")",
    solutionRegex: [/while\s+kaiju_hp\s*>\s*0\s*:/, /kaiju_hp\s*-=\s*25/, /print\s*\(\s*['"]Rocket punch hit!['"]\s*\)/]
  },
  "functions-intro": {
    title: "Weapons Command: def",
    headerPrefix: "WEAPONS_SYSTEM",
    missionPrefix: "FIRE_PROTOCOL",
    intro: "# Beam Rifle Initialization: Functions\n\nEncapsulate your mecha's plasma cannon firing sequence into a reusable Python function with `def`.",
    technical: "Functions bundle executable logic into reusable, named procedures.",
    example: "def fire_beam_cannon():\n    print(\"Beam Cannon Discharged!\")\n\nfire_beam_cannon()",
    task: "### YOUR MISSION\n\n1. Define function `fire_beam_cannon()` that prints `\"Beam Cannon Discharged!\"`.\n2. Call `fire_beam_cannon()`.",
    baseCode: "# TODO: Define fire_beam_cannon and call it\n",
    hints: ["def fire_beam_cannon():\n    print(\"Beam Cannon Discharged!\")\nfire_beam_cannon()"],
    solution: "def fire_beam_cannon():\n    print(\"Beam Cannon Discharged!\")\n\nfire_beam_cannon()",
    solutionRegex: [/def\s+fire_beam_cannon\s*\(\s*\)\s*:/, /print\s*\(\s*['"]Beam Cannon Discharged!['"]\s*\)/, /fire_beam_cannon\s*\(\s*\)/]
  },
  "functions-multi-params": {
    title: "Telemetry Lock: Parameters",
    headerPrefix: "RADAR_COORD_LOCK",
    missionPrefix: "CALCULATE_VECTOR",
    intro: "# Dual Axis Aiming: Parameters\n\nTransmit azimuth and elevation angles into the targeting computer to lock onto airborne monsters.",
    technical: "Functions accept multiple comma-separated parameters.",
    example: "def target_coords(azimuth, elevation):\n    print(f\"Target locked at Azimuth {azimuth}, Elev {elevation}\")",
    task: "### YOUR MISSION\n\nDefine `target_coords(azimuth, elevation)` that prints `f\"Target locked at Azimuth {azimuth}, Elev {elevation}\"`. Call it with `120` and `45`.",
    baseCode: "# TODO: Define target_coords and call with 120, 45\n",
    hints: ["def target_coords(azimuth, elevation):\n    print(f\"Target locked at Azimuth {azimuth}, Elev {elevation}\")\ntarget_coords(120, 45)"],
    solution: "def target_coords(azimuth, elevation):\n    print(f\"Target locked at Azimuth {azimuth}, Elev {elevation}\")\n\ntarget_coords(120, 45)",
    solutionRegex: [/def\s+target_coords\s*\(\s*azimuth\s*,\s*elevation\s*\)\s*:/, /target_coords\s*\(\s*120\s*,\s*45\s*\)/]
  },
  "functions-return": {
    title: "Shield Calculation: return",
    headerPrefix: "POWER_GRID_COMPUTE",
    missionPrefix: "CALC_OUTPUT",
    intro: "# Computing Net Forcefield: return\n\nCalculate the net forcefield resilience and return the resulting integer back to the flight computer.",
    technical: "`return` sends computed values back to the calling code.",
    example: "def calculate_shield(base, boost):\n    return base + boost",
    task: "### YOUR MISSION\n\n1. Define `calc_shield(base, boost)` that returns `base + boost`.\n2. Call `calc_shield(100, 50)` and print the result.",
    baseCode: "# TODO: Define calc_shield and print result\n",
    hints: ["def calc_shield(base, boost):\n    return base + boost\nprint(calc_shield(100, 50))"],
    solution: "def calc_shield(base, boost):\n    return base + boost\n\nprint(calc_shield(100, 50))",
    solutionRegex: [/def\s+calc_shield\s*\(\s*base\s*,\s*boost\s*\)\s*:/, /return\s+base\s*\+\s*boost/, /print\s*\(\s*calc_shield\s*\(\s*100\s*,\s*50\s*\)\s*\)/]
  },
  "oop-intro": {
    title: "Mecha Chassis: Classes",
    headerPrefix: "JAEGER_BLUEPRINT",
    missionPrefix: "CLASS_CHASSIS",
    intro: "# Giant Robot Blueprint: Classes\n\nEvery mechanized defender built in the Tokyo-3 hangars shares foundational architecture (model, reactor, armor). Model this blueprint as a Python **Class**.",
    technical: "Classes define object templates with bundled data and methods.",
    task: "### YOUR MISSION\n\nDefine an empty class named `MechaUnit`. Use `pass` inside.",
    baseCode: "# TODO: Define MechaUnit class\n",
    hints: ["class MechaUnit:\n    pass"],
    solution: "class MechaUnit:\n    pass",
    solutionRegex: [/class\s+MechaUnit\s*:/, /pass/]
  },
  "oop-init": {
    title: "Chassis Assembly: __init__",
    headerPrefix: "HANGAR_CONSTRUCTOR",
    missionPrefix: "INIT_MECHA",
    intro: "# Assembling Chassis: Constructor\n\nWhen a new robot is deployed from the hangar lift, register its model designation using `__init__`.",
    technical: "`__init__` initializes newly instantiated objects with attributes.",
    task: "### YOUR MISSION\n\nInside `MechaUnit`, define `__init__(self, model)` and set `self.model = model`.",
    baseCode: "class MechaUnit:\n    # TODO: Add __init__ constructor\n",
    hints: ["def __init__(self, model):\n    self.model = model"],
    solution: "class MechaUnit:\n    def __init__(self, model):\n        self.model = model",
    solutionRegex: [/def\s+__init__\s*\(\s*self\s*,\s*model\s*\)\s*:/, /self\.model\s*=\s*model/]
  },
  "oop-methods": {
    title: "Weapons Engagement: Class Methods",
    headerPrefix: "WEAPONS_METHOD",
    missionPrefix: "DEPLOY_METHOD",
    intro: "# Weapon Systems: Methods\n\nA robot needs offensive actions! Add an attack method to the class blueprint.",
    task: "### YOUR MISSION\n\nAdd a method `fire_missiles(self)` to `MechaUnit` that prints `\"Missiles away!\"`.",
    baseCode: "class MechaUnit:\n    def __init__(self, model):\n        self.model = model\n    # TODO: Define fire_missiles method\n",
    hints: ["def fire_missiles(self):\n    print(\"Missiles away!\")"],
    solution: "class MechaUnit:\n    def __init__(self, model):\n        self.model = model\n    def fire_missiles(self):\n        print(\"Missiles away!\")",
    solutionRegex: [/def\s+fire_missiles\s*\(\s*self\s*\)\s*:/, /print\s*\(\s*['"]Missiles away!['"]\s*\)/]
  },
  "oop-state": {
    title: "Hull Armor: Object State",
    headerPrefix: "ARMOR_TELEMETRY",
    missionPrefix: "HULL_INTEGRITY",
    intro: "# Hull Integrity: Object State\n\nEach deployed Jaeger monitors its own armor percentage independently as enemy hits land.",
    task: "### YOUR MISSION\n\n1. In `MechaUnit.__init__`, set `self.armor = 100`.\n2. Add method `take_damage(self)` that sets `self.armor = 0`.",
    baseCode: "class MechaUnit:\n    def __init__(self, model):\n        self.model = model\n        # TODO: Add self.armor = 100\n    # TODO: Add take_damage method\n",
    hints: ["self.armor = 100", "def take_damage(self):\n    self.armor = 0"],
    solution: "class MechaUnit:\n    def __init__(self, model):\n        self.model = model\n        self.armor = 100\n    def take_damage(self):\n        self.armor = 0",
    solutionRegex: [/self\.armor\s*=\s*100/, /def\s+take_damage\s*\(\s*self\s*\)\s*:/, /self\.armor\s*=\s*0/]
  },
  "oop-interaction": {
    title: "Squadron Comms: Object Interaction",
    headerPrefix: "MECHA_LINK",
    missionPrefix: "SQUAD_COMM",
    intro: "# Tactical Drift Link: Object Interaction\n\nIn neural drift combat, mecha units communicate directly with wingmen machines across the defense sector.",
    task: "### YOUR MISSION\n\nAdd method `drift_link(self, other)` to `MechaUnit` that prints `f\"{self.model} drift linked with {other.model}!\"`.",
    baseCode: "class MechaUnit:\n    def __init__(self, model):\n        self.model = model\n    # TODO: Add drift_link method\n",
    hints: ["def drift_link(self, other):\n    print(f\"{self.model} drift linked with {other.model}!\")"],
    solution: "class MechaUnit:\n    def __init__(self, model):\n        self.model = model\n    def drift_link(self, other):\n        print(f\"{self.model} drift linked with {other.model}!\")",
    solutionRegex: [/def\s+drift_link\s*\(\s*self\s*,\s*other\s*\)\s*:/, /f['"].*\{self\.model\}.*drift linked with.*\{other\.model\}!['"]/]
  },
  "oop-inheritance": {
    title: "Heavy Artillery: Inheritance",
    headerPrefix: "HEAVY_CHASSIS",
    missionPrefix: "SUBCLASS_HEAVY",
    intro: "# Heavy Artillery Unit: Inheritance\n\nAn `ArtilleryMecha` inherits all base `MechaUnit` properties while gaining access to siege cannon barrages.",
    task: "### YOUR MISSION\n\nCreate a subclass `ArtilleryMecha(MechaUnit)` with method `siege_barrage(self)` that prints `\"Siege barrage fired!\"`.",
    baseCode: "class MechaUnit:\n    def __init__(self, model):\n        self.model = model\n# TODO: Define ArtilleryMecha inheriting from MechaUnit\n",
    hints: ["class ArtilleryMecha(MechaUnit):\n    def siege_barrage(self):\n        print(\"Siege barrage fired!\")"],
    solution: "class MechaUnit:\n    def __init__(self, model):\n        self.model = model\n\nclass ArtilleryMecha(MechaUnit):\n    def siege_barrage(self):\n        print(\"Siege barrage fired!\")",
    solutionRegex: [/class\s+ArtilleryMecha\s*\(\s*MechaUnit\s*\)\s*:/, /def\s+siege_barrage\s*\(\s*self\s*\)\s*:/, /print\s*\(\s*['"]Siege barrage fired!['"]\s*\)/]
  },
  "oop-str": {
    title: "Telemetry Display: __str__",
    headerPrefix: "HUD_STR_READOUT",
    missionPrefix: "STR_OUTPUT",
    intro: "# Sensor Readout: __str__\n\nFormat the visual cockpit printout of your machine by implementing the `__str__` dunder method.",
    task: "### YOUR MISSION\n\nIn `MechaUnit`, implement `__str__(self)` returning `f\"Mecha: {self.model}\"`.",
    baseCode: "class MechaUnit:\n    def __init__(self, model):\n        self.model = model\n    # TODO: Add __str__ method\n",
    hints: ["def __str__(self):\n    return f\"Mecha: {self.model}\""],
    solution: "class MechaUnit:\n    def __init__(self, model):\n        self.model = model\n    def __str__(self):\n        return f\"Mecha: {self.model}\"",
    solutionRegex: [/def\s+__str__\s*\(\s*self\s*\)\s*:/, /return\s+f['"]Mecha:\s*\{self\.model\}['"]/]
  },
  "oop-class-vars": {
    title: "Defense Fleet: Class Variables",
    headerPrefix: "FLEET_COMMAND",
    missionPrefix: "SHARED_FLEET",
    intro: "# Fleet Command: Class Variables\n\nEvery mecha unit has a distinct pilot and model number, but all units report to the same defense command.",
    task: "### YOUR MISSION\n\n1. Define class variable `command = \"Tokyo-3 Defense\"` inside `MechaUnit`.\n2. Print `MechaUnit.command`.",
    baseCode: "class MechaUnit:\n    # TODO: Add command = \"Tokyo-3 Defense\"\n    pass\n# TODO: Print MechaUnit.command\n",
    hints: ["command = \"Tokyo-3 Defense\"", "print(MechaUnit.command)"],
    solution: "class MechaUnit:\n    command = \"Tokyo-3 Defense\"\n\nprint(MechaUnit.command)",
    solutionRegex: [/command\s*=\s*['"]Tokyo-3 Defense['"]/, /print\s*\(\s*MechaUnit\.command\s*\)/]
  }
};
