export const MINECRAFT_THEME: any = {
  "intro-print": {
    title: "World Spawn: Hello Minecraft",
    headerPrefix: "WORLD_SPAWN",
    missionPrefix: "CRAFT_BOOT",
    intro: "# Awakening in the Overworld: print()\n\nWelcome to Minecraft! You wake up on a grassy shore surrounded by trees and mountains. Send your first beacon signal into the blocky world.",
    technical: "In Python, the `print()` function displays whatever text or numbers you place inside its parentheses on the screen.",
    example: "print(\"Welcome to Minecraft!\")",
    task: "### YOUR MISSION\n\nUse `print()` to display: `\"Welcome to Minecraft!\"`",
    baseCode: "# TODO: Broadcast your arrival in Minecraft\n",
    hints: ["Type print(\"Welcome to Minecraft!\")","Keep the string enclosed in double quotes"],
    solution: "print(\"Welcome to Minecraft!\")",
    solutionRegex: [/print\s*\(\s*['"]Welcome to Minecraft!['"]\s*\)/]
  },
  "naming-conventions": {
    title: "Inventory Standards: Lowercase Names",
    headerPrefix: "CRAFTING_TABLE",
    missionPrefix: "ITEM_INDEX",
    intro: "# Storage Standards: Lowercase Names\n\nMinecraft's item data system is case-sensitive! Store your diamond stash count using standard lowercase `snake_case` variable names.",
    technical: "Python variables must start with a lowercase letter or underscore, with words separated by underscores `_`.",
    example: "diamond_count = 64\nprint(diamond_count)",
    task: "### YOUR MISSION\n\nCreate a lowercase variable named `diamond_count` and assign its value to `64` (a full stack of diamonds). Print it with `print()` to confirm. Everything must be lowercase!",
    baseCode: "# TODO: Store diamond_count variable and print it\n",
    hints: ["Write diamond_count = 64","On the next line, write print(diamond_count)"],
    solution: "diamond_count = 64\nprint(diamond_count)",
    solutionRegex: [/diamond_count\s*=\s*64/, /print\s*\(\s*diamond_count\s*\)/]
  },
  "intro-comments": {
    title: "Mining Logs: Comments",
    headerPrefix: "DEEP_CAVERN",
    missionPrefix: "MINING_LOG",
    intro: "# Underground Expeditions: Comments\n\nWhen excavating deep underground caverns near bedrock, leave mining markers so you don't get lost in labyrinth caves.",
    technical: "Lines starting with `#` are comments. Python ignores them, making them perfect for survival notes.",
    example: "# Mining for ancient debris\nprint(\"Digging down...\")",
    task: "### YOUR MISSION\n\nWrite a comment `# Mining for ancient debris` and then `print(\"Digging down...\")`",
    baseCode: "# TODO: Add mining comment and dig downwards\n",
    hints: ["Line 1: # Mining for ancient debris","Line 2: print(\"Digging down...\")"],
    solution: "# Mining for ancient debris\nprint(\"Digging down...\")",
    solutionRegex: [/#.*Mining for ancient debris/, /print\s*\(\s*['"]Digging down\.\.\.['"]\s*\)/]
  },
  "comments-inline": {
    title: "Redstone Diagnostics: Inline Comments",
    headerPrefix: "REDSTONE_WIRE",
    missionPrefix: "POWER_NOTE",
    intro: "# Redstone Circuits: Inline Comments\n\nDocument redstone power levels right next to your wire connections without interfering with circuit execution.",
    technical: "Inline comments appear on the same line after executable code, separated by `#`.",
    example: "redstone_power = 15 # Maximum signal strength",
    task: "### YOUR MISSION\n\nInitialise `redstone_power` to `15`. On the same line, add an inline comment `# Maximum signal strength`.",
    baseCode: "# TODO: Initialize variable with inline comment\n",
    hints: ["Write redstone_power = 15 followed by # Maximum signal strength on the same line."],
    solution: "redstone_power = 15 # Maximum signal strength",
    solutionRegex: [/redstone_power\s*=\s*15/, /#.*Maximum signal strength/]
  },
  "intro-vars": {
    title: "Smelting Supplies: Variables",
    headerPrefix: "FURNACE_SLOTS",
    missionPrefix: "RESOURCE_SLOT",
    intro: "# Resource Vault: Variables\n\n**What is a Variable?** Think of a **variable** as an **inventory chest slot**! You give the slot a name (like `iron_ingots`), store quantities of ore or food inside, and retrieve them whenever you need to craft.",
    technical: "Variables store values that can be referenced and updated throughout your program.",
    example: "iron_ingots = 32\ncoal_lumps = 64",
    task: "### YOUR MISSION\n\nCreate `iron_ingots` set to `32` and `coal_lumps` set to `64`.",
    baseCode: "# TODO: Record iron ingots and coal lumps\n",
    hints: ["iron_ingots = 32","coal_lumps = 64"],
    solution: "iron_ingots = 32\ncoal_lumps = 64",
    solutionRegex: [/iron_ingots\s*=\s*32/, /coal_lumps\s*=\s*64/]
  },
  "vars-reassignment": {
    title: "Tool Upgrades: Reassignment",
    headerPrefix: "ANVIL_UPGRADE",
    missionPrefix: "TOOL_TIER",
    intro: "# Anvil Station: Reassignment\n\nYou combined your pickaxe with netherite ingots at the smithing table! Update your `pickaxe_tier` variable to record your upgraded gear.",
    technical: "When you assign a new value to an existing variable name, Python throws away the old value and replaces it with the new one. This is called **reassignment**.",
    example: "pickaxe_tier = 1.0\npickaxe_tier = 2.1\nprint(pickaxe_tier)",
    task: "### YOUR MISSION\n\nInitialise `pickaxe_tier` as `1.0`. Then update `pickaxe_tier` to `2.1`. Print it.",
    baseCode: "pickaxe_tier = 1.0\n# TODO: Upgrade to 2.1 and print\n",
    hints: ["Assign pickaxe_tier = 2.1 on the next line.","Print it with print(pickaxe_tier)."],
    solution: "pickaxe_tier = 1.0\npickaxe_tier = 2.1\nprint(pickaxe_tier)",
    solutionRegex: [/pickaxe_tier\s*=\s*1\.0/, /pickaxe_tier\s*=\s*2\.1/, /print\s*\(\s*pickaxe_tier\s*\)/]
  },
  "vars-placeholder": {
    title: "Chest Buffer: Empty Placeholders",
    headerPrefix: "CHEST_INSPECTOR",
    missionPrefix: "BLOCK_RECEIVE",
    intro: "# Double Chest: Empty Placeholders\n\nBefore opening a hopper transmission, allocate an empty string buffer to hold incoming mined blocks from the quarry.",
    technical: "For strings, an \"empty\" value is represented by two quotes with nothing inside, such as `\"\"` or `''`.\n\n### Overwriting with Input:\nBy first initializing `block_data = \"\"` as a placeholder, we allocate space in memory. Then, running `block_data = input(\"...\")` overwrites that placeholder with whatever you enter, updating the empty string dynamically!",
    example: "block_data = \"\"\nblock_data = input(\"Enter mined block: \")\nprint(\"Storing in chest: \" + block_data)",
    task: "### YOUR MISSION\n\n1. Initialize `block_data` as an empty string `\"\"` or `''`.\n2. Use `input(\"Enter mined block: \")` to populate it.\n3. Print `\"Storing in chest: \" + block_data`.",
    baseCode: "# TODO: Prepare buffer and log mined block\n",
    hints: ["Use block_data = \"\" to prepare the buffer.","Use block_data = input(\"Enter mined block: \") to capture the block.","Print \"Storing in chest: \" concatenated with block_data."],
    solution: "block_data = \"\"\nblock_data = input(\"Enter mined block: \")\nprint(\"Storing in chest: \" + block_data)",
    solutionRegex: [/block_data\s*=\s*['"]['"]/, /input/, /print/]
  },
  "vars-multi": {
    title: "Precious Minerals: Multiple Assignment",
    headerPrefix: "TREASURE_VAULT",
    missionPrefix: "MULTI_INGOTS",
    intro: "# Desert Temple Vault: Multiple Assignment\n\nYou discovered a hidden chest containing both gold and emeralds! Python allows you to unpack multiple mineral values simultaneously on a single line.",
    technical: "Multiple assignment pairs comma-separated names with comma-separated values: `a, b = 1, 2`.",
    example: "gold_ingots, emeralds = 16, 24",
    task: "### YOUR MISSION\n\nAssign `gold_ingots` set to `16` and `emeralds` set to `24` in one line.",
    baseCode: "# TODO: Assign gold_ingots and emeralds in one line\n",
    hints: ["gold_ingots, emeralds = 16, 24"],
    solution: "gold_ingots, emeralds = 16, 24",
    solutionRegex: [/gold_ingots\s*,\s*emeralds\s*=\s*16\s*,\s*24/]
  },
  "data-strings": {
    title: "Equipped Gear: Strings",
    headerPrefix: "HOTBAR_STATUS",
    missionPrefix: "WEAPON_NAME",
    intro: "# Main Hand Item: Strings\n\nSteve is ready to brave the darkness. Store the name of your primary weapon in a string variable.",
    technical: "Strings represent text enclosed in single or double quotes.",
    example: "active_tool = \"Diamond Pickaxe\"\nprint(active_tool)",
    task: "### YOUR MISSION\n\nCreate a variable `active_tool` set to `\"Diamond Pickaxe\"`. Print it.",
    baseCode: "# TODO: Set active_tool and print\n",
    hints: ["active_tool = \"Diamond Pickaxe\"","print(active_tool)"],
    solution: "active_tool = \"Diamond Pickaxe\"\nprint(active_tool)",
    solutionRegex: [/active_tool\s*=\s*['"]Diamond Pickaxe['"]/, /print\s*\(\s*active_tool\s*\)/]
  },
  "data-booleans": {
    title: "World Status: Booleans",
    headerPrefix: "SURVIVAL_CLOCK",
    missionPrefix: "DAYLIGHT_CHECK",
    intro: "# Survival State: Booleans\n\nIn Minecraft, boolean flags check whether the sun is still up or whether an explosive Creeper is hissing behind you.",
    technical: "Booleans can only be `True` or `False`. Always capitalize the first letter.",
    example: "is_daytime = True\ncreeper_near = False",
    task: "### YOUR MISSION\n\nSet `is_daytime` to `True` and `creeper_near` to `False`.",
    baseCode: "# TODO: Set daytime and creeper flags\n",
    hints: ["is_daytime = True","creeper_near = False"],
    solution: "is_daytime = True\ncreeper_near = False",
    solutionRegex: [/is_daytime\s*=\s*True/, /creeper_near\s*=\s*False/]
  },
  "intro-math": {
    title: "Mining Supplies: Addition",
    headerPrefix: "SUPPLY_CRATE",
    missionPrefix: "TORCH_TALLY",
    intro: "# Mining Gear: Addition\n\nBefore embarking into deep underground caves, calculate your total mining supplies by adding torches and coal blocks together.",
    technical: "The `+` operator adds numerical values together.",
    example: "total_mining_gear = torches_crafted + coal_blocks\nprint(total_mining_gear)",
    task: "### YOUR MISSION\n\nCreate `torches_crafted` as `64` and `coal_blocks` as `16`. Store the sum in `total_mining_gear` and print it.",
    baseCode: "# TODO: Calculate total mining supplies\n",
    hints: ["torches_crafted = 64","coal_blocks = 16","total_mining_gear = torches_crafted + coal_blocks","print(total_mining_gear)"],
    solution: "torches_crafted = 64\ncoal_blocks = 16\ntotal_mining_gear = torches_crafted + coal_blocks\nprint(total_mining_gear)",
    solutionRegex: [/total_mining_gear\s*=\s*torches_crafted\s*\+\s*coal_blocks/, /print\s*\(\s*total_mining_gear\s*\)/]
  },
  "math-complex": {
    title: "Blast Furnace: Complex Math",
    headerPrefix: "BLAST_FURNACE",
    missionPrefix: "REFINED_ORE",
    intro: "# Smelting Efficiency: Complex Math\n\nCalculate refined metal bars produced by factoring fuel costs and furnace yield percentages.",
    technical: "Operations inside parentheses `()` evaluate first before multiplication `*`.",
    example: "refined_bars = (raw_iron + smelt_cost) * 0.8\nprint(refined_bars)",
    task: "### YOUR MISSION\n\n1. Set `raw_iron` as `80`.\n2. Set `smelt_cost` as `-10`.\n3. Calculate `(raw_iron + smelt_cost) * 0.8` and store in `refined_bars`.\n4. Print `refined_bars`.",
    baseCode: "# TODO: Compute refined_bars\n",
    hints: ["raw_iron = 80","smelt_cost = -10","refined_bars = (raw_iron + smelt_cost) * 0.8","print(refined_bars)"],
    solution: "raw_iron = 80\nsmelt_cost = -10\nrefined_bars = (raw_iron + smelt_cost) * 0.8\nprint(refined_bars)",
    solutionRegex: [/refined_bars\s*=\s*\(\s*raw_iron\s*\+\s*smelt_cost\s*\)\s*\*\s*0\.8/, /print\s*\(\s*refined_bars\s*\)/]
  },
  "intro-lists": {
    title: "Hotbar Slots: Lists",
    headerPrefix: "PLAYER_HOTBAR",
    missionPrefix: "SLOT_ROSTER",
    intro: "# Player Hotbar: Lists\n\nEvery crafter carries essential quick-access tools on their 9-slot hotbar belt. Represent your active equipment using a Python list.",
    technical: "Lists are ordered, mutable sequences surrounded by brackets `[...]`.",
    example: "hotbar = [\"Diamond Sword\", \"Pickaxe\", \"Golden Apple\"]\nprint(hotbar)",
    task: "### YOUR MISSION\n\nInitialise your `hotbar` list with \"Diamond Sword\", \"Pickaxe\", and \"Golden Apple\". Print the hotbar list.",
    baseCode: "# TODO: Initialize hotbar list and print\n",
    hints: ["hotbar = [\"Diamond Sword\", \"Pickaxe\", \"Golden Apple\"]","print(hotbar)"],
    solution: "hotbar = [\"Diamond Sword\", \"Pickaxe\", \"Golden Apple\"]\nprint(hotbar)",
    solutionRegex: [/hotbar\s*=\s*\[/, /print\s*\(\s*hotbar\s*\)/]
  },
  "list-indexing": {
    title: "Hotbar Keys: List Indexing",
    headerPrefix: "HOTBAR_INDEX",
    missionPrefix: "KEY_SELECT",
    intro: "# Hotbar Hotkeys: List Indexing\n\nIn Minecraft, hotbar slot 1 corresponds to Python index `0`, while slot 3 is at index `2`.",
    technical: "Index `0` accesses the first item; index `2` accesses the third item.",
    example: "slot_one = hotbar[0]\nslot_three = hotbar[2]",
    task: "### YOUR MISSION\n\n1. Retrieve the first item (index 0) in the `hotbar` list and store in `slot_one`.\n2. Retrieve the third item (index 2) in the `hotbar` list and store in `slot_three`.\n3. Print `slot_one` and `slot_three`.",
    baseCode: "hotbar = [\"Diamond Sword\", \"Pickaxe\", \"Golden Apple\"]\n# TODO: Extract indices 0 and 2 and print\n",
    hints: ["slot_one = hotbar[0]","slot_three = hotbar[2]","print(slot_one)","print(slot_three)"],
    solution: "slot_one = hotbar[0]\nslot_three = hotbar[2]\nprint(slot_one)\nprint(slot_three)",
    solutionRegex: [/slot_one\s*=\s*hotbar\s*\[\s*0\s*\]/, /slot_three\s*=\s*hotbar\s*\[\s*2\s*\]/]
  },
  "list-append": {
    title: "Equipping Gear: .append()",
    headerPrefix: "HOTBAR_EQUIP",
    missionPrefix: "YOUR TASK",
    intro: "# Adding to Hotbar: .append()\n\nYou scooped up a water bucket to safely navigate lava lakes! Use `.append()` to add it directly to your hotbar.",
    technical: "The `.append()` method mutates lists in-place, adding an element to the end.",
    example: "hotbar.append(\"Water Bucket\")\nprint(hotbar)",
    task: "### YOUR MISSION\n\n1. Append \"Water Bucket\" to the `hotbar` list.\n2. Print the final `hotbar` list to confirm.",
    baseCode: "hotbar = [\"Diamond Sword\", \"Pickaxe\", \"Golden Apple\"]\n# TODO: Append value and print\n",
    hints: ["hotbar.append(\"Water Bucket\")","print(hotbar)"],
    solution: "hotbar.append(\"Water Bucket\")\nprint(hotbar)",
    solutionRegex: [/hotbar\.\s*append\s*\(\s*['"]Water Bucket['"]\s*\)/, /print\s*\(\s*hotbar\s*\)/]
  },
  "list-pop": {
    title: "Cleaning Chests: .pop()",
    headerPrefix: "CHEST_PURGE",
    missionPrefix: "YOUR TASK",
    intro: "# Sorting Chest Storage: .pop()\n\nClear out junk blocks from your storage chest to make room for rare ores! Use `.pop()` to remove and store the discarded block.",
    technical: "Calling `.pop()` removes and returns the last element from a list.",
    example: "discarded_junk = chest_storage.pop()\nprint(discarded_junk)",
    task: "### YOUR MISSION\n\n1. Pop the last item from the `chest_storage` list and store it inside a variable named `discarded_junk`.\n2. Print `discarded_junk` to output the removed block.",
    baseCode: "chest_storage = [\"Cobblestone\", \"Dirt\", \"Gravel\"]\n# TODO: Pop last element and print\n",
    hints: ["discarded_junk = chest_storage.pop()","print(discarded_junk)"],
    solution: "discarded_junk = chest_storage.pop()\nprint(discarded_junk)",
    solutionRegex: [/discarded_junk\s*=\s*chest_storage\.\s*pop\s*\(\s*\)/, /print\s*\(\s*discarded_junk\s*\)/]
  },
  "intro-tuples": {
    title: "World Spawnpoint: Tuples",
    headerPrefix: "SPAWN_COORDS",
    missionPrefix: "YOUR TASK",
    intro: "# Permanent Compass Coordinates: Tuples\n\nWorld spawn coordinates must remain constant so your compass always points back home. Tuples provide immutable collections.",
    technical: "Tuples use parentheses `()` and cannot be modified once created.",
    example: "spawn_coordinates = (\"Overworld Hub\", 1024)\nprint(spawn_coordinates)",
    task: "### YOUR MISSION\n\n1. Initialize a tuple named `spawn_coordinates` containing \"Overworld Hub\" and the number `1024`.\n2. Print the `spawn_coordinates` tuple.",
    baseCode: "# TODO: Initialize the coordinate tuple and print\n",
    hints: ["spawn_coordinates = (\"Overworld Hub\", 1024)","print(spawn_coordinates)"],
    solution: "spawn_coordinates = (\"Overworld Hub\", 1024)\nprint(spawn_coordinates)",
    solutionRegex: [/spawn_coordinates\s*=\s*\(\s*['"]Overworld Hub['"]\s*,\s*1024\s*\)/, /print\s*\(\s*spawn_coordinates\s*\)/]
  },
  "intro-tuples-immutability": {
    title: "Inventory vs Bedrock: Immutability",
    headerPrefix: "INVENTORY_STASH",
    missionPrefix: "YOUR TASK",
    intro: "# Changing Inventory vs Unbreakable Bedrock: Immutability\n\nBackpack items are mutable and can be crafted or swapped, but bedrock layer coordinates can never be broken or moved!",
    technical: "Lists can be updated in-place (`list[0] = new_val`), while tuples are read-only and immutable.",
    example: "backpack_inventory = [\"Wood Planks\"]\nbackpack_inventory[0] = \"Obsidian\"",
    task: "### YOUR MISSION\n\n1. Create a list named `backpack_inventory` containing the single string \"Wood Planks\"\n2. Create a tuple named `bedrock_coords` containing the numbers `64` and `0`.\n3. Rewrite `backpack_inventory[0]` to be \"Obsidian\"\n4. Print both `backpack_inventory` and `bedrock_coords`.",
    baseCode: "# TODO: Demonstrate mutable list and immutable tuple\n",
    hints: ["backpack_inventory = [\"Wood Planks\"]","bedrock_coords = (64, 0)","backpack_inventory[0] = \"Obsidian\"","print(backpack_inventory)","print(bedrock_coords)"],
    solution: "backpack_inventory = [\"Wood Planks\"]\nbedrock_coords = (64, 0)\nbackpack_inventory[0] = \"Obsidian\"\nprint(backpack_inventory)\nprint(bedrock_coords)",
    solutionRegex: [/backpack_inventory\s*\[\s*0\s*\]\s*=\s*['"]Obsidian['"]/, /bedrock_coords\s*=\s*\(\s*64\s*,\s*0\s*\)/]
  },
  "list-slicing": {
    title: "Mining Haul: List Slicing",
    headerPrefix: "MINING_HAUL_SLICE",
    missionPrefix: "YOUR TASK",
    intro: "# Mining Haul: List Slicing\n\nAfter a long subterranean excavation, slice the most valuable middle section of your mining haul to bring back to base.",
    technical: "Slice syntax `list[start:end]` extracts elements from `start` up to but not including `end`.",
    example: "essential_ores = mining_haul[1:4]\nprint(essential_ores)",
    task: "### YOUR MISSION\n\n1. Slice index `1` to index `4` (exclusive) from the `mining_haul` list.\n2. Store this result in a new variable named `essential_ores`.\n3. Print the resulting slice `essential_ores`.",
    baseCode: "mining_haul = [\"coal\", \"iron\", \"gold\", \"diamond\", \"redstone\", \"emerald\"]\n# TODO: Slice indices 1:4 and print\n",
    hints: ["essential_ores = mining_haul[1:4]","print(essential_ores)"],
    solution: "essential_ores = mining_haul[1:4]\nprint(essential_ores)",
    solutionRegex: [/essential_ores\s*=\s*mining_haul\s*\[\s*1\s*:\s*4\s*\]/, /print\s*\(\s*essential_ores\s*\)/]
  },
  "list-filtering": {
    title: "Tool Durability: List Comprehensions",
    headerPrefix: "DURABILITY_CHECK",
    missionPrefix: "YOUR TASK",
    intro: "# Equipment Durability: List Comprehensions\n\nFilter all sturdy tools in your chest with durability ratings greater than 50 before setting out on a cave journey!",
    technical: "List comprehensions construct filtered lists cleanly: `[x for x in list if condition]`.",
    example: "high_durability = [d for d in tool_durabilities if d > 50]\nprint(high_durability)",
    task: "### YOUR MISSION\n\n1. Use a list comprehension to filter all values **greater than 50** from `tool_durabilities`.\n2. Store the result in a variable named `high_durability`.\n3. Print `high_durability`.",
    baseCode: "tool_durabilities = [15, 65, 30, 92, 45, 88]\n# TODO: Comprehend and filter values > 50\n",
    hints: ["high_durability = [d for d in tool_durabilities if d > 50]","print(high_durability)"],
    solution: "high_durability = [d for d in tool_durabilities if d > 50]\nprint(high_durability)",
    solutionRegex: [/high_durability\s*=\s*\[\s*d\s+for\s+d\s+in\s+tool_durabilities\s+if\s+d\s*>\s*50\s*\]/, /print\s*\(\s*high_durability\s*\)/]
  },
  "list-comprehension-range": {
    title: "Redstone Clock: Even Tick Comprehension",
    headerPrefix: "REDSTONE_CLOCK",
    missionPrefix: "YOUR TASK",
    intro: "# Redstone Pulse: Even Tick Filtering\n\nIsolate active repeaters pulsing on even tick intervals using modulo `% 2 == 0`.",
    technical: "Use modulo `x % 2 == 0` inside a list comprehension to filter even integers.",
    example: "active_redstone_repeaters = [r for r in redstone_ticks if r % 2 == 0]\nprint(active_redstone_repeaters)",
    task: "### YOUR MISSION\n\n1. Filter only the **even** numbers from the `redstone_ticks` list using a list comprehension.\n2. Store this filtered list in a new variable named `active_redstone_repeaters`.\n3. Print `active_redstone_repeaters`.",
    baseCode: "redstone_ticks = [101, 102, 103, 104, 105, 106, 107, 108]\n# TODO: Comprehend and filter even indices\n",
    hints: ["active_redstone_repeaters = [r for r in redstone_ticks if r % 2 == 0]","print(active_redstone_repeaters)"],
    solution: "active_redstone_repeaters = [r for r in redstone_ticks if r % 2 == 0]\nprint(active_redstone_repeaters)",
    solutionRegex: [/active_redstone_repeaters\s*=\s*\[\s*r\s+for\s+r\s+in\s+redstone_ticks\s+if\s+r\s*%\s*2\s*==\s*0\s*\]/, /print\s*\(\s*active_redstone_repeaters\s*\)/]
  },
  "intro-input": {
    title: "Biome Surveyor: User Input",
    headerPrefix: "BIOME_SURVEY",
    missionPrefix: "YOUR TASK",
    intro: "# Cartographer Table: User Input\n\nPrompt the wandering player for the new biome they just discovered on the map!",
    technical: "`input()` captures keyboard input as a string. Concatenate with `+`.",
    example: "biome_name = input(\"Enter biome name: \")\nprint(\"Entering biome: \" + biome_name)",
    task: "### YOUR MISSION\n\n1. Ask the player for the biome name with the prompt: **\"Enter biome name: \"** and store in `biome_name`.\n2. Print **\"Entering biome: \"** concatenated with `biome_name`.",
    baseCode: "# TODO: Capture biome name and print\n",
    hints: ["biome_name = input(\"Enter biome name: \")","print(\"Entering biome: \" + biome_name)"],
    solution: "biome_name = input(\"Enter biome name: \")\nprint(\"Entering biome: \" + biome_name)",
    solutionRegex: [/biome_name\s*=\s*input\s*\(\s*['"]Enter biome name:\s*['"]\s*\)/, /print\s*\(\s*['"]Entering biome:\s*['"]\s*\+\s*biome_name\s*\)/]
  },
  "input-mad-libs": {
    title: "Survival Diary: Mad Libs Story",
    headerPrefix: "SURVIVAL_DIARY",
    missionPrefix: "CRAFT_TALE",
    intro: "# Nighttime Survival: Mad Libs Story\n\nLog an epic nighttime mob encounter into your survival journal!",
    technical: "Collect user inputs and concatenate into a cohesive adventure story.",
    example: "adventure_log = steve + \" defeated \" + mob + \" with a \" + weapon + \"!\"\nprint(adventure_log)",
    task: "### YOUR MISSION\n\n1. Ask for player name with prompt: **\"Player name: \"** and store in `steve`.\n2. Ask for hostile mob with prompt: **\"Hostile mob: \"** and store in `mob`.\n3. Ask for crafted weapon with prompt: **\"Crafted weapon: \"** and store in `weapon`.\n4. Combine into `adventure_log` and print: `steve + \" defeated \" + mob + \" with a \" + weapon + \"!\"`.",
    baseCode: "# TODO: Compose survival encounter story\n",
    hints: ["steve = input(\"Player name: \")","mob = input(\"Hostile mob: \")","weapon = input(\"Crafted weapon: \")","adventure_log = steve + \" defeated \" + mob + \" with a \" + weapon + \"!\"","print(adventure_log)"],
    solution: "steve = input(\"Player name: \")\nmob = input(\"Hostile mob: \")\nweapon = input(\"Crafted weapon: \")\nadventure_log = steve + \" defeated \" + mob + \" with a \" + weapon + \"!\"\nprint(adventure_log)",
    solutionRegex: [/steve\s*=\s*input\s*\(\s*['"]Player name:\s*['"]\s*\)/, /mob\s*=\s*input\s*\(\s*['"]Hostile mob:\s*['"]\s*\)/, /weapon\s*=\s*input\s*\(\s*['"]Crafted weapon:\s*['"]\s*\)/, /print\s*\(\s*adventure_log\s*\)/]
  },
  "input-mad-libs-pro": {
    title: "Master Builder: Multi-Variable Logging",
    headerPrefix: "BUILD_ARCHIVE",
    missionPrefix: "WORLD_RECORD",
    intro: "# World Architecture: Multi-Variable Logging\n\nRecord the completion of a grand Minecraft castle or cathedral into server logs!",
    technical: "Combine 5 separate prompt inputs into a structured world dispatch message.",
    example: "build_log = crafter + \" crafted \" + material + \" into \" + structure + \" at \" + biome + \". World is \" + weather + \"!\"\nprint(build_log)",
    task: "### YOUR MISSION\n\n1. Ask for crafter with **\"Crafter: \"** in `crafter`.\n2. Ask for material with **\"Material: \"** in `material`.\n3. Ask for structure with **\"Structure: \"** in `structure`.\n4. Ask for biome with **\"Biome: \"** in `biome`.\n5. Ask for weather with **\"Weather: \"** in `weather`.\n6. Combine into `build_log` and print: `crafter + \" crafted \" + material + \" into \" + structure + \" at \" + biome + \". World is \" + weather + \"!\"`.",
    baseCode: "# TODO: Log build completion\n",
    hints: ["Ask all 5 inputs using input()","Combine them with + concatenation and print build_log"],
    solution: "crafter = input(\"Crafter: \")\nmaterial = input(\"Material: \")\nstructure = input(\"Structure: \")\nbiome = input(\"Biome: \")\nweather = input(\"Weather: \")\nbuild_log = crafter + \" crafted \" + material + \" into \" + structure + \" at \" + biome + \". World is \" + weather + \"!\"\nprint(build_log)",
    solutionRegex: [/crafter\s*=\s*input\s*\(\s*['"]Crafter:\s*['"]\s*\)/, /material\s*=\s*input\s*\(\s*['"]Material:\s*['"]\s*\)/, /structure\s*=\s*input\s*\(\s*['"]Structure:\s*['"]\s*\)/, /biome\s*=\s*input\s*\(\s*['"]Biome:\s*['"]\s*\)/, /weather\s*=\s*input\s*\(\s*['"]Weather:\s*['"]\s*\)/, /print\s*\(\s*build_log\s*\)/]
  },
  "print-formatting": {
    title: "Crafter Badge: F-Strings",
    headerPrefix: "PLAYER_PROFILE",
    missionPrefix: "F_STRING_TAG",
    intro: "# Crafter Passport: Clean F-Strings\n\nUse an f-string to display your player username and mining level cleanly on your server profile.",
    technical: "F-strings allow embedding variables inside string literals using `{variable}` syntax.",
    example: "print(f'Crafter: {alias} | Mining Level: {level}')",
    task: "### YOUR MISSION\n\nYou have `alias = 'Steve'` and `level = 99`. Use an **f-string** to print: `Crafter: Steve | Mining Level: 99`.",
    baseCode: "alias = 'Steve'\nlevel = 99\n# TODO: Print using f-string\n",
    hints: ["print(f'Crafter: {alias} | Mining Level: {level}')"],
    solution: "alias = 'Steve'\nlevel = 99\nprint(f'Crafter: {alias} | Mining Level: {level}')",
    solutionRegex: [/print\s*\(\s*f['"]Crafter:\s*\{alias\}\s*\|\s*Mining\s*Level:\s*\{level\}['"]\s*\)/]
  },
  "input-fstrings-fun": {
    title: "Village Trading: Dynamic Deployment",
    headerPrefix: "VILLAGE_MARKET",
    missionPrefix: "F_STRING_INPUT",
    intro: "# Emerald Exchange: F-String Input\n\nPrompt the trader for emerald shipments heading to distant villages, formatting the biome in uppercase.",
    technical: "Combine integer inputs with string formatting methods like `.upper()` in f-strings.",
    example: "print(f\"Deploying {villagers} emeralds to {settlement.upper()}...\")",
    task: "### YOUR MISSION\n\n1. Prompt for villager count with: **\"Enter villager count: \"** and store as int in `villagers`.\n2. Prompt for village biome with: **\"Enter village biome: \"** and store in `settlement`.\n3. Use an **f-string** to print: `Deploying {villagers} emeralds to {settlement.upper()}...`.",
    baseCode: "# TODO: Gather villager count and settlement\n",
    hints: ["villagers = int(input(\"Enter villager count: \"))","settlement = input(\"Enter village biome: \")","print(f\"Deploying {villagers} emeralds to {settlement.upper()}...\")"],
    solution: "villagers = int(input(\"Enter villager count: \"))\nsettlement = input(\"Enter village biome: \")\nprint(f\"Deploying {villagers} emeralds to {settlement.upper()}...\")",
    solutionRegex: [/print\s*\(\s*f['"]Deploying\s*\{villagers\}\s*emeralds\s*to\s*\{settlement\.upper\(\)\}\.\.\.['"]\s*\)/]
  },
  "input-cast-int": {
    title: "Beacon Building: Integer Casting",
    headerPrefix: "BEACON_BASE",
    missionPrefix: "INT_CONVERSION",
    intro: "# Beacon Pyramid: Integer Casting\n\nTally precious mineral blocks by converting user inputs to integers before stacking the pyramid base.",
    technical: "Wrap `input()` inside `int()` to convert text strings to numbers.",
    example: "iron_blocks = int(input(\"Enter iron blocks: \"))\ngold_blocks = int(input(\"Enter gold blocks: \"))\nprint(iron_blocks + gold_blocks)",
    task: "### YOUR MISSION\n\nTally pyramid mineral blocks:\n1. Prompt for iron blocks with **\"Enter iron blocks: \"** and store as an integer in `iron_blocks`.\n2. Prompt for gold blocks with **\"Enter gold blocks: \"** and store as an integer in `gold_blocks`.\n3. Print the sum of these blocks.",
    baseCode: "# TODO: Cast inputs to int and calculate sum\n",
    hints: ["iron_blocks = int(input(\"Enter iron blocks: \"))","gold_blocks = int(input(\"Enter gold blocks: \"))","print(iron_blocks + gold_blocks)"],
    solution: "iron_blocks = int(input(\"Enter iron blocks: \"))\ngold_blocks = int(input(\"Enter gold blocks: \"))\nprint(iron_blocks + gold_blocks)",
    solutionRegex: [/iron_blocks\s*=\s*int\s*\(\s*input/, /gold_blocks\s*=\s*int\s*\(\s*input/, /print\s*\(\s*iron_blocks\s*\+\s*gold_blocks\s*\)/]
  },
  "input-cast-float": {
    title: "Explosion Physics: Float Casting",
    headerPrefix: "TNT_PHYSICS",
    missionPrefix: "FLOAT_CALIBRATION",
    intro: "# TNT Blast Radius: Float Conversion\n\nCalculate blast shockwave velocity by multiplying block hardness by the explosive ratio.",
    technical: "Wrap `input()` in `float()` to parse decimals.",
    example: "blast_res = float(input(\"Enter block hardness: \"))\ntnt_mult = float(input(\"TNT blast ratio: \"))\nprint(blast_res * tnt_mult)",
    task: "### YOUR MISSION\n\nCalibrate explosion mechanics:\n1. Prompt for block hardness with **\"Enter block hardness: \"** and store as float in `blast_res`.\n2. Prompt for TNT ratio with **\"TNT blast ratio: \"** and store as float in `tnt_mult`.\n3. Print the result of multiplying `blast_res` by `tnt_mult`.",
    baseCode: "# TODO: Cast inputs to float and multiply\n",
    hints: ["blast_res = float(input(\"Enter block hardness: \"))","tnt_mult = float(input(\"TNT blast ratio: \"))","print(blast_res * tnt_mult)"],
    solution: "blast_res = float(input(\"Enter block hardness: \"))\ntnt_mult = float(input(\"TNT blast ratio: \"))\nprint(blast_res * tnt_mult)",
    solutionRegex: [/blast_res\s*=\s*float\s*\(\s*input/, /tnt_mult\s*=\s*float\s*\(\s*input/, /print\s*\(\s*blast_res\s*\*\s*tnt_mult\s*\)/]
  },
  "control-indentation": {
    title: "Stronghold Gate: Indentation",
    headerPrefix: "STRONGHOLD_GATE",
    missionPrefix: "INDENT_BLOCK",
    intro: "# Stronghold Portal: Indentation Rules\n\nActivate the End Portal frame by indenting your code 4 spaces inside an `if True:` block.",
    technical: "In Python, code blocks under an `if` statement must be indented by exactly 4 spaces.",
    example: "if True:\n    print(\"Accessing...\")",
    task: "### YOUR MISSION\n\n1. Set up an `if True:` condition block.\n2. On the next line, indented with 4 spaces, print **\"Accessing...\"** to activate the gate.",
    baseCode: "# TODO: Indented if block\n",
    hints: ["if True:","    print(\"Accessing...\")"],
    solution: "if True:\n    print(\"Accessing...\")",
    solutionRegex: [/if\s+True\s*:/, /print\s*\(\s*['"]Accessing\.\.\.['"]\s*\)/]
  },
  "control-nested-indent": {
    title: "Ancient City: Double Indentation",
    headerPrefix: "DEEP_DARK_GATE",
    missionPrefix: "NESTED_INDENT",
    intro: "# Ancient City Vault: Double Indentation\n\nSneak past the Warden's sculk sensors using double-indented nested `if True:` blocks.",
    technical: "Nested if blocks require double indentation (8 spaces) on their interior executable statements.",
    example: "if True:\n    if True:\n        print(\"CORE ACCESS GRANTED\")",
    task: "### YOUR MISSION\n\n1. Write the outer gate with **`if True:`**.\n2. Nest the inner gate underneath with an inner **`if True:`** (indented by 4 spaces).\n3. On the innermost level (indented with 8 spaces), print **`\"CORE ACCESS GRANTED\"`**.",
    baseCode: "# TODO: Nested if blocks\n",
    hints: ["if True:","    if True:","        print(\"CORE ACCESS GRANTED\")"],
    solution: "if True:\n    if True:\n        print(\"CORE ACCESS GRANTED\")",
    solutionRegex: [/if\s+True\s*:/, /if\s+True\s*:/, /print\s*\(\s*['"]CORE\s+ACCESS\s+GRANTED['"]\s*\)/]
  },
  "control-if": {
    title: "Nether Portal: Simple If",
    headerPrefix: "OBSIDIAN_FRAME",
    missionPrefix: "PORTAL_FLAG",
    intro: "# Nether Gate: Simple If\n\nIgnite the obsidian frame with flint and steel. Check if the portal is lit to initiate warp sequence.",
    technical: "The `if` statement executes its code block if its boolean condition is True.",
    example: "if portal_lit:\n    print(\"ENTERING THE NETHER\")",
    task: "### YOUR MISSION\n\nIf `portal_lit` is `True`, print `\"ENTERING THE NETHER\"`.",
    baseCode: "portal_lit = True\n# TODO: Check portal state\n",
    hints: ["if portal_lit:","    print(\"ENTERING THE NETHER\")"],
    solution: "portal_lit = True\nif portal_lit:\n    print(\"ENTERING THE NETHER\")",
    solutionRegex: [/if\s+portal_lit/, /print\s*\(\s*['"]ENTERING THE NETHER['"]\s*\)/]
  },
  "control-else": {
    title: "Iron Door: If/Else",
    headerPrefix: "REDSTONE_DOOR",
    missionPrefix: "ELSE_LOGIC",
    intro: "# Secure Vault Door: If/Else\n\nTest the pressure plate switch using an `if/else` block.",
    technical: "The `else` block runs when the preceding `if` condition evaluates to False.",
    example: "if key_valid:\n    print(\"ACCESS GRANTED\")\nelse:\n    print(\"ALARM TRIGGERED\")",
    task: "### YOUR MISSION\n\n1. Construct an `if/else` block evaluating `key_valid`.\n2. If `key_valid` is `True`, print **`\"ACCESS GRANTED\"`**.\n3. Else, print **`\"ALARM TRIGGERED\"`**.",
    baseCode: "key_valid = True\n# TODO: if/else branch\n",
    hints: ["if key_valid:","    print(\"ACCESS GRANTED\")","else:","    print(\"ALARM TRIGGERED\")"],
    solution: "if key_valid:\n    print(\"ACCESS GRANTED\")\nelse:\n    print(\"ALARM TRIGGERED\")",
    solutionRegex: [/if\s+key_valid/, /else\s*:/, /print\s*\(\s*['"]ACCESS GRANTED['"]\s*\)/, /print\s*\(\s*['"]ALARM TRIGGERED['"]\s*\)/]
  },
  "control-elif": {
    title: "Security Clearance: Elif Levels",
    headerPrefix: "SERVER_SECURITY",
    missionPrefix: "TIER_ELIF",
    intro: "# Server Permission: Elif Branching\n\nSort player privileges based on operator clearance levels.",
    technical: "Chaining `elif` conditions allows multiple separate outcomes to be evaluated in order.",
    example: "if clearance == 1:\n    print(\"ROOT ACCESS\")\nelif clearance <= 5:\n    print(\"LEVEL 5 ACCESS\")\nelse:\n    print(\"PERMISSION DENIED\")",
    task: "### YOUR MISSION\n\n1. Build an `if/elif/else` script around `clearance`.\n2. If `clearance` is exactly `1`, print **`\"ROOT ACCESS\"`**.\n3. Elif `clearance` is less than or equal to `5`, print **`\"LEVEL 5 ACCESS\"`**.\n4. Else, print **`\"PERMISSION DENIED\"`**.",
    baseCode: "clearance = 5\n# TODO: Route clearance\n",
    hints: ["if clearance == 1:","elif clearance <= 5:","else:"],
    solution: "if clearance == 1:\n    print(\"ROOT ACCESS\")\nelif clearance <= 5:\n    print(\"LEVEL 5 ACCESS\")\nelse:\n    print(\"PERMISSION DENIED\")",
    solutionRegex: [/if\s+clearance\s*==\s*1/, /elif\s+clearance\s*<=\s*5/, /else\s*:/, /print\s*\(\s*['"]ROOT ACCESS['"]\s*\)/, /print\s*\(\s*['"]LEVEL 5 ACCESS['"]\s*\)/, /print\s*\(\s*['"]PERMISSION DENIED['"]\s*\)/]
  },
  "control-meme-gen": {
    title: "Creeper Alert: Sss-Boom Defense",
    headerPrefix: "CREEPER_ALARM",
    missionPrefix: "MOB_EVADE",
    intro: "# Cave Ambush: Creeper Defense\n\nIf a Creeper is detected hissing nearby, trigger an emergency water bucket sprint; otherwise, keep mining peacefully!",
    technical: "Use boolean conditions directly inside `if` statements.",
    example: "if is_detected:\n    print(\"CREEPER_HISS_ESCAPE\")\nelse:\n    print(\"Mining expedition safe.\")",
    task: "### YOUR MISSION\n\nCompose an `if/else` guard:\n1. If `is_detected`, print **`\"CREEPER_HISS_ESCAPE\"`** to dodge the blast.\n2. Else, print **`\"Mining expedition safe.\"`**.",
    baseCode: "is_detected = True\n# TODO: Process evasion\n",
    hints: ["if is_detected:","    print(\"CREEPER_HISS_ESCAPE\")","else:","    print(\"Mining expedition safe.\")"],
    solution: "if is_detected:\n    print(\"CREEPER_HISS_ESCAPE\")\nelse:\n    print(\"Mining expedition safe.\")",
    solutionRegex: [/if\s+is_detected/, /else\s*:/, /print\s*\(\s*['"]CREEPER_HISS_ESCAPE['"]\s*\)/, /print\s*\(\s*['"]Mining\s+expedition\s+safe\.['"]\s*\)/]
  },
  "control-nickname-gen": {
    title: "Mining Master: Rank Builder",
    headerPrefix: "XP_LEVELLER",
    missionPrefix: "MINER_TITLE",
    intro: "# Experience Orbs: Player Rank Assignment\n\nAssign a prestigious server title to Steve based on total mining experience points.",
    technical: "Assign a variable inside conditional branches and display it afterwards.",
    example: "if mining_xp > 9000:\n    player_status = \"Master Miner\"\nelse:\n    player_status = \"Novice\"\nprint(player_status)",
    task: "### YOUR MISSION\n\nVerify player tier:\n1. If `mining_xp > 9000`, set `player_status` to **`\"Master Miner\"`**.\n2. Else, set `player_status` to **`\"Novice\"`**.\n3. Finally, print `print(player_status)`.",
    baseCode: "mining_xp = 9001\nplayer_status = \"\"\n# TODO: Evaluate miner rank and print\n",
    hints: ["if mining_xp > 9000:","    player_status = \"Master Miner\"","else:","    player_status = \"Novice\"","print(player_status)"],
    solution: "mining_xp = 9001\nif mining_xp > 9000:\n    player_status = \"Master Miner\"\nelse:\n    player_status = \"Novice\"\nprint(player_status)",
    solutionRegex: [/if\s+mining_xp\s*>\s*9000\s*:/, /player_status\s*=\s*['"]Master Miner['"]/, /player_status\s*=\s*['"]Novice['"]/, /print\s*\(\s*player_status\s*\)/]
  },
  "control-adventure": {
    title: "Minecart Junction: Choice Routing",
    headerPrefix: "MINECART_JUNCTION",
    missionPrefix: "TRACK_SWITCH",
    intro: "# Rail Network: Minecart Route Choice\n\nYou reach a fork on the underground railway track: switch left (\"1\") or plunge deeper into the fortress (\"2\").",
    technical: "Compare `choice` using `==` against string values `'1'` and `'2'`.",
    example: "if choice == \"1\":\n    print(\"Found Diamond Ore!\")\nelif choice == \"2\":\n    print(\"Entered Nether Fortress!\")\nelse:\n    print(\"Returned to Base.\")",
    task: "### YOUR MISSION\n\nCompose a rail switch router:\n1. If `choice` is **\"1\"**, print **\"Found Diamond Ore!\"**.\n2. Elif `choice` is **\"2\"**, print **\"Entered Nether Fortress!\"**.\n3. Else, print **\"Returned to Base.\"**.",
    baseCode: "choice = \"1\"\n# TODO: Route track switch\n",
    hints: ["if choice == \"1\":","elif choice == \"2\":","else:"],
    solution: "if choice == \"1\":\n    print(\"Found Diamond Ore!\")\nelif choice == \"2\":\n    print(\"Entered Nether Fortress!\")\nelse:\n    print(\"Returned to Base.\")",
    solutionRegex: [/if\s+choice\s*==\s*['"]1['"]\s*:/, /elif\s+choice\s*==\s*['"]2['"]\s*:/, /else\s*:/, /print\s*\(\s*['"]Found Diamond Ore!['"]\s*\)/, /print\s*\(\s*['"]Entered Nether Fortress!['"]\s*\)/, /print\s*\(\s*['"]Returned to Base\.['"]\s*\)/]
  },
  "control-multi-elif": {
    title: "Three Dimensions: Multi Elif",
    headerPrefix: "DIMENSION_WARP",
    missionPrefix: "REALM_SELECT",
    intro: "# Minecraft Realms: Multi-Branch Routing\n\nDirect teleportation coordinates based on the selected dimension realm.",
    technical: "Cascading `if/elif/elif/else` blocks inspect multiple alternatives sequentially.",
    example: "if dimension == \"overworld\":\n    print(\"Surface sun shining.\")\nelif dimension == \"nether\":\n    print(\"Lava ocean bubbling.\")",
    task: "### YOUR MISSION\n\nAssign realm status based on variable `dimension`:\n1. If `dimension` is **`\"overworld\"`**, print **`\"Surface sun shining.\"`**\n2. Elif `dimension` is **`\"nether\"`**, print **`\"Lava ocean bubbling.\"`**\n3. Elif `dimension` is **`\"end\"`**, print **`\"Ender dragon circling.\"`**\n4. Else, print **`\"Void falling.\"`**",
    baseCode: "dimension = \"overworld\"\n# TODO: Route dimension realm\n",
    hints: ["if dimension == \"overworld\":","elif dimension == \"nether\":","elif dimension == \"end\":","else:"],
    solution: "dimension = \"overworld\"\nif dimension == \"overworld\":\n    print(\"Surface sun shining.\")\nelif dimension == \"nether\":\n    print(\"Lava ocean bubbling.\")\nelif dimension == \"end\":\n    print(\"Ender dragon circling.\")\nelse:\n    print(\"Void falling.\")",
    solutionRegex: [/if\s+dimension\s*==\s*['"]overworld['"]\s*:/, /elif\s+dimension\s*==\s*['"]nether['"]\s*:/, /elif\s+dimension\s*==\s*['"]end['"]\s*:/, /else\s*:/, /print\s*\(\s*['"]Surface\s+sun\s+shining\.['"]\s*\)/, /print\s*\(\s*['"]Lava\s+ocean\s+bubbling\.['"]\s*\)/, /print\s*\(\s*['"]Ender\s+dragon\s+circling\.['"]\s*\)/, /print\s*\(\s*['"]Void\s+falling\.['"]\s*\)/]
  },
  "control-loops": {
    title: "Block Placement: Range Loop",
    headerPrefix: "BUILDER_LOOP",
    missionPrefix: "WALL_CONSTRUCT",
    intro: "# Wall Construction: For Loops\n\nAutomate placing a sequence of 5 building blocks with a `for` loop.",
    technical: "The `range(5)` function loops 5 times, passing indices 0 through 4 to variable `i`.",
    example: "for i in range(5):\n    print(f\"Block {i+1} placed\")",
    task: "### YOUR MISSION\n\nUse a `for` loop with `range(5)` to `print` the status message `f\"Block {i+1} placed\"` for each of the 5 blocks.",
    baseCode: "# TODO: Loop 5 times\n",
    hints: ["for i in range(5):","    print(f\"Block {i+1} placed\")"],
    solution: "for i in range(5):\n    print(f\"Block {i+1} placed\")",
    solutionRegex: [/for\s+i\s+in\s+range\s*\(\s*5\s*\)/, /print/]
  },
  "loop-data-scan": {
    title: "Rune Translation: Character Iteration",
    headerPrefix: "ENCHANTING_TABLE",
    missionPrefix: "RUNE_SCAN",
    intro: "# Enchanting Table: Character Parsing\n\nDecode the mystic runes inscribed on the obsidian enchanting table `\"MINE\"`.",
    technical: "Iterating through strings processes characters sequentially one by one.",
    example: "for block in craft_code:\n    print(block)",
    task: "### YOUR MISSION\n\nYou've discovered an enchanting rune text `craft_code`: `\"MINE\"`. Use a `for` loop to iterate through every character `block` in `craft_code` and `print` it.",
    baseCode: "craft_code = \"MINE\"\n# TODO: Iterate through runes\n",
    hints: ["for block in craft_code:","    print(block)"],
    solution: "craft_code = \"MINE\"\nfor block in craft_code:\n    print(block)",
    solutionRegex: [/for\s+block\s+in\s+craft_code/, /print\s*\(\s*block\s*\)/]
  },
  "loop-list-audit": {
    title: "Resource Packs: File Audit",
    headerPrefix: "MOD_PACK_LOADER",
    missionPrefix: "MC_FILTER",
    intro: "# Modpack Loader: Filter Minecraft Files\n\nScan through incoming folder assets and load only valid Minecraft addon packages ending in `.mc`.",
    technical: "The `.endswith()` method returns True if a string ends with the specified file extension.",
    example: "for item in inventory_files:\n    if item.endswith(\".mc\"):\n        print(f\"Loading craft: {item}\")",
    task: "### YOUR MISSION\n\nScan through `inventory_files`. If a file ends with `\".mc\"`, `print` the output line: `f\"Loading craft: {item}\"`.",
    baseCode: "inventory_files = [\"sword.mc\", \"skin.png\", \"shield.mc\", \"config.json\"]\n# TODO: Audit addon files\n",
    hints: ["for item in inventory_files:","    if item.endswith(\".mc\"):","        print(f\"Loading craft: {item}\")"],
    solution: "inventory_files = [\"sword.mc\", \"skin.png\", \"shield.mc\", \"config.json\"]\nfor item in inventory_files:\n    if item.endswith(\".mc\"):\n        print(f\"Loading craft: {item}\")",
    solutionRegex: [/for\s+item\s+in\s+inventory_files/, /item\.endswith\s*\(\s*['"]\.mc['"]\s*\)/, /print/]
  },
  "loop-nested": {
    title: "Chunk Generation: 3x3 Grid Scan",
    headerPrefix: "WORLD_GENERATOR",
    missionPrefix: "CHUNK_GRID",
    intro: "# Chunk Coordinates: Nested Loops\n\nMap a 3x3 terrain chunk section in your Minecraft world using nested loops.",
    technical: "Nested loops execute the inner loop completely for each step of the outer loop.",
    example: "for x in range(3):\n    for z in range(3):\n        print(f\"Chunk Grid - X: {x}, Z: {z}\")",
    task: "### YOUR MISSION\n\nScan a **3x3 chunk grid**. Code nested loops with `range(3)` for `x` and `z`.\n\nInside the inner loop, `print` each coordinate in this exact format: `f\"Chunk Grid - X: {x}, Z: {z}\"`.\n\nMake sure your `print` is indented with 8 spaces!",
    baseCode: "# TODO: Nested chunk loop\n",
    hints: ["for x in range(3):","    for z in range(3):","        print(f\"Chunk Grid - X: {x}, Z: {z}\")"],
    solution: "for x in range(3):\n    for z in range(3):\n        print(f\"Chunk Grid - X: {x}, Z: {z}\")",
    solutionRegex: [/for\s+x/, /for\s+z/, /print/]
  },
  "loop-break-continue": {
    title: "Mining Limit: Loop Break",
    headerPrefix: "QUARRY_DRILL",
    missionPrefix: "BEDROCK_AVOID",
    intro: "# Automatic Drill: Loop Break\n\nDrill 10 blocks deep. If the excavation reaches block index `7`, break out of the loop immediately to avoid hitting lava!",
    technical: "The `break` statement halts loop execution immediately.",
    example: "for i in range(10):\n    if i == 7:\n        break\n    print(i)",
    task: "### YOUR MISSION\n\nLoop through `range(10)`. If mining depth `i` reaches `7`, call `break`. Otherwise, `print` current depth `i` using `print(i)`.",
    baseCode: "# TODO: Loop with break condition\n",
    hints: ["for i in range(10):","    if i == 7:","        break","    print(i)"],
    solution: "for i in range(10):\n    if i == 7:\n        break\n    print(i)",
    solutionRegex: [/for\s+i\s+in\s+range/, /if\s+i\s*==\s*7/, /break/, /print/]
  },
  "control-while": {
    title: "Furnace Burner: Fuel While Loop",
    headerPrefix: "FURNACE_HEAT",
    missionPrefix: "SMELT_BURN",
    intro: "# Smelting Fuel: While Loops\n\nWhile loops run as long as fuel remains unspent. Track a coal block's battery power as it burns down in the blast furnace.",
    task: "### YOUR MISSION\n\n1. `battery` starts at `100`.\n2. While `battery > 0`, subtract `20` from `battery` to fuel the furnace.\n3. `print` the current `battery` level inside the loop.",
  },
  "functions-intro": {
    headerPrefix: "WORKBENCH_BLUEPRINT",
    missionPrefix: "CRAFT_RECIPE",
    intro: "# Workbench Crafting: Functions\n\nDefine reusable crafting recipes instead of re-typing crafting table formulas!",
    task: "Write a function `craft_recipe(item_name)` that prints `f'Crafting {item_name} on workbench...'`. Call it with `'Diamond Sword'`.",
    baseCode: "# TODO: Define craft_recipe function\n",
    solution: "def craft_recipe(item_name):\n    print(f'Crafting {item_name} on workbench...')\n\ncraft_recipe('Diamond Sword')",
    solutionRegex: [/def\s+craft_recipe/, /craft_recipe\s*\(/]
  },
  "functions-recursion": {
    headerPrefix: "MINE_SHAFT_DIG",
    missionPrefix: "RECURSIVE_DIG",
    intro: "# Mining Shaft: Recursion\n\nDig a vertical staircase step by step using a recursive function that descends until it reaches level 0!",
    task: "Write a recursive function `mine_shaft(depth)` that prints the depth and calls itself with `depth-1` until it reaches `0`. Call it with `5`.",
    baseCode: "# TODO: Define recursive function\n",
    solution: "def mine_shaft(depth):\n    print(depth)\n    if depth > 0:\n        mine_shaft(depth - 1)\n\nmine_shaft(5)",
    solutionRegex: [/def\s+mine_shaft/, /mine_shaft\s*\(\s*depth\s*-\s*1\s*\)/]
  },
  "oop-intro": {
    headerPrefix: "BLOCK_REGISTRY",
    missionPrefix: "BLOCK_TEMPLATE",
    intro: "# Block Templates: Classes\n\nEvery cube in Minecraft (dirt, stone, diamond ore) is built from a common block template. Define a reusable template called a **Class**.",
    task: "### YOUR MISSION\n\nDefine a base class named `Block`. Use `pass` inside its block under proper indentation.",
    baseCode: "# TODO: Establish base class Block\n",
    hints: ["Use 'class Block:' followed by an indented 'pass'."],
    solution: "class Block:\n    pass",
    solutionRegex: [/class\s+Block/, /pass/]
  },
  "oop-init": {
    headerPrefix: "BLOCK_FACTORY",
    missionPrefix: "TYPE_CONSTRUCTOR",
    intro: "# Block Generation: Constructors\n\nWhen world generation spawns a new block into a chunk, initialize its material name with the `__init__` constructor.",
    task: "### YOUR MISSION\n\nInside `Block`, define the constructor method `__init__` which accepts `self` and a parameter `name`. Assign the `name` value to `self.name`.",
    baseCode: "class Block:\n    # TODO: Add __init__ constructor\n",
    hints: ["def __init__(self, name):","    self.name = name"],
    solution: "class Block:\n    def __init__(self, name):\n        self.name = name",
    solutionRegex: [/def\s+__init__\s*\(\s*self\s*,\s*name\s*\)\s*:/, /self\.name\s*=\s*name/]
  },
  "oop-methods": {
    headerPrefix: "BLOCK_HARVEST",
    missionPrefix: "MINE_ACTION",
    intro: "# Harvesting Blocks: Methods\n\nA block needs behavior when struck with a pickaxe! Functions defined inside a class are called **Methods**.",
    task: "### YOUR MISSION\n\nAdd a `mine` method to `Block` that `print`s \"Block harvested\".",
    baseCode: "class Block:\n    def __init__(self, name):\n        self.name = name\n    # TODO: Define mine method\n",
    hints: ["def mine(self):","    print(\"Block harvested\")"],
    solution: "class Block:\n    def __init__(self, name):\n        self.name = name\n    def mine(self):\n        print(\"Block harvested\")",
    solutionRegex: [/def\s+mine\s*\(\s*self\s*\)\s*:/, /print\s*\(\s*['"]Block harvested['"]\s*\)/]
  },
  "oop-state": {
    headerPrefix: "BLOCK_DURABILITY",
    missionPrefix: "STATE_CHECK",
    intro: "# Block Integrity: Object State\n\nBlocks track their structural integrity as Steve hits them with a tool.",
    task: "### YOUR MISSION\n\n1. In `__init__`, add a `hardness` instance variable defaulted to the string \"Solid\".\n2. Create a method `break_block` that updates `self.hardness` to the string \"Broken\".",
    baseCode: "class Block:\n    def __init__(self, name):\n        self.name = name\n        # TODO: Add hardness default\n    # TODO: Add break_block method\n",
    hints: ["self.hardness = \"Solid\"","def break_block(self):","    self.hardness = \"Broken\""],
    solution: "class Block:\n    def __init__(self, name):\n        self.name = name\n        self.hardness = \"Solid\"\n    def break_block(self):\n        self.hardness = \"Broken\"",
    solutionRegex: [/self\.hardness\s*=\s*['"]Solid['"]/, /def\s+break_block/, /self\.hardness\s*=\s*['"]Broken['"]/]
  },
  "oop-interaction": {
    headerPrefix: "CRAFTING_COMBINE",
    missionPrefix: "RECIPE_MIX",
    intro: "# Crafting Recipes: Object Interaction\n\nIn Minecraft, blocks and items combine together on the crafting grid! Methods can accept other instances as arguments.",
    task: "### YOUR MISSION\n\nAdd a `combine_with` method to `Block` that accepts `other` as its parameter. It should `print` the formatted message: `f\"Combining with: {other.name}\"`.",
    baseCode: "class Block:\n    def __init__(self, name):\n        self.name = name\n    # TODO: Add combine_with method\n",
    hints: ["def combine_with(self, other):","    print(f\"Combining with: {other.name}\")"],
    solution: "class Block:\n    def __init__(self, name):\n        self.name = name\n    def combine_with(self, other):\n        print(f\"Combining with: {other.name}\")",
    solutionRegex: [/def\s+combine_with\s*\(\s*self\s*,\s*other\s*\)\s*:/, /other\.name/]
  },
  "oop-inheritance": {
    headerPrefix: "REDSTONE_CIRCUIT",
    missionPrefix: "POWER_BLOCK",
    intro: "# Powered Blocks: Inheritance\n\nRedstone blocks inherit all standard physical properties of normal blocks, but also emit continuous electrical signals!",
    task: "### YOUR MISSION\n\nCreate a class `RedstoneBlock` that inherits from `Block`. Give it an `emit_power` method that `print`s \"Redstone signal activated\".",
    baseCode: "class Block:\n    def __init__(self, name):\n        self.name = name\n# TODO: Create RedstoneBlock subclass inheriting from Block\n",
    hints: ["class RedstoneBlock(Block):","    def emit_power(self):","        print(\"Redstone signal activated\")"],
    solution: "class Block:\n    def __init__(self, name):\n        self.name = name\n\nclass RedstoneBlock(Block):\n    def emit_power(self):\n        print(\"Redstone signal activated\")",
    solutionRegex: [/class\s+RedstoneBlock\s*\(\s*Block\s*\)\s*:/, /def\s+emit_power/, /print\s*\(\s*['"]Redstone signal activated['"]\s*\)/]
  },
  "oop-str": {
    headerPrefix: "ITEM_TOOLTIP",
    missionPrefix: "STR_FORMAT",
    intro: "# Tooltip Display: Special Str Method\n\nOverride `__str__` to show a clean in-game tooltip description instead of a raw memory address.",
    task: "### YOUR MISSION\n\nIn `Block`, add the custom method `__str__` that returns: `f\"Minecraft Block {self.name}\"`.",
    baseCode: "class Block:\n    def __init__(self, name):\n        self.name = name\n    # TODO: Add __str__ method\n",
    hints: ["def __str__(self):","    return f\"Minecraft Block {self.name}\""],
    solution: "class Block:\n    def __init__(self, name):\n        self.name = name\n    def __str__(self):\n        return f\"Minecraft Block {self.name}\"",
    solutionRegex: [/def\s+__str__/, /return\s+f['"].*Minecraft Block.*self\.name.*['"]/]
  },
  "oop-class-vars": {
    headerPrefix: "GAME_ENGINE",
    missionPrefix: "GLOBAL_ENGINE",
    intro: "# World Constant: Shared Class Variables\n\nEvery block cube in your world belongs to the same Minecraft game engine. Store this universal constant in a class variable.",
    task: "### YOUR MISSION\n\n1. Define a class variable `game_engine` set to \"Minecraft\" inside `Block` before other initialisers.\n2. `print` the class variable using `Block.game_engine`.",
    baseCode: "class Block:\n    # TODO: Define class variable 'game_engine'\n    pass\n# TODO: Print Block.game_engine\n",
    hints: ["game_engine = \"Minecraft\"","print(Block.game_engine)"],
    solution: "class Block:\n    game_engine = \"Minecraft\"\n\nprint(Block.game_engine)",
    solutionRegex: [/game_engine\s*=\s*['"]Minecraft['"]/, /print\s*\(\s*Block\.game_engine\s*\)/]
  }
};
