export const POKEMON_THEME: any = {
  "intro-print": {
    title: "Pokédex Boot: Hello World",
    headerPrefix: "POKEDEX_TERMINAL",
    missionPrefix: "TRAINER_BOOT",
    intro: "# Starting Your Journey: print()\n\nWelcome to the world of Pokémon! Professor Oak has just handed you your very first Pokédex. Initialize your trainer journey by sending your first battle call.",
    technical: "In Python, the `print()` function displays whatever text or numbers you place inside its parentheses on the screen.",
    example: "print(\"Pikachu, I choose you!\")",
    task: "### YOUR MISSION\n\nUse `print()` to display: `\"Pikachu, I choose you!\"`",
    baseCode: "# TODO: Call out your starter Pokémon\n",
    hints: ["Type print(\"Pikachu, I choose you!\")","Make sure the text is inside double quotes"],
    solution: "print(\"Pikachu, I choose you!\")",
    solutionRegex: [/print\s*\(\s*['"]Pikachu, I choose you!['"]\s*\)/]
  },
  "naming-conventions": {
    title: "Pokédex Standards: Lowercase Names",
    headerPrefix: "PROFESSOR_OAK_LAB",
    missionPrefix: "POKEDEX_INDEX",
    intro: "# Pokédex Standards: Lowercase Names\n\nProfessor Oak's Pokédex database is strictly case-sensitive. Variable names should follow snake_case naming conventions and remain lowercase.",
    technical: "Python variables must start with a lowercase letter or underscore, and words are separated by underscores `_`.",
    example: "pokedex_id = 25\nprint(pokedex_id)",
    task: "### YOUR MISSION\n\nCreate a lowercase variable named `pokedex_id` and assign its value to `25` (Pikachu's official Dex number). Print it with `print()` to confirm. Everything must be lowercase!",
    baseCode: "# TODO: Store pokedex_id variable and print it\n",
    hints: ["Write pokedex_id = 25","On the next line, write print(pokedex_id)"],
    solution: "pokedex_id = 25\nprint(pokedex_id)",
    solutionRegex: [/pokedex_id\s*=\s*25/, /print\s*\(\s*pokedex_id\s*\)/]
  },
  "intro-comments": {
    title: "Battle Tactics: Comments",
    headerPrefix: "WILD_GRASS",
    missionPrefix: "BATTLE_TACTIC",
    intro: "# Battle Tactics: Comments\n\nWhen creeping through tall grass, skilled trainers leave scouting notes to remember Pokémon encounter rates and battle strategies.",
    technical: "Lines starting with `#` are comments. Python ignores them, making them perfect for developer and trainer notes.",
    example: "# Catch wild Pokémon\nprint(\"Throwing Pokéball...\")",
    task: "### YOUR MISSION\n\nWrite a comment `# Catch wild Pokémon` and then `print(\"Throwing Pokéball...\")`",
    baseCode: "# TODO: Add tactic comment and throw Pokéball\n",
    hints: ["Line 1: # Catch wild Pokémon","Line 2: print(\"Throwing Pokéball...\")"],
    solution: "# Catch wild Pokémon\nprint(\"Throwing Pokéball...\")",
    solutionRegex: [/#.*Catch wild Pokémon/, /print\s*\(\s*['"]Throwing Pokéball\.\.\.['"]\s*\)/]
  },
  "comments-inline": {
    title: "Trainer Profile: Inline Comments",
    headerPrefix: "TRAINER_CARD",
    missionPrefix: "BADGE_RECORD",
    intro: "# Trainer Profile: Inline Comments\n\nDocumenting stats on your trainer card helps League officials verify your gym credentials without cluttering the screen.",
    technical: "Inline comments appear on the same line after executable code, separated by `#`.",
    example: "trainer_level = 50 # Indigo Plateau rank",
    task: "### YOUR MISSION\n\nInitialise `trainer_level` to `50`. On the same line, add an inline comment `# Indigo Plateau rank`.",
    baseCode: "# TODO: Initialize variable with inline comment\n",
    hints: ["Write trainer_level = 50 followed by # Indigo Plateau rank on the same line."],
    solution: "trainer_level = 50 # Indigo Plateau rank",
    solutionRegex: [/trainer_level\s*=\s*50/, /#.*Indigo Plateau rank/]
  },
  "intro-vars": {
    title: "Creature Vitals: Variables",
    headerPrefix: "POKEMON_STATS",
    missionPrefix: "SLOT_ALLOC",
    intro: "# Creature Vitals: Variables\n\n**What is a Variable?** Think of a **variable** as a **Pokéball slot on your trainer belt**! You give the slot a name (like `starter_hp`), store hit points or items inside, and read them during battle.\n\nKeep track of your active Pokémon's health and your bag's potion stash.",
    technical: "Variables store information that can be referenced and manipulated throughout a program.",
    example: "starter_hp = 100\npotion_count = 5",
    task: "### YOUR MISSION\n\nCreate `starter_hp` set to `100` and `potion_count` set to `5`.",
    baseCode: "# TODO: Record starter hp and potion count\n",
    hints: ["starter_hp = 100","potion_count = 5"],
    solution: "starter_hp = 100\npotion_count = 5",
    solutionRegex: [/starter_hp\s*=\s*100/, /potion_count\s*=\s*5/]
  },
  "vars-reassignment": {
    title: "Pokédex Upgrade: Reassignment",
    headerPrefix: "POKEDEX_UPDATE",
    missionPrefix: "FIRMWARE_FLASH",
    intro: "# Pokédex Upgrade: Reassignment\n\nProfessor Oak just released the National Pokédex expansion! Update your `pokedex_version` variable to upgrade your scanner.",
    technical: "When you assign a new value to an existing variable name, Python throws away the old value and replaces it with the new one. This is called **reassignment**.",
    example: "pokedex_version = 1.0\npokedex_version = 2.0\nprint(pokedex_version)",
    task: "### YOUR MISSION\n\nInitialise `pokedex_version` as `1.0`. Then update `pokedex_version` to `2.0`. Print it.",
    baseCode: "pokedex_version = 1.0\n# TODO: Upgrade to 2.0 and print\n",
    hints: ["Assign pokedex_version = 2.0 on the next line.","Print it with print(pokedex_version)."],
    solution: "pokedex_version = 1.0\npokedex_version = 2.0\nprint(pokedex_version)",
    solutionRegex: [/pokedex_version\s*=\s*1\.0/, /pokedex_version\s*=\s*2\.0/, /print\s*\(\s*pokedex_version\s*\)/]
  },
  "vars-placeholder": {
    title: "Pokédex Registration: Empty Placeholders",
    headerPrefix: "CATCH_LOG",
    missionPrefix: "SCAN_INTERCEPT",
    intro: "# Pokédex Registration: Empty Placeholders\n\nWhen a wild Pokémon rustles in the tall grass, our database prepares an empty buffer in memory before logging the species name.",
    technical: "For strings, an \"empty\" value is represented by two quotes with nothing inside, such as `\"\"` or `''`.\n\n### Overwriting with Input:\nBy first initializing `pokemon_data = \"\"` as a placeholder, we allocate space in memory. Then, running `pokemon_data = input(\"...\")` overwrites that placeholder with whatever you enter, updating the empty string dynamically!",
    example: "pokemon_data = \"\"\npokemon_data = input(\"Enter caught Pokémon: \")\nprint(\"Registering Pokédex: \" + pokemon_data)",
    task: "### YOUR MISSION\n\n1. Initialize `pokemon_data` as an empty string `\"\"` or `''`.\n2. Use `input(\"Enter caught Pokémon: \")` to populate it.\n3. Print `\"Registering Pokédex: \" + pokemon_data`.",
    baseCode: "# TODO: Prepare buffer and log caught Pokémon\n",
    hints: ["Use pokemon_data = \"\" to prepare the buffer.","Use pokemon_data = input(\"Enter caught Pokémon: \") to capture the species.","Print \"Registering Pokédex: \" concatenated with pokemon_data."],
    solution: "pokemon_data = \"\"\npokemon_data = input(\"Enter caught Pokémon: \")\nprint(\"Registering Pokédex: \" + pokemon_data)",
    solutionRegex: [/pokemon_data\s*=\s*['"]['"]/, /input/, /print/]
  },
  "vars-multi": {
    title: "Battle Stats: Multiple Assignment",
    headerPrefix: "COMBAT_CALIBRATION",
    missionPrefix: "DUAL_STATS",
    intro: "# Battle Stats: Multiple Assignment\n\nWhen your Pokémon levels up, its Attack and Defense stats increase simultaneously. Python allows multiple variables to be initialized in a single line!",
    technical: "Multiple assignment uses commas to assign several values in one statement: `a, b = 1, 2`.",
    example: "attack_power, defense_power = 85, 75",
    task: "### YOUR MISSION\n\nAssign `attack_power` set to `85` and `defense_power` set to `75` in one line.",
    baseCode: "# TODO: Assign attack_power and defense_power in one line\n",
    hints: ["attack_power, defense_power = 85, 75"],
    solution: "attack_power, defense_power = 85, 75",
    solutionRegex: [/attack_power\s*,\s*defense_power\s*=\s*85\s*,\s*75/]
  },
  "data-strings": {
    title: "Favorite Partner: Strings",
    headerPrefix: "POKEMON_CARD",
    missionPrefix: "SPECIES_TAG",
    intro: "# Favorite Partner: Strings\n\nEvery great trainer has a signature ace Pokémon partner! Store your favorite Pokémon's name in a string variable.",
    technical: "Strings represent text enclosed in single or double quotes.",
    example: "favorite_pokemon = \"Charizard\"\nprint(favorite_pokemon)",
    task: "### YOUR MISSION\n\nCreate a variable `favorite_pokemon` set to `\"Charizard\"`. Print it.",
    baseCode: "# TODO: Set favorite_pokemon and print\n",
    hints: ["favorite_pokemon = \"Charizard\"","print(favorite_pokemon)"],
    solution: "favorite_pokemon = \"Charizard\"\nprint(favorite_pokemon)",
    solutionRegex: [/favorite_pokemon\s*=\s*['"]Charizard['"]/, /print\s*\(\s*favorite_pokemon\s*\)/]
  },
  "data-booleans": {
    title: "Battle Condition: Booleans",
    headerPrefix: "BATTLE_STATE",
    missionPrefix: "STATUS_FLAGS",
    intro: "# Battle Condition: Booleans\n\nIn Pokémon encounters, boolean flags track whether a wild creature is an ultra-rare Shiny or whether your battler has fainted in battle.",
    technical: "Booleans can only be `True` or `False`. Capitalize the first letter.",
    example: "is_shiny = True\nis_fainted = False",
    task: "### YOUR MISSION\n\nSet `is_shiny` to `True` and `is_fainted` to `False`.",
    baseCode: "# TODO: Set shiny and fainted flags\n",
    hints: ["is_shiny = True","is_fainted = False"],
    solution: "is_shiny = True\nis_fainted = False",
    solutionRegex: [/is_shiny\s*=\s*True/, /is_fainted\s*=\s*False/]
  },
  "intro-math": {
    title: "Gym Circuit: Addition",
    headerPrefix: "LEAGUE_HQ",
    missionPrefix: "BADGE_CALC",
    intro: "# Gym Circuit: Addition\n\nTo qualify for the Pokémon League Tournament, tally your badges earned across both Kanto and Johto regions.",
    technical: "The `+` operator adds numerical values together.",
    example: "total = kanto + johto\nprint(total)",
    task: "### YOUR MISSION\n\nCreate `kanto_badges` as `8` and `johto_badges` as `8`. Store the sum in `total_badges` and print it.",
    baseCode: "# TODO: Calculate total gym badges\n",
    hints: ["kanto_badges = 8","johto_badges = 8","total_badges = kanto_badges + johto_badges","print(total_badges)"],
    solution: "kanto_badges = 8\njohto_badges = 8\ntotal_badges = kanto_badges + johto_badges\nprint(total_badges)",
    solutionRegex: [/total_badges\s*=\s*kanto_badges\s*\+\s*johto_badges/, /print\s*\(\s*total_badges\s*\)/]
  },
  "math-complex": {
    title: "Experience Share: Complex Math",
    headerPrefix: "EXP_SHARE",
    missionPrefix: "FORMULA_MATH",
    intro: "# Experience Share: Complex Math\n\nCalculating battle experience points requires priority arithmetic using parentheses and multipliers.",
    technical: "Operations inside parentheses `()` evaluate first before multiplication `*`.",
    example: "gained_exp = (base_exp + bonus_exp) * 0.8\nprint(gained_exp)",
    task: "### YOUR MISSION\n\n1. Set `base_exp` as `80`.\n2. Set `bonus_exp` as `-10`.\n3. Calculate `(base_exp + bonus_exp) * 0.8` and store in `gained_exp`.\n4. Print `gained_exp`.",
    baseCode: "# TODO: Compute gained_exp\n",
    hints: ["base_exp = 80","bonus_exp = -10","gained_exp = (base_exp + bonus_exp) * 0.8","print(gained_exp)"],
    solution: "base_exp = 80\nbonus_exp = -10\ngained_exp = (base_exp + bonus_exp) * 0.8\nprint(gained_exp)",
    solutionRegex: [/gained_exp\s*=\s*\(\s*base_exp\s*\+\s*bonus_exp\s*\)\s*\*\s*0\.8/, /print\s*\(\s*gained_exp\s*\)/]
  },
  "intro-lists": {
    title: "Trainer Party: Lists",
    headerPrefix: "PARTY_SLOTS",
    missionPrefix: "ROSTER_INIT",
    intro: "# Trainer Party: Lists\n\nA Pokémon trainer travels with an active team of party companions. Store your starting combat lineup inside a Python list.",
    technical: "Lists are ordered, mutable collections defined with square brackets `[...]`.",
    example: "pokemon_party = [\"Pikachu\", \"Bulbasaur\", \"Charmander\"]\nprint(pokemon_party)",
    task: "### YOUR MISSION\n\nInitialise your `pokemon_party` list with \"Pikachu\", \"Bulbasaur\", and \"Charmander\". Print the pokemon_party list.",
    baseCode: "# TODO: Initialize pokemon_party list and print\n",
    hints: ["pokemon_party = [\"Pikachu\", \"Bulbasaur\", \"Charmander\"]","print(pokemon_party)"],
    solution: "pokemon_party = [\"Pikachu\", \"Bulbasaur\", \"Charmander\"]\nprint(pokemon_party)",
    solutionRegex: [/pokemon_party\s*=\s*\[/, /print\s*\(\s*pokemon_party\s*\)/]
  },
  "list-indexing": {
    title: "Battle Order: List Indexing",
    headerPrefix: "PARTY_TACTICS",
    missionPrefix: "SLOT_INDEX",
    intro: "# Battle Order: List Indexing\n\nPython lists are zero-indexed! The lead Pokémon on your belt is at index `0`, while the third teammate is at index `2`.",
    technical: "Index `0` accesses the first item; index `2` accesses the third item.",
    example: "lead = pokemon_party[0]\nanchor = pokemon_party[2]",
    task: "### YOUR MISSION\n\n1. Retrieve the first Pokémon (index 0) in the `pokemon_party` list and store in `lead_pokemon`.\n2. Retrieve the third Pokémon (index 2) in the `pokemon_party` list and store in `anchor_pokemon`.\n3. Print `lead_pokemon` and `anchor_pokemon`.",
    baseCode: "pokemon_party = [\"Pikachu\", \"Bulbasaur\", \"Charmander\"]\n# TODO: Extract indices 0 and 2 and print\n",
    hints: ["lead_pokemon = pokemon_party[0]","anchor_pokemon = pokemon_party[2]","print(lead_pokemon)","print(anchor_pokemon)"],
    solution: "lead_pokemon = pokemon_party[0]\nanchor_pokemon = pokemon_party[2]\nprint(lead_pokemon)\nprint(anchor_pokemon)",
    solutionRegex: [/lead_pokemon\s*=\s*pokemon_party\s*\[\s*0\s*\]/, /anchor_pokemon\s*=\s*pokemon_party\s*\[\s*2\s*\]/]
  },
  "list-append": {
    title: "Expanding Your Team: .append()",
    headerPrefix: "POKEMON_PARTY_ADD",
    missionPrefix: "YOUR TASK",
    intro: "# Expanding Your Team: .append()\n\nYou just threw a Pokéball and caught a wild Squirtle! Use `.append()` to add it directly to your active party roster.",
    technical: "The `.append()` method mutates lists in-place, inserting elements at the end.",
    example: "pokemon_party.append(\"Squirtle\")\nprint(pokemon_party)",
    task: "### YOUR MISSION\n\n1. Append \"Squirtle\" to the `pokemon_party` list.\n2. Print the final `pokemon_party` list to confirm.",
    baseCode: "pokemon_party = [\"Pikachu\", \"Bulbasaur\", \"Charmander\"]\n# TODO: Append value and print\n",
    hints: ["pokemon_party.append(\"Squirtle\")","print(pokemon_party)"],
    solution: "pokemon_party.append(\"Squirtle\")\nprint(pokemon_party)",
    solutionRegex: [/pokemon_party\.\s*append\s*\(\s*['"]Squirtle['"]\s*\)/, /print\s*\(\s*pokemon_party\s*\)/]
  },
  "list-pop": {
    title: "PC Storage Box: .pop()",
    headerPrefix: "BOX_TRANSFER",
    missionPrefix: "YOUR TASK",
    intro: "# PC Storage Box: .pop()\n\nBill's PC storage system is full! Use `.pop()` to remove the last deposited Pokémon from the storage box and transfer it.",
    technical: "Calling `.pop()` removes and returns the last element from a list.",
    example: "released = box_pokemon.pop()\nprint(released)",
    task: "### YOUR MISSION\n\n1. Pop the last item from the `box_pokemon` list and store it inside a variable named `released_pokemon`.\n2. Print `released_pokemon` to output the transferred Pokémon.",
    baseCode: "box_pokemon = [\"Rattata\", \"Pidgey\", \"Zubat\"]\n# TODO: Pop last element and print\n",
    hints: ["released_pokemon = box_pokemon.pop()","print(released_pokemon)"],
    solution: "released_pokemon = box_pokemon.pop()\nprint(released_pokemon)",
    solutionRegex: [/released_pokemon\s*=\s*box_pokemon\.\s*pop\s*\(\s*\)/, /print\s*\(\s*released_pokemon\s*\)/]
  },
  "intro-tuples": {
    title: "Sacred Gym Locations: Tuples",
    headerPrefix: "GYM_COORDINATES",
    missionPrefix: "YOUR TASK",
    intro: "# Sacred Gym Locations: Tuples\n\nOfficial Pokémon Gym coordinates are permanent landmarks that must never be accidentally modified or overwritten. Tuples provide immutable collections.",
    technical: "Tuples use parentheses `()` and cannot be modified once created.",
    example: "gym_location = (\"Pallet Town\", 151)\nprint(gym_location)",
    task: "### YOUR MISSION\n\n1. Initialize a tuple named `gym_location` containing \"Pallet Town\" and the number `151`.\n2. Print the `gym_location` tuple.",
    baseCode: "# TODO: Initialize the coordinate tuple and print\n",
    hints: ["gym_location = (\"Pallet Town\", 151)","print(gym_location)"],
    solution: "gym_location = (\"Pallet Town\", 151)\nprint(gym_location)",
    solutionRegex: [/gym_location\s*=\s*\(\s*['"]Pallet Town['"]\s*,\s*151\s*\)/, /print\s*\(\s*gym_location\s*\)/]
  },
  "intro-tuples-immutability": {
    title: "Bag Items vs Coordinates: Immutability",
    headerPrefix: "BAG_CONFIG",
    missionPrefix: "YOUR TASK",
    intro: "# Bag Items vs Map Coordinates: Immutability\n\nYour trainer bag items can be changed and upgraded, but official Gym coordinates are locked in stone!",
    technical: "Lists can be updated in-place (`list[0] = new_val`), while tuples are read-only and will raise a TypeError if modified.",
    example: "bag = [\"Pokéball\"]\nbag[0] = \"Ultra Ball\"",
    task: "### YOUR MISSION\n\n1. Create a list named `trainer_bag` containing the single string \"Pokéball\"\n2. Create a tuple named `gym_coords` containing the numbers `1` and `0`.\n3. Rewrite `trainer_bag[0]` to be \"Ultra Ball\"\n4. Print both `trainer_bag` and `gym_coords`.",
    baseCode: "# TODO: Demonstrate mutable list and immutable tuple\n",
    hints: ["trainer_bag = [\"Pokéball\"]","gym_coords = (1, 0)","trainer_bag[0] = \"Ultra Ball\"","print(trainer_bag)","print(gym_coords)"],
    solution: "trainer_bag = [\"Pokéball\"]\ngym_coords = (1, 0)\ntrainer_bag[0] = \"Ultra Ball\"\nprint(trainer_bag)\nprint(gym_coords)",
    solutionRegex: [/trainer_bag\s*\[\s*0\s*\]\s*=\s*['"]Ultra Ball['"]/, /gym_coords\s*=\s*\(\s*1\s*,\s*0\s*\)/]
  },
  "list-slicing": {
    title: "Battle Roster: List Slicing",
    headerPrefix: "BATTLE_ROSTER_SLICE",
    missionPrefix: "YOUR TASK",
    intro: "# Battle Roster: List Slicing\n\nIn competitive tournament matches, you register a 3-Pokémon battle squad from your larger team. Use list slicing to extract indices 1 through 4 (exclusive).",
    technical: "Slice syntax `list[start:end]` extracts elements from `start` up to but not including `end`.",
    example: "combat_team = battle_roster[1:4]\nprint(combat_team)",
    task: "### YOUR MISSION\n\n1. Slice index `1` to index `4` (exclusive) from the `battle_roster` list.\n2. Store this result in a new variable named `combat_team`.\n3. Print the resulting slice `combat_team`.",
    baseCode: "battle_roster = [\"Pikachu\", \"Charizard\", \"Gengar\", \"Dragonite\", \"Mewtwo\", \"Lucario\"]\n# TODO: Slice indices 1:4 and print\n",
    hints: ["combat_team = battle_roster[1:4]","print(combat_team)"],
    solution: "combat_team = battle_roster[1:4]\nprint(combat_team)",
    solutionRegex: [/combat_team\s*=\s*battle_roster\s*\[\s*1\s*:\s*4\s*\]/, /print\s*\(\s*combat_team\s*\)/]
  },
  "list-filtering": {
    title: "Power Rating: List Comprehensions",
    headerPrefix: "CP_FILTER",
    missionPrefix: "YOUR TASK",
    intro: "# Power Rating: List Comprehensions\n\nFilter high-level Pokémon with Combat Power (CP) ratings greater than 50 to enter the Champion League tournament!",
    technical: "List comprehensions construct lists in one line: `[x for x in list if condition]`.",
    example: "high_combat_power = [cp for cp in pokemon_cp if cp > 50]\nprint(high_combat_power)",
    task: "### YOUR MISSION\n\n1. Use a list comprehension to filter all values **greater than 50** from `pokemon_cp`.\n2. Store the result in a variable named `high_combat_power`.\n3. Print `high_combat_power`.",
    baseCode: "pokemon_cp = [15, 65, 30, 92, 45, 88]\n# TODO: Comprehend and filter values > 50\n",
    hints: ["high_combat_power = [cp for cp in pokemon_cp if cp > 50]","print(high_combat_power)"],
    solution: "high_combat_power = [cp for cp in pokemon_cp if cp > 50]\nprint(high_combat_power)",
    solutionRegex: [/high_combat_power\s*=\s*\[\s*cp\s+for\s+cp\s+in\s+pokemon_cp\s+if\s+cp\s*>\s*50\s*\]/, /print\s*\(\s*high_combat_power\s*\)/]
  },
  "list-comprehension-range": {
    title: "Gym Radar: Even ID Comprehension",
    headerPrefix: "GYM_BEACON_FILTER",
    missionPrefix: "YOUR TASK",
    intro: "# Gym Radar: Even ID Comprehension\n\nIsolate active gym beacons matching even ID numbers using modulo `% 2 == 0` filtering.",
    technical: "Use modulo `x % 2 == 0` inside a comprehension to filter even integers.",
    example: "active_gym_beacons = [g for g in gym_ids if g % 2 == 0]\nprint(active_gym_beacons)",
    task: "### YOUR MISSION\n\n1. Filter only the **even** numbers from the `gym_ids` list using a list comprehension.\n2. Store this filtered list in a new variable named `active_gym_beacons`.\n3. Print `active_gym_beacons`.",
    baseCode: "gym_ids = [101, 102, 103, 104, 105, 106, 107, 108]\n# TODO: Comprehend and filter even indices\n",
    hints: ["active_gym_beacons = [g for g in gym_ids if g % 2 == 0]","print(active_gym_beacons)"],
    solution: "active_gym_beacons = [g for g in gym_ids if g % 2 == 0]\nprint(active_gym_beacons)",
    solutionRegex: [/active_gym_beacons\s*=\s*\[\s*g\s+for\s+g\s+in\s+gym_ids\s+if\s+g\s*%\s*2\s*==\s*0\s*\]/, /print\s*\(\s*active_gym_beacons\s*\)/]
  },
  "intro-input": {
    title: "Safari Zone Scanner: User Input",
    headerPrefix: "SAFARI_ZONE",
    missionPrefix: "YOUR TASK",
    intro: "# Safari Zone Scanner: User Input\n\nPrompt the wandering trainer for the target Pokémon they are searching for in the tall grass!",
    technical: "`input()` captures input as text. Concatenate strings with the `+` operator.",
    example: "target_pokemon = input(\"Enter target Pokémon: \")\nprint(\"Catching Pokémon: \" + target_pokemon)",
    task: "### YOUR MISSION\n\n1. Ask the trainer for the target Pokémon with the prompt: **\"Enter target Pokémon: \"** and store in `target_pokemon`.\n2. Print **\"Catching Pokémon: \"** concatenated with `target_pokemon`.",
    baseCode: "# TODO: Capture target and print\n",
    hints: ["target_pokemon = input(\"Enter target Pokémon: \")","print(\"Catching Pokémon: \" + target_pokemon)"],
    solution: "target_pokemon = input(\"Enter target Pokémon: \")\nprint(\"Catching Pokémon: \" + target_pokemon)",
    solutionRegex: [/target_pokemon\s*=\s*input\s*\(\s*['"]Enter target Pokémon:\s*['"]\s*\)/, /print\s*\(\s*['"]Catching Pokémon:\s*['"]\s*\+\s*target_pokemon\s*\)/]
  },
  "input-mad-libs": {
    title: "Battle Reporter: Mad Libs Story",
    headerPrefix: "POKEMON_CHRONICLE",
    missionPrefix: "BATTLE_CHRONICLE",
    intro: "# Battle Reporter: Mad Libs Story\n\nAssemble an exciting newspaper headline from the Pokémon League championship match!",
    technical: "Gather user inputs and concatenate into a narrative story.",
    example: "story = trainer + \" defeated \" + rival + \" with \" + move + \"!\"\nprint(story)",
    task: "### YOUR MISSION\n\n1. Ask for trainer name with prompt: **\"Trainer name: \"** and store in `trainer`.\n2. Ask for rival name with prompt: **\"Rival name: \"** and store in `rival`.\n3. Ask for attack move with prompt: **\"Attack move: \"** and store in `move`.\n4. Combine into `battle_report` and print: `trainer + \" defeated \" + rival + \" with \" + move + \"!\"`.",
    baseCode: "# TODO: Compose Pokémon battle story\n",
    hints: ["trainer = input(\"Trainer name: \")","rival = input(\"Rival name: \")","move = input(\"Attack move: \")","battle_report = trainer + \" defeated \" + rival + \" with \" + move + \"!\"","print(battle_report)"],
    solution: "trainer = input(\"Trainer name: \")\nrival = input(\"Rival name: \")\nmove = input(\"Attack move: \")\nbattle_report = trainer + \" defeated \" + rival + \" with \" + move + \"!\"\nprint(battle_report)",
    solutionRegex: [/trainer\s*=\s*input\s*\(\s*['"]Trainer name:\s*['"]\s*\)/, /rival\s*=\s*input\s*\(\s*['"]Rival name:\s*['"]\s*\)/, /move\s*=\s*input\s*\(\s*['"]Attack move:\s*['"]\s*\)/, /print\s*\(\s*battle_report\s*\)/]
  },
  "input-mad-libs-pro": {
    title: "League Grand Champion: Multi-Variable Logging",
    headerPrefix: "LEAGUE_ARCHIVE",
    missionPrefix: "CHAMPION_LOG",
    intro: "# League Grand Champion: Multi-Variable Logging\n\nLog the full championship victory record for the Pokémon Hall of Fame!",
    technical: "Concatenate 5 prompt inputs into a formatted League dispatch record.",
    example: "league_log = trainer + \" dispatched \" + pokemon + \" into \" + gym + \" at \" + badge + \". League is \" + status + \"!\"\nprint(league_log)",
    task: "### YOUR MISSION\n\n1. Ask for trainer with **\"Trainer: \"** in `trainer`.\n2. Ask for Pokémon with **\"Pokémon: \"** in `pokemon`.\n3. Ask for gym with **\"Gym: \"** in `gym`.\n4. Ask for badge with **\"Badge: \"** in `badge`.\n5. Ask for status with **\"Status: \"** in `status`.\n6. Combine into `league_log` and print: `trainer + \" dispatched \" + pokemon + \" into \" + gym + \" at \" + badge + \". League is \" + status + \"!\"`.",
    baseCode: "# TODO: Log championship record\n",
    hints: ["Ask all 5 inputs using input()","Combine them with + concatenation and print league_log"],
    solution: "trainer = input(\"Trainer: \")\npokemon = input(\"Pokémon: \")\ngym = input(\"Gym: \")\nbadge = input(\"Badge: \")\nstatus = input(\"Status: \")\nleague_log = trainer + \" dispatched \" + pokemon + \" into \" + gym + \" at \" + badge + \". League is \" + status + \"!\"\nprint(league_log)",
    solutionRegex: [/trainer\s*=\s*input\s*\(\s*['"]Trainer:\s*['"]\s*\)/, /pokemon\s*=\s*input\s*\(\s*['"]Pokémon:\s*['"]\s*\)/, /gym\s*=\s*input\s*\(\s*['"]Gym:\s*['"]\s*\)/, /badge\s*=\s*input\s*\(\s*['"]Badge:\s*['"]\s*\)/, /status\s*=\s*input\s*\(\s*['"]Status:\s*['"]\s*\)/, /print\s*\(\s*league_log\s*\)/]
  },
  "print-formatting": {
    title: "Trainer Card: F-Strings",
    headerPrefix: "TRAINER_CARD",
    missionPrefix: "F_STRING_TAG",
    intro: "# Official Trainer Card: Clean F-Strings\n\nUse an f-string to display your trainer ID and champion badge rank cleanly on your trainer passport.",
    technical: "F-strings allow embedding variables inside string literals using `{variable}` syntax.",
    example: "print(f'Trainer: {alias} | Champion Rank: {level}')",
    task: "### YOUR MISSION\n\nYou have `alias = 'Ash Ketchum'` and `level = 99`. Use an **f-string** to print: `Trainer: Ash Ketchum | Champion Rank: 99`.",
    baseCode: "alias = 'Ash Ketchum'\nlevel = 99\n# TODO: Print using f-string\n",
    hints: ["print(f'Trainer: {alias} | Champion Rank: {level}')"],
    solution: "alias = 'Ash Ketchum'\nlevel = 99\nprint(f'Trainer: {alias} | Champion Rank: {level}')",
    solutionRegex: [/print\s*\(\s*f['"]Trainer:\s*\{alias\}\s*\|\s*Champion\s*Rank:\s*\{level\}['"]\s*\)/]
  },
  "input-fstrings-fun": {
    title: "League Badges: Dynamic Deployment",
    headerPrefix: "LEAGUE_GATE",
    missionPrefix: "F_STRING_INPUT",
    intro: "# Indigo Plateau Security: F-String Input\n\nPrompt the gym challenger for their badge count and destination region, formatting the output with `.upper()`.",
    technical: "Combine integer inputs with string formatting methods like `.upper()` in f-strings.",
    example: "print(f\"Deploying {badges} badges to {region.upper()}...\")",
    task: "### YOUR MISSION\n\n1. Prompt for badge count with: **\"Enter badge count: \"** and store as int in `badges`.\n2. Prompt for region with: **\"Enter region: \"** and store in `region`.\n3. Use an **f-string** to print: `Deploying {badges} badges to {region.upper()}...`.",
    baseCode: "# TODO: Gather badge count and region\n",
    hints: ["badges = int(input(\"Enter badge count: \"))","region = input(\"Enter region: \")","print(f\"Deploying {badges} badges to {region.upper()}...\")"],
    solution: "badges = int(input(\"Enter badge count: \"))\nregion = input(\"Enter region: \")\nprint(f\"Deploying {badges} badges to {region.upper()}...\")",
    solutionRegex: [/print\s*\(\s*f['"]Deploying\s*\{badges\}\s*badges\s*to\s*\{region\.upper\(\)\}\.\.\.['"]\s*\)/]
  },
  "input-cast-int": {
    title: "Item Inventory: Integer Casting",
    headerPrefix: "BAG_AUDIT",
    missionPrefix: "INT_CONVERSION",
    intro: "# Healing Bag Tally: Integer Casting\n\nConvert item string inputs into integers so you can calculate total recovery supplies.",
    technical: "Wrap `input()` inside `int()` to convert text strings to integer numbers.",
    example: "potions = int(input(\"Enter potion count: \"))\nrevives = int(input(\"Enter revive count: \"))\nprint(potions + revives)",
    task: "### YOUR MISSION\n\nTally Pokémon healing items:\n1. Prompt for potion count with **\"Enter potion count: \"** and store it as an integer in `potions`.\n2. Prompt for revive count with **\"Enter revive count: \"** and store it as an integer in `revives`.\n3. Print the sum of these items.",
    baseCode: "# TODO: Cast inputs to int and calculate sum\n",
    hints: ["potions = int(input(\"Enter potion count: \"))","revives = int(input(\"Enter revive count: \"))","print(potions + revives)"],
    solution: "potions = int(input(\"Enter potion count: \"))\nrevives = int(input(\"Enter revive count: \"))\nprint(potions + revives)",
    solutionRegex: [/potions\s*=\s*int\s*\(\s*input/, /revives\s*=\s*int\s*\(\s*input/, /print\s*\(\s*potions\s*\+\s*revives\s*\)/]
  },
  "input-cast-float": {
    title: "Stat Multiplier: Float Casting",
    headerPrefix: "STAT_ANALYZER",
    missionPrefix: "FLOAT_CALIBRATION",
    intro: "# IV & EV Math: Float Conversion\n\nCompetitive Pokémon training requires calculating decimal multipliers for Individual Values (IVs).",
    technical: "Wrap `input()` in `float()` to parse decimals.",
    example: "iv_rating = float(input(\"Enter IV rating: \"))\nstat_mult = float(input(\"Stat multiplier: \"))\nprint(iv_rating * stat_mult)",
    task: "### YOUR MISSION\n\nCalibrate battle stat multipliers:\n1. Prompt for IV rating with **\"Enter IV rating: \"** and store as float in `iv_rating`.\n2. Prompt for stat multiplier with **\"Stat multiplier: \"** and store as float in `stat_mult`.\n3. Print the result of multiplying `iv_rating` by `stat_mult`.",
    baseCode: "# TODO: Cast inputs to float and multiply\n",
    hints: ["iv_rating = float(input(\"Enter IV rating: \"))","stat_mult = float(input(\"Stat multiplier: \"))","print(iv_rating * stat_mult)"],
    solution: "iv_rating = float(input(\"Enter IV rating: \"))\nstat_mult = float(input(\"Stat multiplier: \"))\nprint(iv_rating * stat_mult)",
    solutionRegex: [/iv_rating\s*=\s*float\s*\(\s*input/, /stat_mult\s*=\s*float\s*\(\s*input/, /print\s*\(\s*iv_rating\s*\*\s*stat_mult\s*\)/]
  },
  "control-indentation": {
    title: "Gym Doors: Indentation",
    headerPrefix: "GYM_SECURITY",
    missionPrefix: "INDENT_BLOCK",
    intro: "# Gym Gatekeeper: Indentation Rules\n\nStep past the gym barrier by structuring a clean 4-space indented `if True:` block.",
    technical: "In Python, code blocks under an `if` statement must be indented by exactly 4 spaces.",
    example: "if True:\n    print(\"Accessing...\")",
    task: "### YOUR MISSION\n\n1. Set up an `if True:` condition block.\n2. On the next line, indented with 4 spaces, print **\"Accessing...\"** to challenge the gym leader.",
    baseCode: "# TODO: Indented if block\n",
    hints: ["if True:","    print(\"Accessing...\")"],
    solution: "if True:\n    print(\"Accessing...\")",
    solutionRegex: [/if\s+True\s*:/, /print\s*\(\s*['"]Accessing\.\.\.['"]\s*\)/]
  },
  "control-nested-indent": {
    title: "Champion Room: Double Indentation",
    headerPrefix: "ELITE_FOUR_GATE",
    missionPrefix: "NESTED_INDENT",
    intro: "# Champion Chamber: Double Indentation\n\nPass both Indigo Plateau verification gates using nested `if True:` blocks.",
    technical: "Nested if blocks require double indentation (8 spaces) on their interior executable statements.",
    example: "if True:\n    if True:\n        print(\"CORE ACCESS GRANTED\")",
    task: "### YOUR MISSION\n\n1. Write the outer gate with **`if True:`**.\n2. Nest the inner gate underneath with an inner **`if True:`** (indented by 4 spaces).\n3. On the innermost level (indented with 8 spaces), print **`\"CORE ACCESS GRANTED\"`**.",
    baseCode: "# TODO: Nested if blocks\n",
    hints: ["if True:","    if True:","        print(\"CORE ACCESS GRANTED\")"],
    solution: "if True:\n    if True:\n        print(\"CORE ACCESS GRANTED\")",
    solutionRegex: [/if\s+True\s*:/, /if\s+True\s*:/, /print\s*\(\s*['"]CORE\s+ACCESS\s+GRANTED['"]\s*\)/]
  },
  "control-if": {
    title: "Battle Flag: Simple If",
    headerPrefix: "BATTLE_ARENA",
    missionPrefix: "BATTLE_FLAG",
    intro: "# Arena Encounter: Simple If\n\nWhen entering wild grass, check if an encounter flag is active to initiate battle.",
    technical: "The `if` statement executes its code block if its boolean expression evaluates to True.",
    example: "if in_battle:\n    print(\"BATTLE INITIATED\")",
    task: "### YOUR MISSION\n\nIf `in_battle` is `True`, print `\"BATTLE INITIATED\"`.",
    baseCode: "in_battle = True\n# TODO: Check battle state\n",
    hints: ["if in_battle:","    print(\"BATTLE INITIATED\")"],
    solution: "in_battle = True\nif in_battle:\n    print(\"BATTLE INITIATED\")",
    solutionRegex: [/if\s+in_battle/, /print\s*\(\s*['"]BATTLE INITIATED['"]\s*\)/]
  },
  "control-else": {
    title: "Pokéball Gate: If/Else",
    headerPrefix: "SECURITY_BEACON",
    missionPrefix: "ELSE_LOGIC",
    intro: "# Pokémon Center Gate: If/Else\n\nCheck trainer clearance with an `if/else` block.",
    technical: "The `else` block runs when the preceding `if` condition evaluates to False.",
    example: "if key_valid:\n    print(\"ACCESS GRANTED\")\nelse:\n    print(\"ALARM TRIGGERED\")",
    task: "### YOUR MISSION\n\n1. Construct an `if/else` block evaluating `key_valid`.\n2. If `key_valid` is `True`, print **`\"ACCESS GRANTED\"`**.\n3. Else, print **`\"ALARM TRIGGERED\"`**.",
    baseCode: "key_valid = True\n# TODO: if/else branch\n",
    hints: ["if key_valid:","    print(\"ACCESS GRANTED\")","else:","    print(\"ALARM TRIGGERED\")"],
    solution: "if key_valid:\n    print(\"ACCESS GRANTED\")\nelse:\n    print(\"ALARM TRIGGERED\")",
    solutionRegex: [/if\s+key_valid/, /else\s*:/, /print\s*\(\s*['"]ACCESS GRANTED['"]\s*\)/, /print\s*\(\s*['"]ALARM TRIGGERED['"]\s*\)/]
  },
  "control-elif": {
    title: "Trainer Tier: Elif Levels",
    headerPrefix: "LEAGUE_CLASSIFIER",
    missionPrefix: "TIER_ELIF",
    intro: "# Trainer Badges: Elif Branching\n\nFilter trainer permissions based on badge clearance.",
    technical: "Chaining `elif` conditions allows multiple separate outcomes to be evaluated in order.",
    example: "if clearance == 1:\n    print(\"ROOT ACCESS\")\nelif clearance <= 5:\n    print(\"LEVEL 5 ACCESS\")\nelse:\n    print(\"PERMISSION DENIED\")",
    task: "### YOUR MISSION\n\n1. Build an `if/elif/else` script around `clearance`.\n2. If `clearance` is exactly `1`, print **`\"ROOT ACCESS\"`**.\n3. Elif `clearance` is less than or equal to `5`, print **`\"LEVEL 5 ACCESS\"`**.\n4. Else, print **`\"PERMISSION DENIED\"`**.",
    baseCode: "clearance = 5\n# TODO: Route clearance\n",
    hints: ["if clearance == 1:","elif clearance <= 5:","else:"],
    solution: "if clearance == 1:\n    print(\"ROOT ACCESS\")\nelif clearance <= 5:\n    print(\"LEVEL 5 ACCESS\")\nelse:\n    print(\"PERMISSION DENIED\")",
    solutionRegex: [/if\s+clearance\s*==\s*1/, /elif\s+clearance\s*<=\s*5/, /else\s*:/, /print\s*\(\s*['"]ROOT ACCESS['"]\s*\)/, /print\s*\(\s*['"]LEVEL 5 ACCESS['"]\s*\)/, /print\s*\(\s*['"]PERMISSION DENIED['"]\s*\)/]
  },
  "control-meme-gen": {
    title: "Wild Escape: Smoke Ball Action",
    headerPrefix: "WILD_ESCAPE",
    missionPrefix: "ESCAPE_DECISION",
    intro: "# Wild Encounter: Escape Decision\n\nIf spotted by a dangerous wild Pokémon, throw a Smoke Ball to retreat safely; otherwise complete the capture!",
    technical: "Use boolean variables directly inside `if` statements to handle binary encounter branching.",
    example: "if is_detected:\n    print(\"USE_SMOKE_BALL\")\nelse:\n    print(\"Wild Pokémon captured successfully.\")",
    task: "### YOUR MISSION\n\nCompose an `if/else` guard:\n1. If `is_detected`, print **`\"USE_SMOKE_BALL\"`** to escape.\n2. Else, print **`\"Wild Pokémon captured successfully.\"`**.",
    baseCode: "is_detected = True\n# TODO: Process escape condition\n",
    hints: ["if is_detected:","    print(\"USE_SMOKE_BALL\")","else:","    print(\"Wild Pokémon captured successfully.\")"],
    solution: "if is_detected:\n    print(\"USE_SMOKE_BALL\")\nelse:\n    print(\"Wild Pokémon captured successfully.\")",
    solutionRegex: [/if\s+is_detected/, /else\s*:/, /print\s*\(\s*['"]USE_SMOKE_BALL['"]\s*\)/, /print\s*\(\s*['"]Wild\s+Pokémon\s+captured\s+successfully\.['"]\s*\)/]
  },
  "control-nickname-gen": {
    title: "Trainer Tier: Master Rank",
    headerPrefix: "RANK_EVAL",
    missionPrefix: "TRAINER_TIER",
    intro: "# League Rating: Trainer Rank Assignment\n\nAssign a prestigious title tag to a trainer based on their total battle experience.",
    technical: "Assign a variable inside conditional branches and display it afterwards.",
    example: "if trainer_exp > 9000:\n    player_status = \"Master\"\nelse:\n    player_status = \"Rookie\"\nprint(player_status)",
    task: "### YOUR MISSION\n\nVerify trainer tier:\n1. If `trainer_exp > 9000`, set `player_status` to **`\"Master\"`**.\n2. Else, set `player_status` to **`\"Rookie\"`**.\n3. Finally, print `print(player_status)`.",
    baseCode: "trainer_exp = 9001\nplayer_status = \"\"\n# TODO: Evaluate trainer rank and print\n",
    hints: ["if trainer_exp > 9000:","    player_status = \"Master\"","else:","    player_status = \"Rookie\"","print(player_status)"],
    solution: "trainer_exp = 9001\nif trainer_exp > 9000:\n    player_status = \"Master\"\nelse:\n    player_status = \"Rookie\"\nprint(player_status)",
    solutionRegex: [/if\s+trainer_exp\s*>\s*9000\s*:/, /player_status\s*=\s*['"]Master['"]/, /player_status\s*=\s*['"]Rookie['"]/, /print\s*\(\s*player_status\s*\)/]
  },
  "control-adventure": {
    title: "Tall Grass Adventure: Choice Routing",
    headerPrefix: "GRASS_DECISION",
    missionPrefix: "PATH_SELECT",
    intro: "# Route 1 Crossroads: Adventure Choice\n\nYou arrive at a fork in Route 1: enter the forest (\"1\") or search the hidden cave (\"2\").",
    technical: "Compare `choice` using `==` against string values `'1'` and `'2'`.",
    example: "if choice == \"1\":\n    print(\"Wild Pikachu captured!\")\nelif choice == \"2\":\n    print(\"Found a rare Candy!\")\nelse:\n    print(\"Escaped safely.\")",
    task: "### YOUR MISSION\n\nCompose an encounter router:\n1. If `choice` is **\"1\"**, print **\"Wild Pikachu captured!\"**.\n2. Elif `choice` is **\"2\"**, print **\"Found a rare Candy!\"**.\n3. Else, print **\"Escaped safely.\"**.",
    baseCode: "choice = \"1\"\n# TODO: Route trainer choice\n",
    hints: ["if choice == \"1\":","elif choice == \"2\":","else:"],
    solution: "if choice == \"1\":\n    print(\"Wild Pikachu captured!\")\nelif choice == \"2\":\n    print(\"Found a rare Candy!\")\nelse:\n    print(\"Escaped safely.\")",
    solutionRegex: [/if\s+choice\s*==\s*['"]1['"]\s*:/, /elif\s+choice\s*==\s*['"]2['"]\s*:/, /else\s*:/, /print\s*\(\s*['"]Wild Pikachu captured!['"]\s*\)/, /print\s*\(\s*['"]Found a rare Candy!['"]\s*\)/, /print\s*\(\s*['"]Escaped safely\.['"]\s*\)/]
  },
  "control-multi-elif": {
    title: "League Divisions: Multi Elif",
    headerPrefix: "LEAGUE_BRANCH",
    missionPrefix: "ARENA_ASSIGN",
    intro: "# Championship Arenas: Multi-Branch Routing\n\nRoute trainers to their designated arena depending on their league tier.",
    technical: "Cascading `if/elif/elif/else` blocks inspect multiple alternatives sequentially.",
    example: "if tier == \"champion\":\n    print(\"Hall of Fame access.\")\nelif tier == \"elite\":\n    print(\"Indigo Plateau access.\")",
    task: "### YOUR MISSION\n\nAssign arena locations based on variable `tier`:\n1. If `tier` is **`\"champion\"`**, print **`\"Hall of Fame access.\"`**\n2. Elif `tier` is **`\"elite\"`**, print **`\"Indigo Plateau access.\"`**\n3. Elif `tier` is **`\"gym\"`**, print **`\"Standard Gym arena.\"`**\n4. Else, print **`\"Trainer School training.\"`**",
    baseCode: "tier = \"champion\"\n# TODO: Route trainer tier\n",
    hints: ["if tier == \"champion\":","elif tier == \"elite\":","elif tier == \"gym\":","else:"],
    solution: "if tier == \"champion\":\n    print(\"Hall of Fame access.\")\nelif tier == \"elite\":\n    print(\"Indigo Plateau access.\")\nelif tier == \"gym\":\n    print(\"Standard Gym arena.\")\nelse:\n    print(\"Trainer School training.\")",
    solutionRegex: [/if\s+tier\s*==\s*['"]champion['"]\s*:/, /elif\s+tier\s*==\s*['"]elite['"]\s*:/, /elif\s+tier\s*==\s*['"]gym['"]\s*:/, /else\s*:/, /print\s*\(\s*['"]Hall\s+of\s+Fame\s+access\.['"]\s*\)/, /print\s*\(\s*['"]Indigo\s+Plateau\s+access\.['"]\s*\)/, /print\s*\(\s*['"]Standard\s+Gym\s+arena\.['"]\s*\)/, /print\s*\(\s*['"]Trainer\s+School\s+training\.['"]\s*\)/]
  },
  "control-loops": {
    title: "Pokéball Volley: Range Loop",
    headerPrefix: "TRAINER_LOOP",
    missionPrefix: "BALL_VOLLEY",
    intro: "# Catching Practice: For Loops\n\nAutomate throwing 5 practice Pokéballs in training camp with a `for` loop.",
    technical: "The `range(5)` function generates numbers from 0 up to 4, repeating the loop body 5 times.",
    example: "for i in range(5):\n    print(f\"Pokéball {i+1} thrown\")",
    task: "### YOUR MISSION\n\nUse a `for` loop with `range(5)` to `print` the status message `f\"Pokéball {i+1} thrown\"` for each of the 5 throws.",
    baseCode: "# TODO: Loop 5 times\n",
    hints: ["for i in range(5):","    print(f\"Pokéball {i+1} thrown\")"],
    solution: "for i in range(5):\n    print(f\"Pokéball {i+1} thrown\")",
    solutionRegex: [/for\s+i\s+in\s+range\s*\(\s*5\s*\)/, /print/]
  },
  "loop-data-scan": {
    title: "Cry Decryption: Character Iteration",
    headerPrefix: "POKEDEX_AUDIO",
    missionPrefix: "CRY_DECODE",
    intro: "# Soundwave Analysis: Character Parsing\n\nLoop through every character of Pikachu's intercepted battle cry `\"PIKA\"`.",
    technical: "Iterating through strings sequentially processes each character one by one.",
    example: "for char in message:\n    print(char)",
    task: "### YOUR MISSION\n\nYou've intercepted a Pokémon cry `message`: `\"PIKA\"`. Use a `for` loop to iterate through every character `char` in the variable `message` and `print` it.",
    baseCode: "message = \"PIKA\"\n# TODO: Iterate through characters\n",
    hints: ["for char in message:","    print(char)"],
    solution: "message = \"PIKA\"\nfor char in message:\n    print(char)",
    solutionRegex: [/for\s+char\s+in\s+message/, /print\s*\(\s*char\s*\)/]
  },
  "loop-list-audit": {
    title: "Pokédex Files: Script Audit",
    headerPrefix: "DEX_STORAGE",
    missionPrefix: "PKMN_FILTER",
    intro: "# Dex Storage: Filter Pokémon Data\n\nFilter and load only valid Pokémon data records ending in `.pkmn`.",
    technical: "The `.endswith()` method returns True if a string ends with the specified suffix.",
    example: "for f in discovered_files:\n    if f.endswith(\".pkmn\"):\n        print(f\"Analyzing: {f}\")",
    task: "### YOUR MISSION\n\nScan through `discovered_files`. If a file ends with `\".pkmn\"`, `print` the output line: `f\"Analyzing: {f}\"`.",
    baseCode: "discovered_files = [\"pikachu.pkmn\", \"pokedex.txt\", \"mewtwo.pkmn\", \"save.dat\"]\n# TODO: Audit files\n",
    hints: ["for f in discovered_files:","    if f.endswith(\".pkmn\"):","        print(f\"Analyzing: {f}\")"],
    solution: "discovered_files = [\"pikachu.pkmn\", \"pokedex.txt\", \"mewtwo.pkmn\", \"save.dat\"]\nfor f in discovered_files:\n    if f.endswith(\".pkmn\"):\n        print(f\"Analyzing: {f}\")",
    solutionRegex: [/for\s+f\s+in\s+discovered_files/, /f\.endswith\s*\(\s*['"]\.pkmn['"]\s*\)/, /print/]
  },
  "loop-nested": {
    title: "Region Map: 3x3 Grid Scan",
    headerPrefix: "MAP_RADAR",
    missionPrefix: "KANTO_GRID",
    intro: "# Kanto Radar: Nested Loops\n\nScan a 3x3 map sector for wild legendary Pokémon spawns using nested loops.",
    technical: "Nested loops execute the inner loop in full for every single step of the outer loop.",
    example: "for x in range(3):\n    for y in range(3):\n        print(f\"Kanto - Row: {x}, Col: {y}\")",
    task: "### YOUR MISSION\n\nScan a **3x3 radar grid**. Code nested loops with `range(3)` for `x` and `y`.\n\nInside the inner loop, `print` each coordinate in this exact format: `f\"Kanto - Row: {x}, Col: {y}\"`.\n\nMake sure your `print` is indented with 8 spaces!",
    baseCode: "# TODO: Nested grid loop\n",
    hints: ["for x in range(3):","    for y in range(3):","        print(f\"Kanto - Row: {x}, Col: {y}\")"],
    solution: "for x in range(3):\n    for y in range(3):\n        print(f\"Kanto - Row: {x}, Col: {y}\")",
    solutionRegex: [/for\s+x/, /for\s+y/, /print/]
  },
  "loop-break-continue": {
    title: "Catch Combo: Loop Break",
    headerPrefix: "COMBO_SCANNER",
    missionPrefix: "SAFARI_SAFETY",
    intro: "# Catch Chain: Loop Interruption\n\nLoop through a catch combo of 10 Pokémon. If the encounter index reaches `7`, call `break` to preserve your combo.",
    technical: "The `break` statement halts the loop immediately and resumes execution after the loop body.",
    example: "for i in range(10):\n    if i == 7:\n        break\n    print(i)",
    task: "### YOUR MISSION\n\nLoop through `range(10)`. If encounter index `i` reaches `7`, call `break`. Otherwise, `print` current index `i` using `print(i)`.",
    baseCode: "# TODO: Loop with break condition\n",
    hints: ["for i in range(10):","    if i == 7:","        break","    print(i)"],
    solution: "for i in range(10):\n    if i == 7:\n        break\n    print(i)",
    solutionRegex: [/for\s+i\s+in\s+range/, /if\s+i\s*==\s*7/, /break/, /print/]
  },
  "control-while": {
    title: "Pokémon Center: Energy Charger",
    headerPrefix: "POKEMON_CENTER",
    missionPrefix: "HEAL_CYCLE",
    intro: "# Healing Machine: While Loops\n\nWhile loops run as long as their condition stays True. Monitor the healing machine battery as it recharges your team's Pokéballs.",
    task: "### YOUR MISSION\n\n1. `battery` starts at `100`.\n2. While `battery > 0`, subtract `20` from `battery` to power the healing ray.\n3. `print` the current `battery` level inside the loop.",
  },
  "functions-intro": {
    headerPrefix: "POKECENTER_DOC",
    missionPrefix: "HEAL_ROUTINE",
    intro: "# Pokémon Center Services: Functions\n\nNurse Joy uses a reusable healing protocol instead of repeating treatment code for every visiting trainer!",
    task: "Write a function `heal_pokemon(name)` that prints `f'Healing {name} at Pokémon Center...'`. Call it with `'Pikachu'`.",
    baseCode: "# TODO: Define heal_pokemon function\n",
    solution: "def heal_pokemon(name):\n    print(f'Healing {name} at Pokémon Center...')\n\nheal_pokemon('Pikachu')",
    solutionRegex: [/def\s+heal_pokemon/, /heal_pokemon\s*\(/]
  },
  "functions-recursion": {
    headerPrefix: "EVOLUTION_COUNTDOWN",
    missionPrefix: "RECURSIVE_EXP",
    intro: "# Level Countdown: Recursion\n\nBefore a Pokémon evolves, an energy counter counts down until the evolutionary burst takes place!",
    task: "Write a recursive function `evolution_countdown(count)` that prints the count and calls itself with `count-1` until it reaches `0`. Call it with `5`.",
    baseCode: "# TODO: Define recursive function\n",
    solution: "def evolution_countdown(count):\n    print(count)\n    if count > 0:\n        evolution_countdown(count - 1)\n\nevolution_countdown(5)",
    solutionRegex: [/def\s+evolution_countdown/, /evolution_countdown\s*\(\s*count\s*-\s*1\s*\)/]
  },
  "oop-intro": {
    headerPrefix: "POKEDEX_CLASS",
    missionPrefix: "POKEMON_TEMPLATE",
    intro: "# Creature Species Blueprint: Classes\n\nEvery Pokémon in the wild shares core traits (name, moves, hit points). Instead of creating isolated variables for each creature, define a reusable blueprint called a **Class**.",
    task: "### YOUR MISSION\n\nDefine a base class named `Pokemon`. Use `pass` inside its block under proper indentation.",
    baseCode: "# TODO: Establish base class Pokemon\n",
    hints: ["Use 'class Pokemon:' followed by an indented 'pass'."],
    solution: "class Pokemon:\n    pass",
    solutionRegex: [/class\s+Pokemon/, /pass/]
  },
  "oop-init": {
    headerPrefix: "PROFESSOR_OAK",
    missionPrefix: "NAME_CONSTRUCTOR",
    intro: "# Catching Registration: Constructors\n\nWhen a new Pokémon is registered into the Pokédex, we record its species name immediately using the constructor method `__init__`.",
    task: "### YOUR MISSION\n\nInside `Pokemon`, define the constructor method `__init__` which accepts `self` and a parameter `name`. Assign the `name` value to `self.name`.",
    baseCode: "class Pokemon:\n    # TODO: Add __init__ constructor\n",
    hints: ["def __init__(self, name):","    self.name = name"],
    solution: "class Pokemon:\n    def __init__(self, name):\n        self.name = name",
    solutionRegex: [/def\s+__init__\s*\(\s*self\s*,\s*name\s*\)\s*:/, /self\.name\s*=\s*name/]
  },
  "oop-methods": {
    headerPrefix: "BATTLE_ACTION",
    missionPrefix: "ATTACK_MOVE",
    intro: "# Battle Capabilities: Methods\n\nA Pokémon needs moves to duel in the gym! Functions defined inside a class are called **Methods**. Let's add an attack move.",
    task: "### YOUR MISSION\n\nAdd a `thunderbolt` method to `Pokemon` that `print`s \"Thunderbolt attack\".",
    baseCode: "class Pokemon:\n    def __init__(self, name):\n        self.name = name\n    # TODO: Define thunderbolt method\n",
    hints: ["def thunderbolt(self):","    print(\"Thunderbolt attack\")"],
    solution: "class Pokemon:\n    def __init__(self, name):\n        self.name = name\n    def thunderbolt(self):\n        print(\"Thunderbolt attack\")",
    solutionRegex: [/def\s+thunderbolt\s*\(\s*self\s*\)\s*:/, /print\s*\(\s*['"]Thunderbolt attack['"]\s*\)/]
  },
  "oop-state": {
    headerPrefix: "HEALTH_TRACKER",
    missionPrefix: "FAINT_STATE",
    intro: "# Battle Status: Object State\n\nDuring intense gym encounters, each Pokémon tracks its condition independently (e.g. Healthy vs Fainted).",
    task: "### YOUR MISSION\n\n1. In `__init__`, add a `status` instance variable defaulted to the string \"Healthy\".\n2. Create a method `faint` that updates `self.status` to the string \"Fainted\".",
    baseCode: "class Pokemon:\n    def __init__(self, name):\n        self.name = name\n        # TODO: Add status default\n    # TODO: Add faint method\n",
    hints: ["self.status = \"Healthy\"","def faint(self):","    self.status = \"Fainted\""],
    solution: "class Pokemon:\n    def __init__(self, name):\n        self.name = name\n        self.status = \"Healthy\"\n    def faint(self):\n        self.status = \"Fainted\"",
    solutionRegex: [/self\.status\s*=\s*['"]Healthy['"]/, /def\s+faint/, /self\.status\s*=\s*['"]Fainted['"]/]
  },
  "oop-interaction": {
    headerPrefix: "BATTLE_LINK",
    missionPrefix: "DUEL_OPPONENT",
    intro: "# Gym Arena Clash: Object Interaction\n\nIn Pokémon battles, creatures interact directly with opposing battlers! Methods can accept other instances of a class as arguments.",
    task: "### YOUR MISSION\n\nAdd a `battle` method to `Pokemon` that accepts `other` as its parameter. It should `print` the formatted message: `f\"Battling against: {other.name}\"`.",
    baseCode: "class Pokemon:\n    def __init__(self, name):\n        self.name = name\n    # TODO: Add battle method\n",
    hints: ["def battle(self, other):","    print(f\"Battling against: {other.name}\")"],
    solution: "class Pokemon:\n    def __init__(self, name):\n        self.name = name\n    def battle(self, other):\n        print(f\"Battling against: {other.name}\")",
    solutionRegex: [/def\s+battle\s*\(\s*self\s*,\s*other\s*\)\s*:/, /other\.name/]
  },
  "oop-inheritance": {
    headerPrefix: "LEGENDARY_DEX",
    missionPrefix: "MYTHIC_POKEMON",
    intro: "# Legendary Species: Inheritance\n\nLegendary Pokémon (like Mewtwo or Rayquaza) inherit all general Pokémon traits, but possess mythic signature abilities!",
    task: "### YOUR MISSION\n\nCreate a class `LegendaryPokemon` that inherits from `Pokemon`. Give it a `psystrike` method that `print`s \"Psystrike unleashed\".",
    baseCode: "class Pokemon:\n    def __init__(self, name):\n        self.name = name\n# TODO: Create LegendaryPokemon subclass inheriting from Pokemon\n",
    hints: ["class LegendaryPokemon(Pokemon):","    def psystrike(self):","        print(\"Psystrike unleashed\")"],
    solution: "class Pokemon:\n    def __init__(self, name):\n        self.name = name\n\nclass LegendaryPokemon(Pokemon):\n    def psystrike(self):\n        print(\"Psystrike unleashed\")",
    solutionRegex: [/class\s+LegendaryPokemon\s*\(\s*Pokemon\s*\)\s*:/, /def\s+psystrike/, /print\s*\(\s*['"]Psystrike unleashed['"]\s*\)/]
  },
  "oop-str": {
    headerPrefix: "POKEDEX_SPEECH",
    missionPrefix: "STR_DISPLAY",
    intro: "# Pokédex Voice Readout: __str__\n\nOverride the `__str__` method to make the Pokédex voice declare the Pokémon name cleanly instead of returning a cryptic memory address.",
    task: "### YOUR MISSION\n\nIn `Pokemon`, add the custom method `__str__` that returns: `f\"Pokémon {self.name}\"`.",
    baseCode: "class Pokemon:\n    def __init__(self, name):\n        self.name = name\n    # TODO: Add __str__ method\n",
    hints: ["def __str__(self):","    return f\"Pokémon {self.name}\""],
    solution: "class Pokemon:\n    def __init__(self, name):\n        self.name = name\n    def __str__(self):\n        return f\"Pokémon {self.name}\"",
    solutionRegex: [/def\s+__str__/, /return\s+f['"].*Pokémon.*self\.name.*['"]/]
  },
  "oop-class-vars": {
    headerPrefix: "CREATURE_SPECIES",
    missionPrefix: "UNIVERSAL_TRAIT",
    intro: "# Universal Biology: Shared Class Variables\n\nEvery individual Pokémon has its own nickname and level, but they all share the fundamental scientific classification of \"Pocket Monster\".",
    task: "### YOUR MISSION\n\n1. Define a class variable `classification` set to \"Pocket Monster\" inside `Pokemon` before other initialisers.\n2. `print` the class variable using `Pokemon.classification`.",
    baseCode: "class Pokemon:\n    # TODO: Define class variable 'classification'\n    pass\n# TODO: Print Pokemon.classification\n",
    hints: ["classification = \"Pocket Monster\"","print(Pokemon.classification)"],
    solution: "class Pokemon:\n    classification = \"Pocket Monster\"\n\nprint(Pokemon.classification)",
    solutionRegex: [/classification\s*=\s*['"]Pocket Monster['"]/, /print\s*\(\s*Pokemon\.classification\s*\)/]
  }
};
